plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

gradlePlugin {
    plugins {
        webstart {
            id = 'sktools.webstart'
            implementationClass = 'no.statkart.sktools.gradle.plugins.webstart.WebstartPlugin'
        }
    }
}


dependencies {
    testImplementation project(':build-utils:test-utils')
    testImplementation 'commons-codec:commons-codec:1.2@jar'
}

task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications.matching { it.name == 'pluginMaven' }.each {
        artifact sourceJar
    }
}

