
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Database
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
db_hostname=localhost
db_sid=DEV1
db_port=1521


! Systembruker/password som brukes ved database administrasjon, create.user, export/import etc.
admin_db_username=SYSTEM
admin_db_password=MATRIKKELADM

systemProp.db.oradata=D:\\oracle\\Oradata


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Database - sanntid og historikk
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
sanntid_db_username=HISTORIKKDEMO1
sanntid_db_password=${sanntid_db_username}
sanntid_db_sid=${db_sid}
sanntid_db_hostname=${db_hostname}
sanntid_db_port=${db_port}
sanntid_db_schema=${sanntid_db_username}
sanntid_db_tablespace=${sanntid_db_schema}
sanntid_db_tablespace_index=${sanntid_db_schema}
sanntid_admin_db_username=${admin_db_username}
sanntid_admin_db_password=${admin_db_password}

historikk_db_username=HISTORIKKDEMO1_H
historikk_db_password=${historikk_db_username}
historikk_db_sid=${db_sid}
historikk_db_hostname=${db_hostname}
historikk_db_port=${db_port}
historikk_db_schema=${historikk_db_username}
historikk_db_tablespace=${historikk_db_schema}
historikk_db_tablespace_index=${historikk_db_schema}
historikk_admin_db_username=${admin_db_username}
historikk_admin_db_password=${admin_db_password}
