
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Database
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
db_hostname=localhost
db_sid=DEV1
db_port=1521


! Systembruker/password som brukes ved database administrasjon, create.user, export/import etc.
db_system_username=SYSTEM
db_system_password=MATRIKKELADM

systemProp.db.oradata=D:\\oracle\\Oradata


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Database - sanntid og historikk
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
sanntid_db_system_username=${db_system_username}
sanntid_db_system_password=${db_system_password}

sanntid_db_username=HISTORIKKDEMO1
sanntid_db_password=${sanntid_db_username}
sanntid_db_sid=${db_sid}
sanntid_db_hostname=${db_hostname}
sanntid_db_port=${db_port}
sanntid_db_url=jdbc:oracle:thin:@${sanntid_db_hostname}:${sanntid_db_port}:${sanntid_db_sid}
sanntid_db_schema=${sanntid_db_username}
sanntid_db_tablespace=${sanntid_db_schema}
sanntid_db_tablespace_index=${sanntid_db_schema}

historikk_db_system_username=${db_system_username}
historikk_db_system_password=${db_system_password}

historikk_db_username=HISTORIKKDEMO1_H
historikk_db_password=${historikk_db_username}
historikk_db_sid=${db_sid}
historikk_db_hostname=${db_hostname}
historikk_db_port=${db_port}
historikk_db_url=jdbc:oracle:thin:@${historikk_db_hostname}:${historikk_db_port}:${historikk_db_sid}
historikk_db_schema=${historikk_db_username}
historikk_db_tablespace=${historikk_db_schema}
historikk_db_tablespace_index=${historikk_db_schema}

! oppsett for replikering
replication_db_username=${sanntid_db_username}_GG
replication_db_password=${replication_db_username}
replication_db_schema=${replication_db_username}
replication_db_tablespace=USERS

!SKTOOLS-163: default encoding for sqlfiler
systemProp.sql.file.encoding=UTF-8
