PROMPT Creating Table KOMMUNE_H ...
CREATE TABLE "@historikk_db_schema@"."KOMMUNE_H"
(
	"TVERSION"  		NUMBER(6,0) DEFAULT 1 NOT NULL,
	"TBEGIN_INFO"		VARCHAR2(255 CHAR),
	"TEND_INFO"  		VARCHAR2(255 CHAR),
	"TBEGIN"    		TIMESTAMP(9) DEFAULT SYSTIMESTAMP NOT NULL,
	"TEND"      		TIMESTAMP(9) DEFAULT TO_TIMESTAMP('9999-01-01 00:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF') NOT NULL,
	"ID"		NUMBER(19,0)	NULL,
	"KOMMUNENUMMER"		VARCHAR2(16 CHAR)	NULL,
	"KOMMUNENAVN"		VARCHAR2(255 CHAR)	NULL
)
;

ALTER TABLE "@historikk_db_schema@"."KOMMUNE_H"
ADD CONSTRAINT "C_HIST_KOMMUNE_H" UNIQUE 
(
	"ID",
	"TEND",
	"TBEGIN"
)
USING INDEX (
	CREATE UNIQUE INDEX "@historikk_db_schema@"."KOMMUNE_H_IX_HIST" ON "@historikk_db_schema@"."KOMMUNE_H"
	(
		"ID",
		"TEND",
		"TBEGIN"	
	)
	REVERSE
)
ENABLE
;



PROMPT Creating Table KOMMUNERFORSTED_H ...
CREATE TABLE "@historikk_db_schema@"."KOMMUNERFORSTED_H"
(
	"TVERSION"  		NUMBER(6,0) DEFAULT 1 NOT NULL,
	"TBEGIN_INFO"		VARCHAR2(255 CHAR),
	"TEND_INFO"  		VARCHAR2(255 CHAR),
	"TBEGIN"    		TIMESTAMP(9) DEFAULT SYSTIMESTAMP NOT NULL,
	"TEND"      		TIMESTAMP(9) DEFAULT TO_TIMESTAMP('9999-01-01 00:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF') NOT NULL,
	"STEDID"		NUMBER(19,0)	NULL,
	"KOMMUNEID"		NUMBER(19,0)	NULL
)
;

ALTER TABLE "@historikk_db_schema@"."KOMMUNERFORSTED_H"
ADD CONSTRAINT "C_HIST_KOMMUNERFORSTED_H" UNIQUE 
(
	"STEDID",
	"KOMMUNEID",
	"TEND",
	"TBEGIN"
)
USING INDEX (
	CREATE UNIQUE INDEX "@historikk_db_schema@"."KOMMUNERFORSTED_H_IX_HIST" ON "@historikk_db_schema@"."KOMMUNERFORSTED_H"
	(
		"STEDID",
		"KOMMUNEID",
		"TEND",
		"TBEGIN"	
	)
	REVERSE
)
ENABLE
;



PROMPT Creating Table STED_H ...
CREATE TABLE "@historikk_db_schema@"."STED_H"
(
	"TVERSION"  		NUMBER(6,0) DEFAULT 1 NOT NULL,
	"TBEGIN_INFO"		VARCHAR2(255 CHAR),
	"TEND_INFO"  		VARCHAR2(255 CHAR),
	"TBEGIN"    		TIMESTAMP(9) DEFAULT SYSTIMESTAMP NOT NULL,
	"TEND"      		TIMESTAMP(9) DEFAULT TO_TIMESTAMP('9999-01-01 00:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF') NOT NULL,
	"ID"		NUMBER(19,0)	NULL,
	"STEDSNAVN"		VARCHAR2(255 CHAR)	NULL,
	"OPPDATERTAV"		VARCHAR2(255 CHAR)	NULL
)
;

ALTER TABLE "@historikk_db_schema@"."STED_H"
ADD CONSTRAINT "C_HIST_STED_H" UNIQUE 
(
	"ID",
	"TEND",
	"TBEGIN"
)
USING INDEX (
	CREATE UNIQUE INDEX "@historikk_db_schema@"."STED_H_IX_HIST" ON "@historikk_db_schema@"."STED_H"
	(
		"ID",
		"TEND",
		"TBEGIN"	
	)
	REVERSE
)
ENABLE
;
