apply plugin: 'sktools-dbtools-plugin'


def libraries = [
        drivers: ["com.oracle:ojdbc6:11.2.0.4.0@jar"]
]


//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {
    useDrivers libraries.drivers

    toolset( name:'main', type:'oracle', prefix:'') {

        properties = [
                username: project.properties.get('username', 'BRUKER1'),
                password: project.properties.get('password', 'BRUKER1'),
        ]

        ('a'..'z').each { def name ->
            task("${name}") << { println "$it.name" }
        }

        ('a'..'z').each { def name ->
            task("do${name.toUpperCase()}", dependsOn: name)
        }


        taskSequence('doMCA', description: 'nested sequence task') {
            dependsOn tasks['m']
            dependsOn tasks['c']
            dependsOn tasks['doA']
        }
    }


    taskSequence('taskSequenceYMCA', description: 'Transitive task dependencies executed in sequence') {
        dependsOn dbToolSets.main.tasks['doY']
        dependsOn dbToolSets.main.tasks['doMCA']

        doFirst {
            def expectedSequence = [tasks['y'], tasks['m'], tasks['c'], tasks['a']]
            assert gradle.taskGraph.allTasks.findAll {expectedSequence.contains(it)} == expectedSequence //SKTOOLS-152
        }
    }

}

taskSequence('taskSequenceZXY', description: 'Transitive task dependencies executed in sequence') {
    dependsOn dbToolSets.main.tasks['doZ']
    dependsOn dbToolSets.main.tasks['doX']
    dependsOn dbToolSets.main.tasks['doY']

    doFirst {
        def expectedSequence = [tasks['z'], tasks['x'], tasks['y']]
        assert gradle.taskGraph.allTasks.findAll {expectedSequence.contains(it)} == expectedSequence //SKTOOLS-152
    }
}




task runDemo() {

    //SKTOOLS-152: verifiserer rekkefølge
    dependsOn task('verifyTaskSequence', type:GradleBuild) {
        startParameter.logLevel = LogLevel.QUIET
        tasks = ['taskSequenceZXY']
    }

    //SKTOOLS-152: verifiserer rekkefølge
    dependsOn task('verifyTaskSequence2', type:GradleBuild) {
        startParameter.logLevel = LogLevel.QUIET
        tasks = ['taskSequenceYMCA']
    }

}