group = 'no.statkart.sktools.gradle.plugins.webstart-plugin.demos'

buildscript {
    if (rootProject.ext.has('sktools_versjon')) version = rootProject.ext.get('sktools_versjon')
    if (version == Project.DEFAULT_VERSION) { version = '1.5-SNAPSHOT'; logger.warn "No -Psktools_versjon= defined. Defaulting to \"${version}\""} //nb - dersom ikke default version er satt riktig så blir kjøring ifra demo-katalog feil..

    // Variables to grab from environment + defaults
    ['WEBLOGIC_HOME', 'WEBLOGIC_VERSION', 'MAVEN_REPO'].each { val ->
        if (!rootProject.ext.has(val) && System.getenv(val) != null) {
            rootProject.ext.set(val, System.getenv(val))
        }
    }

    project.ext.set('MAVEN_REPO', project.properties.get('MAVEN_REPO', 'https://nexus.statkart.no/repository/public/'))

    //repository for plugin + jar filer for byggesystem
    repositories {
        mavenLocal()
        maven { name = 'public'; url = MAVEN_REPO }
    }

    //innkobling av plugin jar filer for gradle byggesystem
    dependencies {
        classpath "no.statkart.sktools.gradle:webstart-plugin:${version}"
        classpath "no.statkart.sktools.gradle:weblogic-deploy-plugin:${version}" //trenger en eller annen enkel deploy mulighet
    }

}

allprojects {
    setVersion(rootProject.version)
    tasks.matching { 'runDemo' == it.name }.each {
        it.mustRunAfter clean
    }
}

apply(from:'deploy-ear.gradle')

tasks.clean.doFirst {
    logger.info "Cleaning project ${project.projectDir}"
}
