//prosjekt logik for pakking og deploying av test-ear til weblogic server

apply plugin: 'ear'


project.ext.set('app_url', properties.get('wls.deploy.adminurl', "http://${java.net.InetAddress.localHost.hostName}:7001"))
def appName = 'webstart-plugin-demo'

//legger til action etter at prosjektet er evaluert. Dette da for å få satt riktig navn/versjon på warfiler definert i konfigurasjonen her.
afterEvaluate {

    //dependencies - legger til alle subprosjekt med war plugin aktivert
    subprojects.each { Project subProject ->
        dependencies {
            if (subProject.plugins.hasPlugin('war')) {
                deploy project(path:subProject.path, configuration: 'archives')
            }
            earlib project(path:subProject.path)
        }
    }


    def warMap = subprojects.findAll { it.plugins.hasPlugin('war') }.collectEntries { Project subProject ->
            String warFileName = subProject.configurations['archives'].artifacts.files.singleFile.name
            def path = project.relativePath(subProject.projectDir)
            ["${warFileName}" : "${project.name}/${path}"]
    }

    logger.quiet "configured warMap ->"
    warMap.each {key, value -> logger.quiet "  ${key} -> ${project.app_url}/${value}"}

    ear {
        appDirName 'src/main/application' //default -
        libDirName 'APP-INF/lib'  // default - put dependency libraries into APP-INF/lib inside the generated EAR;
        deploymentDescriptor {
            version = "5"
            displayName = appName
    //        applicationName = "webstart-demoear"
            warMap.each {
                webModule(it.key, it.value)
            }
        }
    }

}




ant.taskdef(name: 'wldeploy', classname: 'weblogic.ant.taskdefs.management.WLDeploy', classpath: libraries.weblogic.asPath)

task deploy(dependsOn: ['assemble', 'undeploy']) {
    doFirst {
        def args = [
                action: 'deploy',
                source: "${ear.archivePath}",
                name: appName,
                user: project.properties.get('wls.deploy.username', 'admmatr'),
                password: project.properties.get('wls.deploy.password', 'matrikkeladm1'),
                adminurl: project.properties.get('wls.deploy.adminurl', 'http://localhost:7001'),
                targets: project.properties.get('wls.deploy.target', 'AdminServer'),
                upload: 'true',
                timeout: '18000',
                verbose: 'true',
                failonerror: 'true',
        ]
        ant.wldeploy(args)
    }
}

task undeploy() {
    doFirst {
        def args = [
                action: 'undeploy',
                name: appName,
                user: project.properties.get('wls.deploy.username', 'admmatr'),
                password: project.properties.get('wls.deploy.password', 'matrikkeladm1'),
                adminurl: project.properties.get('wls.deploy.adminurl', 'http://localhost:7001'),
                targets: project.properties.get('wls.deploy.target', 'AdminServer'),
                graceful: true,
                verbose: true,
                failonerror: true,
        ]
        ant.wldeploy(args)
    }
}



