apply plugin: 'sktools-dbtools-plugin'

description = """
Testing SKTOOLS-59: connection exhaustion

Manual testing with command: gradle testAWholeBunchOfConnections ^
 -Ddb_host=localhost -Ddb_port=1521 -Ddb_sid=DEV1 -Ddb_password=MATRIKKELADM

To change the setting on oracle database edit %ORA_HOME%/NETWORK/ADMIN/listener.ora
 - For more documentation search for "RATE_LIMIT on listener"
   PS: to actuate changes remember to restart tnslistener

"""

def libraries = [
        drivers: ['com.oracle.jdbc:ojdbc6:11.2.0.4@jar']
]


//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {
    useDrivers libraries.drivers

    toolset( name:'main', type:'oracle', prefix:'') {

        task('aWholeBunchOfConnections') {
            def similarTasks = (1..500).collect {
                sqlTask("ping${String.format( "%04d", it )}", sqlFile: 'src/main/sql/ping.sql')
            }

            dependsOn similarTasks
        }



        url = "jdbc:oracle:thin:@${project.ext.oracle_db_host}:${project.ext.oracle_db_port}:${project.ext.oracle_db_sid}"

        properties = [
                username: 'SYSTEM',
                password: System.getProperty('db_password', 'MATRIKKELADM'),
        ]
    }

    task('testAWholeBunchOfConnections', description: 'Opens 500 connections as fast as possible') {
        dependsOn project.convention.plugins['db'].dbToolSets['main'].tasks['aWholeBunchOfConnections']
    }
}
