plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

gradlePlugin {
    plugins {
        wsdoc {
            id = 'sktools.wsdoc'
            implementationClass = 'no.statkart.sktools.gradle.plugins.wsdocgen.WsDocGenPlugin'
        }
    }
}

dependencies {
    implementation project(':build-utils:wsdocgen')

    testImplementation project(':build-utils:test-utils')
}

task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications.all {
        if (it.name == 'pluginMaven') artifact sourceJar
    }
}
