plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

java {
    withSourcesJar()
}

publishing {
    publications {
        pluginMaven(MavenPublication) {
            artifactId = 'wsdocgen-plugin'
        }
    }
}


gradlePlugin {
    plugins {
        wsdoc {
            id = 'sktools.wsdoc'
            implementationClass = 'no.statkart.sktools.gradle.plugins.wsdocgen.WsDocGenPlugin'
        }
    }
}

def pluginPropertiesDir = "$buildDir/plugin-properties"
def pluginProperties = [
    sktools_wsdocgen : "no.statkart.sktools:wsdocgen:${version}" as String,
] as Properties

dependencies {
    testImplementation project(':build-utils:test-utils')
}


// inject av verktøy i testkjøring
tasks.register('testProperties') {
    def outputDir = file("$buildDir/$name")
    def wsdocGenClasspath = project(':build-utils:wsdocgen').sourceSets.main.runtimeClasspath

    inputs.files wsdocGenClasspath
    outputs.dir outputDir

    doLast {
        def properties = [
            sktools_wsdocgen_classpath: wsdocGenClasspath.asPath,
        ]
        outputDir.mkdirs()

        file("$outputDir/WsDocGenPluginTest.properties").withWriter {
             (properties as Properties).store(it, (String) null)
        }
    }
}
pluginUnderTestMetadata.pluginClasspath.from files(testProperties)
pluginUnderTestMetadata.pluginClasspath.from sourceSets.main.output

tasks.register('createPluginProperties') {
    outputs.dir pluginPropertiesDir
    inputs.properties pluginProperties
    doLast {
        def file = layout.projectDirectory.file("$pluginPropertiesDir/no/statkart/sktools/wsdocgen-gradle-plugin.properties").asFile
        file.parentFile.mkdirs()
        file.withWriter {
            pluginProperties.store(it, (String) null)
        }
        logger.info "Created plugin info file: ${file.getAbsolutePath()}"
    }
}
sourceSets.main.resources.srcDir createPluginProperties
