plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

java {
    withSourcesJar()
}

gradlePlugin {
    plugins {
        wsdoc {
            id = 'sktools.wsdoc'
            implementationClass = 'no.statkart.sktools.gradle.plugins.wsdocgen.WsDocGenPlugin'
        }
    }
}

def pluginPropertiesDir = layout.buildDirectory.dir("plugin-properties").get()
def pluginProperties = [
    sktools_wsdocgen : "no.statkart.sktools:wsdocgen:${version}" as String,
] as Properties

dependencies {
    testImplementation project(':build-utils:test-utils')
}


// inject av verktøy i testkjøring
task testProperties {
    def outputDir = layout.buildDirectory.dir("${name}").get().asFile
    inputs.files project(':build-utils:wsdocgen').sourceSets.main.runtimeClasspath
    outputs.dir outputDir

    doLast {
        def properties = [
            sktools_wsdocgen_classpath: project(':build-utils:wsdocgen').sourceSets.main.runtimeClasspath.asPath,
        ]
        outputDir.mkdirs()
        org.gradle.util.internal.GUtil.saveProperties(properties as Properties, file("$outputDir/WsDocGenPluginTest.properties"))
    }
}
pluginUnderTestMetadata.pluginClasspath.from files(testProperties)
pluginUnderTestMetadata.pluginClasspath.from sourceSets.main.output

task createPluginProperties() {
    outputs.dir pluginPropertiesDir
    inputs.properties pluginProperties
    doLast {
        def file = project.file("$pluginPropertiesDir/no/statkart/sktools/wsdocgen-gradle-plugin.properties")
        file.parentFile.mkdirs()
        org.gradle.util.internal.GUtil.saveProperties(pluginProperties, file)
        logger.info "Created plugin info file: ${file.getAbsolutePath()}"
    }
}
sourceSets.main.resources.srcDir createPluginProperties
