group = 'no.statkart.sktools.gradle.plugins.weblogic-wswar-plugin.demos'

// build a map of the dependency artifacts to use. Allows centralized definition of the versions of artifacts to use
project.ext.set('libraries', [:])

//tools.jar for JDK
libraries.'tools.jar' = files("${System.getenv('JAVA_HOME')}/lib/tools.jar").stopExecutionIfEmpty() //JAVA_HOME ikke satt??

libraries.weblogic =  fileTree(dir:"${WEBLOGIC_HOME}", includes:[
        'wlserver_10.3/server/lib/weblogic.jar',
        'wlserver_10.3/server/lib/webservices.jar',
        'wlserver_10.3/server/lib/wljmsclient.jar',
        'modules/javax.annotation_*.jar/',
        'modules/javax.ejb_3*.jar',
        'modules/javax.interceptor_*.jar',
        'modules/javax.servlet_*.jar',
        'modules/javax.transaction_*.jar',
        'modules/com.bea.core.transaction_*.jar',
        'modules/com.bea.core.datasource*.jar',
        'modules/glassfish.jaxws.rt*.jar',
]).stopExecutionIfEmpty() //feilsituasjon dersom WEBLOGIC_HOME ikke er riktig satt



assert gradle.gradleVersion == '1.0' || gradle.gradleVersion >= '1.0-rc-2'

//innkobling av plugin jar filer for gradle byggesystem
buildscript {
    if (rootProject.ext.has('sktools_versjon')) version = rootProject.ext.get('sktools_versjon')
    if (version == Project.DEFAULT_VERSION) { version = '1.3-SNAPSHOT'; logger.warn "No -Psktools_versjon= defined. Defaulting to \"${version}\""} //nb - dersom ikke default version er satt riktig så blir kjøring ifra demo-katalog feil..

    // Variables to grab from environment + defaults
    ['WEBLOGIC_HOME', 'COMPUTERNAME', 'MAVEN_REPO'].each { val ->
        if (!rootProject.ext.has(val) && System.getenv(val) != null) {
            rootProject.ext.set(val, System.getenv(val))
        }
    }

    project.ext.set('MAVEN_REPO', project.properties.get('MAVEN_REPO', 'http://nexus.statkart.no:8090/nexus/content/groups/public/'))

    repositories {
        //bruker kun lokale filer her da dette er et demo prosjekt...
        mavenLocal()

//        maven { name = 'public'; url = MAVEN_REPO }

    }
    dependencies {
        classpath "no.statkart.sktools.gradle:weblogic-wswar-plugin:${version}"
    }
}

allprojects {
    setVersion(rootProject.version)
}
task clean<<{
    logger.info "Cleaning project ${project.projectDir}"
}
