include ':simple-demo'

rootProject.name = 'weblogic-wswar-demos'




//automatisk re-compile og install av siste versjon av plugin til lokal maven (spesifikt for demo-prosjekt)
gradle.projectsLoaded { Gradle g ->
    //dersom ikke nested bygg..
    if (g.parent == null) {
        if (!startParameter.taskNames.isEmpty()) {
            g.rootProject.buildscript {
                StartParameter sp = gradle.startParameter.newBuild()
                sp.taskNames = ['install']
                sp.projectDir = g.rootProject.file('..')

                println 'Asserting project is up to date. Running build on root-project:'
                GradleLauncher.newInstance(sp).run().rethrowFailure();
            }
        }
    }
}

