apply plugin: 'groovy'
apply plugin: 'maven-publish'

group = 'no.statkart.sktools.gradle'

dependencies {
    compileOnly gradleApi()
}


task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourceJar
        }
    }
}
