plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

java {
    withSourcesJar()
}

publishing {
    publications {
        pluginMaven(MavenPublication) {
            artifactId = 'wsgen-plugin'
        }
    }
}


gradlePlugin {
    plugins {
        wsgen {
            id = 'sktools.wsgen'
            implementationClass = 'no.statkart.sktools.gradle.plugins.wsgen.WsdlGenPlugin'
        }
    }
}

dependencies {
    testImplementation project(':build-utils:test-utils')
}

