-- Patcher for Module1 til versjon 1.9.1

-- PATCH DB.MIN.VERSION="<any>"
-- PATCH DATA DB.VERSION="1.9.1" PATCH.NO="1" "Create test table"

CREATE TABLE TEST_TABLE1 (
   ID INTEGER NOT NULL,
   NAVN VARCHAR(32) NOT NULL,
   PRIMARY KEY (ID)
);

-- PATCH INDEX DB.VERSION="1.9.1" PATCH.NO="2" "Indexing names"
CREATE INDEX TEST_TABLE1_IDX_NAME ON TEST_TABLE1(NAVN);

