import groovy.sql.Sql
import java.sql.SQLException

apply plugin: 'sktools-dbtools-plugin'


 // Kort intro til HSQLDB - http://hsqldb.org
 /**
  * Hsqldb er en liten lettvekts database som kan kjøres in memory eller som stand alone.
  * En har mulighet til å persistere informasjon til disk.
  *
  * Dersom en kjører in memory kan en aksessere databasen innenfor samme javavm.
  *
  * Ved aksessering ifra flere prosesser bør en kjøre basen i "stand alone" mode. En har her fortsatt mulighet til
  * å kjøre denne som in memory. Databasen kjører da i en frittstående prosess.
  */
configurations {
    hsqldb
}

dependencies {
    hsqldb 'org.hsqldb:hsqldb:2.2.9'
}


//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {

    useDrivers project.configurations.hsqldb

    toolset( name:'sa', type:'hsqldb', prefix:'') {
        url = "jdbc:hsqldb:hsql://localhost/testPatching${project.version}"
        credentials.username = 'SA'
        credentials.password = ''

        patch {
            name = 'Module1'
            patchTask('Patch_1.9.1', sqlFile: 'src/sql/system_1.9.1/patch/patchModule1_1.9.1.sql')
            patchTask('Patch_1.10', sqlFile: 'src/sql/system_1.10/patch/patchModule1_1.10.sql')
        }

        patch {
            name = 'Module2'
            patchTask('Patch_1.9.1', sqlFile: 'src/sql/system_1.9.1/patch/patchModule2_1.9.1.sql')
            patchTask('Patch_1.10', sqlFile: 'src/sql/system_1.10/patch/patchModule2_1.10.sql')
        }

        sqlTask('assertMinPatchVersion', sqlString: '-- verifies min patch version').doLast {
            patch['Module1'].assertMinVersion '1.9.1' //minste versjon støttet i dette bygget
            patch['Module2'].assertMinVersion '1.9.1' //minste versjon støttet i dette bygget
        }

        taskSequence('createViews', dependsOn: [tasks['assertMinPatchVersion']]) {
            dependsOn sqlTask('createTestTableView_1.9.1', sqlFile: 'src/sql/system_1.9.1/view/createTestTableView_1.9.1.sql') {
                onlyIf { patch['Module1'].currentVersion == '1.9.1' }
                onlyIf { patch['Module2'].currentVersion == '1.9.1' }
            }
            dependsOn sqlTask('createTestTableView_1.10', sqlFile: 'src/sql/system_1.10/view/createTestTableView_1.10.sql') {
                onlyIf { patch['Module1'].currentVersion == '1.10' }
                onlyIf { patch['Module2'].currentVersion == '1.10' }
            }
        }

        sqlTask('ImportEmpty', sqlString:'PROMPT Pseudo task for import')

        sqlTask('tearDownDatabase', sqlString: "SHUTDOWN;", failOnError:false).doFirst {
            println "Tar ned database ${url}" //får noen ganger EOFException her..
        }

        properties = [:]

    }

    task dbPatch(description: 'Patcher databasen opp til siste versjon') {
        int i = 0 //hacker til nytt lag av tasker da gradle 1.9.1 eksekverer dependencies i alfabetisk rekkefølge

        dependsOn project.task(String.format('%s_step%02d', it.name, ++i), dependsOn: dbToolSets['sa'].tasks['Patch_1.9.1Module1'])
        dependsOn project.task(String.format('%s_step%02d', it.name, ++i), dependsOn: dbToolSets['sa'].tasks['Patch_1.9.1Module2'])
        dependsOn project.task(String.format('%s_step%02d', it.name, ++i), dependsOn: dbToolSets['sa'].tasks['Patch_1.10Module1'])
        dependsOn project.task(String.format('%s_step%02d', it.name, ++i), dependsOn: dbToolSets['sa'].tasks['Patch_1.10Module2'])
    }

}


task dbImportEmpty(description: "Import of 'Empty' schema.") {
    dependsOn dbToolSets['sa'].tasks['ImportEmpty']
}


task startUpDatabase(description: 'Forker database i subprosess') {

    //forking the groovy way until GRADLE-1254
    doFirst {
        def cmd = ['java', '-cp', configurations.hsqldb.asPath, 'org.hsqldb.Server',
                '-database.0', 'mem:test', '-dbname.0', "testPatching${project.version}" //definisjon for database med navn "test"
        ]

        println "Starter opp database via kommando: \n\t${cmd.join(' ')}"
        def process = cmd.execute()

        process.in.close()
        process.out.close()
        process.err.close()
    }

    doLast {
//        System.console().readLine('pause for debug..')
    }
}



/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task runDemo(dependsOn:[clean]) {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'



    doLast {
        println 'Forsøker å ta ned evt allerede kjørende database-instans. (forventer feilmelding)'
        forkGradle(['startUpDatabase', 'tearDownDatabase'])

        forkGradle(['startUpDatabase'])

        //verifiserer førtilstand
        forkGradle(['_assertNoTestTable1', '_assertNoTestTable2'])
        
        //kjører inn en patch
        forkGradle(['Patch_1.9.1Module1'])
        forkGradle(['_assertModule1_version1', '_assertNoTestTable2'])

        //kjører inn alle patcher
        forkGradle(['dbPatch'])
        forkGradle(['_assertModule1_version2', '_assertModule2_version2'])

        //tester at man kan kjøre inn alle patcher igjen og igjen..
        forkGradle(['dbPatch'])
        forkGradle(['_assertModule1_version2', '_assertModule2_version2'])


        forkGradle(['tearDownDatabase']) //avslutter prosess for databasen sammen med demo
    }
}



// -- tilstand før patching

task _assertNoTestTable1() << {
    def sql = getSql()
    try {
        sql.eachRow("select count(*) from TEST_TABLE1") { }
        assert false //forventer ikke at tabell finnes
    } catch (SQLException e) {
        assert true
    }
}

task _assertNoTestTable2() << {
    def sql = getSql()
    try {
        sql.eachRow("select count(*) from TEST_TABLE2") { }
        assert false //forventer ikke at tabell finnes
    } catch (SQLException e) {
        assert true
    }
}

// -- tilstand versjon 1.9.1

task _assertModule1_version1() << {
    def sql = getSql()
    sql.eachRow("select count(*) from TEST_TABLE1 where ID=1") {
        assert it[0] == 0
    }
}
task _assertModule2_version1() << {
    def sql = getSql()
    sql.eachRow("select count(*) from TEST_TABLE2 where ID=1") {
        assert it[0] == 0
    }
}


// -- tilstand versjon 2.0

task _assertModule1_version2() << {
    def sql = getSql()
    sql.eachRow("select count(*) from TEST_TABLE1 where ID=1") {
        assert it[0] == 1
    }
}
task _assertModule2_version2() << {
    def sql = getSql()
    sql.eachRow("select count(*) from TEST_TABLE2 where ID=1") {
        assert it[0] == 1
    }
}



//--

task _assertNoPatchTable() << {
    def sql = getSql()
    try {
        sql.eachRow("select count(*) from PATCHINFO") { }
        assert false //forventer ikke at tabell finnes
    } catch (SQLException e) {
        assert true
    }
}

private def getSql() {
    def convention = project.convention.plugins['db'].dbToolSets['sa']
    def sql = Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
    sql
}

private void listPatchInfoTableForComponent(def sql, def component = null) {
    try {
        def sqlString = "select * from PATCHINFO"
        if (component != null)  sqlString += " where component='${component}'"
        println "Utskrift av PATCHINFO component=${component}:\n\n"

        if (sql.rows(sqlString).isEmpty()) {
            println "\t<empty>"
        } else {
            sql.eachRow(sqlString) {
                println it
            }
        }

    } catch (SQLException e) {
        assert false
    }
}

/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(Map props = [:], List tasks) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks.collect {"${project.path}:${it}".toString()}
    sp.projectProperties << props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}