# Default: log INFO to System.out
log4j.rootCategory=INFO, stdout


# stdout appender includes caller's file name and line number
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#log4j.appender.stdout.layout.ConversionPattern=%5p [%t] %4r %m%n
log4j.appender.stdout.layout.ConversionPattern=%-5p %m [%c{1}]%n


### log level for testdata
log4j.logger.no.statkart.sktools.utils.databasepatcher=info
