group = 'no.statkart.sktools.gradle.plugins.wsdocgen-plugin.demos'

// build a map of the dependency artifacts to use. Allows centralized definition of the versions of artifacts to use
project.ext.set('libraries', [:])

//tools.jar for JDK
libraries.'tools.jar' = files("${System.getenv('JAVA_HOME')}/lib/tools.jar").stopExecutionIfEmpty() //JAVA_HOME ikke satt??

assert GradleVersion.version('2.1').compareTo(GradleVersion.current()) <= 0 //lowest gradle version supported

buildscript {
    if (rootProject.ext.has('sktools_versjon')) version = rootProject.ext.get('sktools_versjon')
    if (version == Project.DEFAULT_VERSION) { version = '1.4-SNAPSHOT'; logger.warn "No -Psktools_versjon= defined. Defaulting to \"${version}\""} //nb - dersom ikke default version er satt riktig så blir kjøring ifra demo-katalog feil..

    // Variables to grab from environment + defaults
    ['WEBLOGIC_HOME', 'MAVEN_REPO'].each { val ->
        if (!rootProject.ext.has(val) && System.getenv(val) != null) {
            rootProject.ext.set(val, System.getenv(val))
        }
    }

    project.ext.set('MAVEN_REPO', project.properties.get('MAVEN_REPO', 'http://nexus.statkart.no:8090/nexus/content/groups/public/'))

    //repository for plugin + jar filer for byggesystem
    repositories {

        //bruker lokale filer her da dette er et demo prosjekt...
        mavenLocal()

        maven { name = 'public'; url = MAVEN_REPO }
    }

    //innkobling av plugin jar filer for gradle byggesystem
    dependencies {
        if (!Boolean.valueOf(gradle.startParameter.systemPropertiesArgs.containsKey('samlepom'))) {   //dersom ikke "-Dsamplepom" parameter anngitt
            classpath "no.statkart.sktools.gradle:wsdocgen-plugin:${version}"
        } else {
            classpath "no.statkart.sktools.gradle:gradle-plugins:${version}"    //SKIF-154
        }
    }

//    println "Using artifacts \n\t" + configurations.classpath.files.join("\n\t")

}

allprojects {
    setVersion(rootProject.version)
}
task clean<<{
    logger.info "Cleaning project ${project.projectDir}"
}
