include ':simple-demo'

rootProject.name = 'wsdocgen-demos'




//automatisk re-compile og install av siste versjon av plugin til lokal maven (spesifikt for demo-prosjekt)
gradle.projectsLoaded { Gradle g ->
    //dersom ikke nested bygg..
    if (g.parent == null) {
        if (!startParameter.taskNames.isEmpty()) {
            g.rootProject.buildscript {
                println 'Asserting project is up to date. Running build on plugin-project:'
                g.rootProject.exec() {
                    commandLine 'gradle.bat', 'install'
                    workingDir '..'
                }
            }
        }
    }
}
