plugins {
    id 'java'
    id 'maven-publish'
}

java {
    withSourcesJar()
}

dependencies {
    compileOnly 'jakarta.xml.ws:jakarta.xml.ws-api:3.0.1' //Jakarta EE 9+

    compileOnly platform(libraries.wsdlgen_jakarta_platform) //
    compileOnly 'com.sun.xml.ws:jaxws-rt' //provided

    testRuntimeOnly platform(libraries.wsdlgen_jakarta_platform) //sktools 7.x with jakarta as default
    testRuntimeOnly 'com.sun.xml.ws:jaxws-rt' //provided

    implementation 'io.github.classgraph:classgraph:4.8.186'
    implementation 'commons-cli:commons-cli:1.11.0'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
