plugins {
    id 'java'
    id 'maven-publish'
}

java {
    withSourcesJar()
}

dependencies {
    implementation group: 'com.sun.xml.ws', name: 'jaxws-tools', version: '2.3.5'
    implementation group: 'io.github.classgraph', name: 'classgraph', version: '4.8.114'
    implementation group: 'commons-cli', name: 'commons-cli', version: '1.4'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
