plugins {
    id 'java'
    id 'maven-publish'
}

dependencies {
    implementation 'com.sun.xml.ws:jaxws-tools:2.3.6'
    implementation group: 'io.github.classgraph', name: 'classgraph', version: '4.8.114'
    implementation group: 'commons-cli', name: 'commons-cli', version: '1.4'
}

task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    classifier 'sources'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
        }
    }
}