group = 'no.statkart.sktools.gradle.plugins.webstart-plugin.demos'

// build a map of the dependency artifacts to use. Allows centralized definition of the versions of artifacts to use
project.ext.set('libraries', [:])

//weblogic
libraries.weblogic = fileTree(dir:project.WEBLOGIC_HOME, includes:[
        'wlserver_10.3/server/lib/weblogic.jar',
        'wlserver_10.3/server/lib/webservices.jar',
        'wlserver_10.3/server/lib/wljmsclient.jar',
        'modules/javax.annotation_*.jar/',
        'modules/javax.ejb_3*.jar',
        'modules/javax.interceptor_*.jar',
        'modules/javax.servlet_*.jar',
        'modules/javax.transaction_*.jar',
        'modules/com.bea.core.transaction_*.jar',
        'modules/com.bea.core.datasource*.jar',
        'modules/glassfish.jaxws.rt*.jar',
]).stopExecutionIfEmpty() //feilsituasjon dersom WEBLOGIC_HOME ikke er riktig satt


assert gradle.gradleVersion == '1.0' || gradle.gradleVersion >= '1.0-rc-2'

buildscript {
    def version = rootProject.getProperty('version')
    if (version == Project.DEFAULT_VERSION) version = '1.2-SNAPSHOT' //nb - dersom ikke default version er satt riktig så blir kjøring ifra demo-katalog feil..

    // Variables to grab from environment + defaults
    ['WEBLOGIC_HOME', 'COMPUTERNAME', 'PUBLIC_REPO'].each { val ->
        if (!rootProject.ext.has(val) && System.getenv(val) != null) {
            rootProject.ext.set(val, System.getenv(val))
        }
    }

    project.ext.set('HOSTNAME', project.properties.get('HOSTNAME', "${COMPUTERNAME}.${System.getenv('USERDNSDOMAIN').toLowerCase()}"))
    project.ext.set('PUBLIC_REPO', project.properties.get('PUBLIC_REPO', 'http://skrivap92.statkart.no:8001/nexus/content/groups/public/'))

    //repository for plugin + jar filer for byggesystem
    repositories {
        //bruker lokale filer her da dette er et demo prosjekt...
        mavenLocal()

        mavenRepo name: 'public', url: PUBLIC_REPO
    }

    //innkobling av plugin jar filer for gradle byggesystem
    dependencies {
        classpath "no.statkart.sktools.gradle:webstart-plugin:${version}"
    }


}


apply(from:'deploy-ear.gradle')
