import org.gradle.util.GradleVersion

allprojects {
    defaultTasks 'build'
    group = 'no.statkart.sktools'

    // version kan settes via properties (feks kommandolinje -Psktools_versjon=xxx )
    project.version = sktools_versjon

    // build katalog avledes av Gradle versjon - brukes bla ved parallelle bygg
    buildDir = 'buildGradle' + GradleVersion.current().baseVersion.version

    tasks.withType(AbstractPublishToMaven).configureEach {
        doFirst {
            logger.lifecycle "Publishing ${publication.groupId}:${publication.artifactId}:${publication.version}"
        }
    }
}

// Optional configuration of library versions to use. (not production)
// Values will be read from project.properties with naming convention "version.<key>"
// Simply add version properties to your gradle-user.property file to use this feature.
def libVersion(String name, String defaultValue) {
    project.findProperty('version.' + name) ?: defaultValue //development mode only
}


// build a map of the dependency artifacts to use. Allows centralized definition of the versions of artifacts to
// use. In that respect it serves a role similar to <dependencyManagement> in Maven
project.ext.libraries = [

        //wsdlGen
        wsdlgen_jakarta_platform: 'com.sun.xml.ws:jaxws-ri-bom:3.0.2', // jakarta/EE9+

        // Logging
        slf4j_api: "org.slf4j:slf4j-api:${libVersion('slf4j', '1.7.36')}",
        slf4j_simple: "org.slf4j:slf4j-simple:${libVersion('slf4j', '1.7.36')}",

        // Testing
        assertj: 'org.assertj:assertj-core:3.27.7',
        testng: 'org.testng:testng:7.12.0',
        hsqldb: 'org.hsqldb:hsqldb:2.7.2',
]




subprojects { Project project ->
    apply plugin: 'project-report'
    apply plugin: 'base'


    repositories {
        mavenLocal()
        mavenCentral()
    }

    project.plugins.withType(MavenPublishPlugin) {
        publishing {
            repositories {
                maven {
                    name = "GitHubPackages"
                    url = "https://maven.pkg.github.com/kartverket/SkTools"
                    credentials {
                        username = System.getenv("GITHUB_ACTOR")
                        password = System.getenv("GITHUB_TOKEN") ?: System.getenv("KV_PACKAGES_PAT") ?: System.getenv("GH_PACKAGES_PAT")
                    }
                }
            }
        }
    }

    project.plugins.withType(JavaPlugin) {

        java {
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        }

        // appropriately inject common dependencies into each sub-project
        dependencies {
            testImplementation libraries.assertj
            testImplementation libraries.testng
        }


        project.ext.set('filterProperties', [:])

        project.afterEvaluate {
            if (project.ext.filterProperties.isEmpty())
            project.properties.entrySet().collectEntries(project.ext.filterProperties) {(it.value instanceof String) ? new MapEntry(it.key, it.value) : [:]}
        }


        ['main', 'test'].each { String scope ->
            def unfilteredPropertiesDir = project.file("src/${scope}/resources-filter")
            def filteredResourcesDir = project.file("gen/${scope}/resources")

            def scopeName = scope.replaceFirst(".") {it[0].toUpperCase()}

            if (unfilteredPropertiesDir.isDirectory()) {
                def filterTask = task("filter${scopeName}Resources") {
                    inputs.dir(unfilteredPropertiesDir)

                    inputs.properties(project.filterProperties)
                    outputs.dir(filteredResourcesDir)
                    doLast {
                        delete(filteredResourcesDir);
                        copy {
                            into(filteredResourcesDir)
                            from(unfilteredPropertiesDir)
                            filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: project.filterProperties)
                        }
                        ant.touch() { fileset(dir: filteredResourcesDir)}
                    }
                }
                project.sourceSets."$scope".resources.srcDir filterTask
            }
        }


        /**
         * Testing via TestNG grupper. Se bruk av @Test(groups = "") i koden.
         */
        project.tasks.withType(Test).configureEach { Test test -> //felles for alle test-tasks
            useTestNG()

            systemProperty 'java.io.tmpdir', System.getProperty('java.io.tmpdir')

//            testLogging.showStandardStreams = true

            options.excludeGroups 'broken', 'manual'
            doFirst {
                if (testFramework.class.simpleName == 'TestNGTestFramework') {
                    testFramework.options.with {
                        if (includeGroups) logger.quiet "${test.path}: including test groups ${includeGroups} ..."
                        if (excludeGroups) logger.quiet "${test.path}: excluding test groups ${excludeGroups} ..."
                    }
                }
            }

            if (rootProject.hasProperty('test.remote.debug')) {
                jvmArgs '-Xdebug'
                jvmArgs '-Xnoagent'
                jvmArgs '-Xrunjdwp:transport=dt_socket,address=*:8787,server=y,suspend=y'
            }

            //listening to test execution events
            afterTest { descriptor, result ->
                logger.lifecycle((result.toString() == 'SUCCESS' ? ' Successfully tested' : 'Failed testing') + " : ${descriptor.className}.${descriptor.name}")
                if (result.resultType.name() == 'FAILURE') {
                    logger.error("${result.exception}")
                }
            }
        }
    }


    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8' //SKTOOLS-163: java source in UTF-8 encoding
    }

    tasks.withType(GroovyCompile) {
        options.encoding = 'UTF-8' //SKTOOLS-163: java source in UTF-8 encoding (discriminates java files in the groovy source set)
        groovyOptions.encoding = 'UTF-8' //SKTOOLS-163: groovy source files in UTF-8 encoding (default is UTF-8)
    }

    tasks.withType(Jar) {
        it.manifest.attributes([
            'Specification-Title'   : project.name,
            'Specification-Vendor'  : 'Statens kartverk',
            'Specification-Version' : (gradle.startParameter.projectProperties.get('sktools_versjon') ?: sktools_versjon).replace('-SNAPSHOT', ''),

            //misc build info
            'Build-Gradle'          : gradle.gradleVersion,

            'Implementation-Title'  : "${project.name} bygget for ${(project.version == null || project.version.contains('-SNAPSHOT')) ? 'TEST' : 'Produksjon'}",
            'Implementation-Vendor' : 'Statens kartverk',
            'Implementation-Version': project.version,
        ])
    }
}
