
allprojects {
    apply plugin: 'idea'

    defaultTasks 'build'
    group = 'no.statkart.sktools'

    // version kan settes via properties (feks kommandolinje -P )
    if (ext.has('sktools_versjon')) { project.version = sktools_versjon }

    // valgfri build katalog - kan benyttes for kompilering for flere samtidige Gradle versjoner..
    buildDir = gradle.startParameter.systemPropertiesArgs.get('buildDirName', Project.DEFAULT_BUILD_DIR_NAME)

    afterEvaluate {
        if (plugins.hasPlugin('maven')) {
            uploadArchives.repositories.mavenDeployer {
                repository(url: uri(REPO_UPLOAD_RELEASES)) {
                    authentication([userName: REPO_UPLOAD_RELEASES_USERNAME, password: REPO_UPLOAD_RELEASES_PASSWORD])
                }
            }
        }
    }
}


// Optional configuration of library versions to use. (not production)
// Values will be read from project.properties with naming convention "version.<key>"
// Simply add version properties to your gradle-user.property file to use this feature.
def libVersion(String name, String defaultValue) {
    project.ext.properties.get('version.' + name, defaultValue) //development mode only
}


// build a map of the dependency artifacts to use. Allows centralized definition of the versions of artifacts to
// use. In that respect it serves a role similar to <dependencyManagement> in Maven
project.ext.libraries = [

        log4j: "log4j:log4j:${libVersion('log4j', '1.2.17')}@jar",

        groovy: dependencies.localGroovy(),

        // Testing
        testng: 'org.testng:testng:6.8.7@jar',
        hsqldb: 'org.hsqldb:hsqldb:2.2.8',
]

//tools.jar for JDK
libraries.'tools.jar' = files("${System.getenv('JAVA_HOME')}/lib/tools.jar").stopExecutionIfEmpty() //JAVA_HOME ikke satt??


// Oracle Weblogic dependencies

final Map WEBLOGIC_VERSIONS = [
        WL_10_3_1: '10.3.1',
        WL_10_3_5: '10.3.5',
        WL_10_3_6: '10.3.6',
]
final def weblogicVersion = project.properties.get('WEBLOGIC_VERSION', WEBLOGIC_VERSIONS.WL_10_3_5)
assert WEBLOGIC_VERSIONS.containsValue(weblogicVersion) //husk å utvide byggesystem med ny weblogic version..
assert WEBLOGIC_HOME //WEBLOGIC_HOME maa vaere gitt

// JAX-WS runtime for weblogic
libraries.weblogic_jaxws_rt = files(
        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_6 ? "${WEBLOGIC_HOME}/modules/glassfish.jaxws.rt_1.3.0.0_2-1-5.jar" : [],
        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_5 ? "${WEBLOGIC_HOME}/modules/glassfish.jaxws.rt_1.2.0.0_2-1-5.jar" : [],
        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_1 ? "${WEBLOGIC_HOME}/modules/glassfish.jaxws.rt_1.0.0.0_2-1-4.jar" : [],
)

// Weblogic jar files must be located in the WEBLOGIC_HOME directory since they internally (in their manifest file) refer to other files in the directory
libraries.weblogic_client = files(
        "${WEBLOGIC_HOME}/modules/javax.ejb_3.0.1.jar",
        "${WEBLOGIC_HOME}/modules/javax.interceptor_1.0.jar",
        "${WEBLOGIC_HOME}/modules/javax.transaction_1.0.0.0_1-1.jar",

        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_6 ? "${WEBLOGIC_HOME}/modules/com.bea.core.transaction_2.7.1.0.jar" : [],
        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_5 ? "${WEBLOGIC_HOME}/modules/com.bea.core.transaction_2.7.0.0.jar" : [],
        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_1 ? "${WEBLOGIC_HOME}/modules/com.bea.core.transaction_2.5.1.0.jar" : [],

        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_6 ? "${WEBLOGIC_HOME}/modules/com.bea.core.datasource6_1.10.0.0.jar" : [],
        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_5 ? "${WEBLOGIC_HOME}/modules/com.bea.core.datasource6_1.9.0.0.jar" : [],
        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_1 ? "${WEBLOGIC_HOME}/modules/com.bea.core.datasource6_1.6.0.0.jar" : [],

        libraries.weblogic_jaxws_rt,
)

// Weblogic jar files must be located in the WEBLOGIC_HOME directory since they internally (in their manifest file) refer to other files in the directory
libraries.weblogic_server = files(
        "${WEBLOGIC_HOME}/wlserver_10.3/server/lib/weblogic.jar",
        "${WEBLOGIC_HOME}/wlserver_10.3/server/lib/webservices.jar",
        "${WEBLOGIC_HOME}/wlserver_10.3/server/lib/wljmsclient.jar",

        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_6 ? "${WEBLOGIC_HOME}/modules/javax.annotation_1.0.0.0_1-0.jar" : [],
        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_5 ? "${WEBLOGIC_HOME}/modules/javax.annotation_1.0.0.0_1-0.jar" : [],
        weblogicVersion == WEBLOGIC_VERSIONS.WL_10_3_1 ? "${WEBLOGIC_HOME}/modules/javax.annotation_1.1.jar" : [],

        "${WEBLOGIC_HOME}/modules/javax.servlet_1.0.0.0_2-5.jar",

        libraries.weblogic_client,
)

libraries.weblogic = files(
        libraries.weblogic_server,
        libraries.weblogic_client,
)



def boolean isJavaProject(Project project) {
    return project.subprojects.size() == 0 && !project.name.endsWith('-ear') && !project.name.endsWith('-test')
}


subprojects { Project project ->
    apply plugin: 'project-report'
    apply plugin: 'base'


    repositories {
        mavenLocal()
        mavenRepo name: 'public', url: "${rootProject.MAVEN_REPO}"
    }


    if (isJavaProject(project)) {
        apply plugin: 'java'

        sourceCompatibility = '1.6'
        targetCompatibility = '1.6'


        // appropriately inject common dependencies into each sub-project
        dependencies {

            testCompile libraries.testng

        }


        project.ext.set('filterProperties', [:])

        project.afterEvaluate {
            if (project.ext.filterProperties.isEmpty())
            project.properties.entrySet().collectEntries(project.ext.filterProperties) {(it.value instanceof String) ? new MapEntry(it.key, it.value) : [:]}
        }


        ['main', 'test'].each { String scope ->
            def unfilteredPropertiesDir = project.file("src/${scope}/resources-filter")
            def filteredResourcesDir = project.file("gen/${scope}/resources")

            def scopeName = scope.replaceFirst(".") {it[0].toUpperCase()}

            if (unfilteredPropertiesDir.isDirectory()) {
                def filterTask = task("filter${scopeName}Resources") {
                    inputs.dir(unfilteredPropertiesDir)

                    @org.gradle.api.tasks.Input
                    Map<String, Object> filterProperties = project.filterProperties
                    outputs.dir(filteredResourcesDir)
                    doLast {
                        delete(filteredResourcesDir);
                        copy {
                            into(filteredResourcesDir)
                            from(unfilteredPropertiesDir)
                            filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: filterProperties)
                        }
                        ant.touch() { fileset(dir: filteredResourcesDir)}
                    }
                }
                project.sourceSets."$scope".resources.srcDir filteredResourcesDir
                project.processResources.dependsOn filterTask

                project.tasks.ideaModule.dependsOn filterTask
                project.tasks.ideaModule.doFirst {
                    println "...mkdir ${project.relativePath(filteredResourcesDir)}"
                    project.mkdir(filteredResourcesDir)
                }
            }
        }



        // Får Idea til å legge build katalog for alle moduler i en egen felles topp katalog (out/production, out/test)
        project.idea.module {
            inheritOutputDirs = true
//            scopes.PROVIDED.plus += configurations.provided
        }


        test {
            ignoreFailures = gradle.startParameter.systemPropertiesArgs.get('ignoreFailures', 'true') == 'true' //Gradle feiler ikke dersom denne er true. Kan ikke være true dersom en gjør en install eller uploadArchives

            useTestNG() {
                excludeGroups('broken')
                listeners << 'org.testng.reporters.XMLReporter' // For Jenkins siden Gradle 1.5+ ikke tar med default listerners som standard lenger
            }

            jvmArgs '-Xmx512m'
            if (rootProject.hasProperty('test.remote.debug')) {
                jvmArgs '-Xdebug'
                jvmArgs '-Xnoagent'
                jvmArgs '-Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y'
            }

//            systemProperty "file.encoding", "UTF-8"
//            defaultCharacterEncoding = "UTF-8"

            //listening to test execution events
            afterTest { descriptor, result  ->
              logger.lifecycle("${result.toString() == 'SUCCESS' ? ' Sucessfully tested' : 'Failed testing'} : ${descriptor.className}#${descriptor.name}")
              if (result.resultType.name() == 'FAILURE') {
                  logger.error("${result.exception}")
              }
            }

            onOutput { descriptor, event ->
                if (event.destination == TestOutputEvent.Destination.StdErr) {
                    logger.error('' + descriptor + ", error: " + event.message)
                } else {
                    logger.info('\t' + event.message)
                }
            }

        }
    }

    tasks.withType(GroovyCompile) {
        groovyOptions.encoding = System.getProperty('file.encoding') //SKTOOLS-83: groovy source files in system encoding (default is UTF-8)
    }

}

allprojects {
    afterEvaluate {
        tasks.withType(Jar) {
            it.manifest {
                attributes([
                        'Specification-Title': project.name,
                        'Specification-Vendor': 'Statens kartverk',
                        'Specification-Version': sktools_versjon,

                        //misc build info
                        'Build-By': System.getenv('USERNAME'),
                        'Build-Machine': System.getenv('COMPUTERNAME'),
                        'Build-Repo': MAVEN_REPO,
                        'Build-Gradle': gradle.gradleVersion,

                        'Implementation-Title': "${project.name} bygget for ${version.contains('-SNAPSHOT') ? 'TEST' : 'Produksjon'}",
                        'Implementation-Version': project.version,
                        'Implementation-Vendor': 'Statens kartverk',
                ])
            }
        }
    }
}

afterEvaluate {

    idea.project {
        jdkName = '1.6'
        languageLevel = '1.6'

        ipr {
            //adding Perforce as default vcs by tinkering with the output *.ipr file before it's written out
            withXml {
                def node = it.asNode()
                def component = node.appendNode('component', ['name': 'VcsDirectoryMappings'])
                component.appendNode('mapping', ['directory': '', 'vcs': 'Perforce'])
            }
        }
    }

    // branch spesifike navn for prosjekt og workspace fil.
    ideaWorkspace {
        outputFile = file("${project.name}-${project.version.toString().replace('-SNAPSHOT', '')}-gradle${gradle.gradleVersion}.iws")
    }
    idea.project {
        outputFile = file("${project.name}-${project.version.toString().replace('-SNAPSHOT', '')}-gradle${gradle.gradleVersion}.ipr")
    }

    // gradle spesifik iml fil da gradle dependencies ligger på hver modul
    allprojects {
        idea.module {
            outputFile = file("${project.name}-gradle${gradle.gradleVersion}.iml")
        }
    }

}

buildscript {

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Miljøvariable for konfigurasjon av byggemiljø
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    [
            'JAVA_HOME',
            'COMPUTERNAME',
            'LOCALHOSTNAME',
            'WEBLOGIC_HOME',
            'WEBLOGIC_VERSION',
    ].each { key ->
        if (!project.hasProperty(key) && System.getenv(key) != null) {
            project.ext.setProperty(key, System.getenv(key))
        }
    }

    if (!project.hasProperty('LOCALHOSTNAME')) {
        project.ext.setProperty('LOCALHOSTNAME', '${COMPUTERNAME}.statkart.no')
    }

    ext.MAVEN_REPO = rootProject.properties.get('MAVEN_REPO', System.getenv('MAVEN_REPO'))
    if (ext.MAVEN_REPO == null) {
        ext.MAVEN_REPO = 'http://nexus.statkart.no:8090/nexus/content/groups/public/'
        logger.warn "warning: MAVEN_REPO not defined. Defaulting to ${MAVEN_REPO}"
    }

    ext.REPO_UPLOAD_RELEASES = rootProject.properties.get('REPO_UPLOAD_RELEASES', System.getenv('REPO_UPLOAD_RELEASES'))
    if (ext.REPO_UPLOAD_RELEASES == null) {
        ext.REPO_UPLOAD_RELEASES = 'http://admin:admin123@nexus.statkart.no:8090/nexus/content/repositories/releases/'
        logger.warn "warning: REPO_UPLOAD_RELEASES not defined. Defaulting to ${'http://admin:***@nexus.statkart.no:8090/nexus/content/repositories/releases/'}"
    }
    ext.REPO_UPLOAD_RELEASES_USERNAME = rootProject.properties.get('REPO_UPLOAD_RELEASES_USERNAME', System.getenv('REPO_UPLOAD_RELEASES_USERNAME'))
    if (ext.REPO_UPLOAD_RELEASES_USERNAME == null) {
        ext.REPO_UPLOAD_RELEASES_USERNAME = 'admin'
        logger.warn "warning: REPO_UPLOAD_RELEASES_USERNAME not defined. Defaulting to admin"
    }
    ext.REPO_UPLOAD_RELEASES_PASSWORD = rootProject.properties.get('REPO_UPLOAD_RELEASES_PASSWORD', System.getenv('REPO_UPLOAD_RELEASES_PASSWORD'))
    if (ext.REPO_UPLOAD_RELEASES_PASSWORD == null) {
        ext.REPO_UPLOAD_RELEASES_PASSWORD = 'admin123'
        logger.warn "warning: REPO_UPLOAD_RELEASES_PASSWORD not defined. Defaulting to default admin password"
    }

}
