include ':build-utils'
include ':build-utils:sql-parser'
include ':build-utils:db-tools'

include ':gradle-plugins'
include ':gradle-plugins:dbtools-plugin'
include ':gradle-plugins:filterproperties-plugin'
include ':gradle-plugins:ideaextensions-plugin'
include ':gradle-plugins:weblogic-wsclient-plugin'
include ':gradle-plugins:weblogic-wswar-plugin'
include ':gradle-plugins:webstart-plugin'





rootProject.name = 'sktools'

