include ':build-utils:test-utils'

include ':build-utils'
include ':build-utils:sql-parser'
include ':build-utils:db-tools'
include ':build-utils:wsdocgen'
include ':build-utils:xjc-plugins'

include ':gradle-plugins'
include ':gradle-plugins:dbtools-plugin'
include ':gradle-plugins:filterproperties-plugin'
include ':gradle-plugins:ideaextensions-plugin'
include ':gradle-plugins:weblogic-plugin'
include ':gradle-plugins:weblogic-wsclient-plugin'
include ':gradle-plugins:weblogic-wswar-plugin'
include ':gradle-plugins:weblogic-deploy-plugin'
include ':gradle-plugins:webstart-plugin'
include ':gradle-plugins:wsdocgen-plugin'
include ':gradle-plugins:xjc-plugin'




rootProject.name = 'sktools'
