group = 'no.statkart.sktools.gradle.plugins.filter-resources-plugin.demos'

allprojects {
    defaultTasks 'clean', 'runDemo'
}

assert GradleVersion.version('1.0').compareTo(GradleVersion.current()) <= 0 //lowest gradle version supported

//innkobling av plugin jar filer for gradle byggesystem
buildscript {
    if (rootProject.ext.has('sktools_versjon')) version = rootProject.ext.get('sktools_versjon')
    if (version == Project.DEFAULT_VERSION) { version = '1.3-SNAPSHOT'; logger.warn "No -Psktools_versjon= defined. Defaulting to \"${version}\""} //nb - dersom ikke default version er satt riktig så blir kjøring ifra demo-katalog feil..

    // Variables to grab from environment + defaults
    ['WEBLOGIC_HOME', 'COMPUTERNAME', 'MAVEN_REPO', 'JAVA_HOME'].each { val ->
        if (!rootProject.ext.has(val) && System.getenv(val) != null) {
            rootProject.ext.set(val, System.getenv(val))
        }
    }

    project.ext.set('MAVEN_REPO', project.ext.properties.get('MAVEN_REPO', 'http://nexus.statkart.no:8090/nexus/content/groups/public/'))

    repositories {
        //bruker kun lokale filer her da dette er et demo prosjekt...
        mavenLocal()

        maven { name = 'public'; url = MAVEN_REPO }

    }

    dependencies {
        classpath "no.statkart.sktools.gradle:filter-resources-plugin:${version}"
        classpath "no.statkart.sktools.gradle:ideaextensions-plugin:${version}"
    }

}

allprojects {
    setVersion(rootProject.version)
}
task clean<<{
    logger.info "Cleaning project ${project.projectDir}"
}
