apply plugin: 'sktools-dbtools-plugin'

//hjelpefunksjon for eksekveringsrekkefølge dersom task blir kjørt
def dependsOnIfExecuted = rootProject.getDependsOnIfExecuted()

configureDatabasePlugin {
    useDrivers libraries.ojdbc

    project.ext.tns = "${sanntid_db_sid}_${sanntid_db_hostname}"


    /**
     * Toolset for DBA med script for:
     *
     *  - Vedlikehold av grants for brukere på systemnivå
     *  - Opprettelse/sletting av tablespace
     *  - Opprettelse/sletting av brukere
     */
    toolset(name: 'system', type: 'oracle', prefix: 'system') {

        sqlTask('CreateSanntidTablespace', sqlFile: 'src/main/sql/demo/system/tablespace/CreateSanntidTablespace.sql') {
            dependsOnIfExecuted it, sqlTask('DropSanntidTablespace', sqlFile: 'src/main/sql/demo/system/tablespace/DropSanntidTablespace.sql')
        }

        task('CreateUsers') {
            dependsOn sqlTask('CreateSanntidUser', sqlFile: 'src/main/sql/demo/system/user/CreateSanntidUser.sql') {
                dependsOnIfExecuted it, tasks['CreateSanntidTablespace']
                dependsOnIfExecuted it, sqlTask('DropSanntidUser', sqlFile: 'src/main/sql/demo/system/user/DropSanntidUser.sql', failOnError: false)
            }
            dependsOn sqlTask('CreateReplicationUser', sqlFile: 'src/main/sql/demo/system/user/CreateReplicationUser.sql') {
                dependsOnIfExecuted it, sqlTask('DropReplicationUser', sqlFile: 'src/main/sql/demo/system/user/DropReplicationUser.sql', failOnError: false)
            }
        }


        task('GrantUsers') {
            dependsOn sqlTask('GrantSanntidUser', sqlFile: 'src/main/sql/demo/system/grant/GrantSanntidUser.sql') {
                dependsOnIfExecuted it, tasks['CreateSanntidUser']
            }
            dependsOn sqlTask('GrantReplicationUser', sqlFile: 'src/main/sql/demo/system/grant/GrantReplicationUser.sql') {
                dependsOnIfExecuted it, tasks['CreateReplicationUser']
            }
        }

        properties += [
                sanntid_db_username: sanntid_db_username,
                sanntid_db_password: sanntid_db_password,
                sanntid_db_sid: sanntid_db_sid,
                sanntid_db_tablespace: sanntid_db_tablespace,
                sanntid_db_tablespace_index: sanntid_db_tablespace_index,
        ]


        properties += [
                replication_db_username: replication_db_username,
                replication_db_password: replication_db_password,
                replication_db_tablespace: replication_db_tablespace,
        ]


        if (System.properties.containsKey('db.oradata')) { properties.put('db_oradata', System.getProperty('db.oradata')) }

        credentials.username = sanntid_db_system_username
        credentials.password = sanntid_db_system_password
        url = "jdbc:oracle:thin:@${sanntid_db_hostname}:${sanntid_db_port}:${sanntid_db_sid}"
        driver = 'oracle.jdbc.OracleDriver'
    }



    /**
     * Toolset for SA-bruker med script for:
     *
     *  - Vedlikehold av grants for brukere på skjema-nivå
     *  - Opprettelse og vedlikehold av skjema (inkludert patching)
     *
     *  - Mekanikk for migrering til og fra historikk skjema
     */
    toolset(name: 'sanntid', type: 'oracle', prefix: 'sanntid') {

        sqlTask('CreateSanntidSchema', sqlFile: 'src/main/sql/demo/sanntid/schema/CreateSanntidSchema.sql') {
            dependsOn taskSequence('PurgeSanntidSchema') {
                dependsOn sqlTask('PurgeSanntidTables', sqlFile: 'src/main/sql/demo/sanntid/schema/PurgeSanntidTables.sql')
                dependsOn sqlTask('PurgeSanntidSynonyms', sqlFile: 'src/main/sql/demo/sanntid/schema/PurgeSanntidSynonyms.sql')
            }
        }

        task('GrantUsers')


//        sqlTask('FylkerOgKommuner', sqlFile: 'src/main/sql/sanntid/data/FylkerOgKommuner.sql')

        properties += [
                sanntid_db_username: sanntid_db_username,
                sanntid_db_schema: sanntid_db_schema,
                sanntid_db_tablespace: sanntid_db_tablespace,
                sanntid_db_tablespace_index: sanntid_db_tablespace_index,
        ]


        /*
         * Tillegg for Replikeringsbruker
         * Denne brukeren blir alltid opprettet, alltid. Se dbSetUpSanntidUsers
         */
        tasks['GrantUsers'].with {
            dependsOn sqlTask('GrantReplicationUser', sqlFile: 'src/main/sql/demo/replication/grant/GrantReplicationUser.sql') {
                dependsOnIfExecuted it, project.dbToolSets['system'].tasks['CreateReplicationUser']
            }
        }
        properties += [
                replication_db_username: replication_db_username,
                replication_db_schema: replication_db_schema,
        ]


        credentials.username = sanntid_db_system_username
        credentials.password = sanntid_db_system_password
        url = "jdbc:oracle:thin:@${sanntid_db_hostname}:${sanntid_db_port}:${sanntid_db_sid}"
        driver = 'oracle.jdbc.OracleDriver'
    }




    task('dbSetUpSanntidUsers', group: 'Database', description: 'Oppretter tablespace og bruker for sanntid data') {
        dependsOn dbToolSets['system'].tasks['CreateSanntidTablespace']
        dependsOn dbToolSets['system'].tasks['CreateUsers']
        dependsOn dbToolSets['system'].tasks['GrantUsers']
    }

    taskSequence('dbTearDownSanntidUsers', group: 'Database', description: 'Sletter tablespace og bruker for sanntid data') {
        dependsOn dbToolSets['system'].tasks['DropSanntidUser']
        dependsOn dbToolSets['system'].tasks['DropSanntidTablespace']

        dependsOn dbToolSets['system'].tasks['DropReplicationUser']
    }

    task('dbCreateSanntidSchema') {
        dependsOn dbToolSets['sanntid'].tasks['CreateSanntidSchema']
    }

    task('dbGrantUsers', description: 'Grants for brukere') {
        dependsOn dbToolSets['system'].tasks['GrantUsers']
        dependsOn dbToolSets['sanntid'].tasks['GrantUsers']
    }



    //global tasks...

    task('dbClean') {
        dependsOn 'dbTearDownSanntidUsers'
    }

    task('dbSetUpUsers') {
        dependsOn 'dbSetUpSanntidUsers'
    }

    taskSequence('dbInit') {
        dependsOn 'dbCreateSanntidSchema'
        dependsOn 'dbGrantUsers'
    }

}

