apply plugin: 'sktools-dbtools-plugin'

//hjelpefunksjon for eksekveringsrekkefølge dersom task blir kjørt
def dependsOnIfExecuted = rootProject.getDependsOnIfExecuted()

configureDatabasePlugin {
    useDrivers libraries.ojdbc

    project.ext.tns = "${sanntid_db_sid}_${sanntid_db_hostname}"


    /**
     * Toolset for SYSTEM-bruker
     */
    toolset(name: 'admin', type: 'oracle', prefix: 'admin') {

        sqlTask('CreateSanntidTablespace', sqlFile: 'src/main/sql/demo/system/tablespace/CreateSanntidTablespace.sql') {
            dependsOnIfExecuted it, sqlTask('DropSanntidTablespace', sqlFile: 'src/main/sql/demo/system/tablespace/DropSanntidTablespace.sql')
        }

        sqlTask('CreateSanntidUser', sqlFile: 'src/main/sql/demo/system/user/CreateSanntidUser.sql') {
            dependsOnIfExecuted it, sqlTask('DropSanntidUser', sqlFile: 'src/main/sql/demo/system/user/DropSanntidUser.sql', failOnError: false)
        }


        properties += [
                sanntid_db_username: sanntid_db_username,
                sanntid_db_password: sanntid_db_password,
                sanntid_db_sid: sanntid_db_sid,
                sanntid_db_tablespace: sanntid_db_tablespace,
                sanntid_db_tablespace_index: sanntid_db_tablespace_index,
        ]


        sqlTask('CreateReplicationUser', sqlFile: 'src/main/sql/demo/system/user/CreateReplicationUser.sql') {
            dependsOnIfExecuted it, sqlTask('DropReplicationUser', sqlFile: 'src/main/sql/demo/system/user/DropReplicationUser.sql', failOnError: false)
        }

        properties += [
                replication_db_username: replication_db_username,
                replication_db_password: replication_db_password,
                replication_db_tablespace: replication_db_tablespace,
        ]


        if (System.properties.containsKey('db.oradata')) { properties.put('db_oradata', System.getProperty('db.oradata')) }

        credentials.username = sanntid_admin_db_username
        credentials.password = sanntid_admin_db_password
        url = "jdbc:oracle:thin:@${sanntid_db_hostname}:${sanntid_db_port}:${sanntid_db_sid}"
        driver = 'oracle.jdbc.OracleDriver'
    }



    /**
     * Toolset for SANNTID-bruker
     */
    toolset(name: 'sanntid', type: 'oracle', prefix: 'sanntid') {

        sqlTask('CreateSanntidSchema', sqlFile: 'src/main/sql/demo/sanntid/schema/CreateSanntidSchema.sql') {
            dependsOn taskSequence('PurgeSanntidSchema') {
                dependsOn sqlTask('PurgeSanntidTables', sqlFile: 'src/main/sql/demo/sanntid/schema/PurgeSanntidTables.sql')
                dependsOn sqlTask('PurgeSanntidSynonyms', sqlFile: 'src/main/sql/demo/sanntid/schema/PurgeSanntidSynonyms.sql')
            }
        }

        task('GrantUsers')


        tasks['GrantUsers'].with {
            dependsOn sqlTask('GrantSanntidUser', sqlFile: 'src/main/sql/demo/sanntid/grant/GrantSanntidUser.sql') {
                dependsOnIfExecuted it, project.dbToolSets['admin'].tasks['CreateSanntidUser']
            }
        }


//        sqlTask('FylkerOgKommuner', sqlFile: 'src/main/sql/sanntid/data/FylkerOgKommuner.sql')

        properties += [
                sanntid_db_username: sanntid_db_username,
                sanntid_db_schema: sanntid_db_schema,
                sanntid_db_tablespace: sanntid_db_tablespace,
                sanntid_db_tablespace_index: sanntid_db_tablespace_index,
        ]


        /*
         * Tillegg for Replikeringsbruker
         * Denne brukeren blir alltid opprettet, alltid. Se dbSetUpSanntidUsers
         */
        tasks['GrantUsers'].with {
            dependsOn sqlTask('GrantReplicationUser', sqlFile: 'src/main/sql/demo/replication/grant/GrantReplicationUser.sql') {
                dependsOnIfExecuted it, project.dbToolSets['admin'].tasks['CreateReplicationUser']
            }
        }
        properties += [
                replication_db_username: replication_db_username,
                replication_db_schema: replication_db_schema,
        ]


        credentials.username = sanntid_admin_db_username
        credentials.password = sanntid_admin_db_password
        url = "jdbc:oracle:thin:@${sanntid_db_hostname}:${sanntid_db_port}:${sanntid_db_sid}"
        driver = 'oracle.jdbc.OracleDriver'
    }




    taskSequence('dbSetUpSanntidUsers', group: 'Database', description: 'Oppretter tablespace og bruker for sanntid data') {
        dependsOn dbToolSets['admin'].tasks['CreateSanntidTablespace']
        dependsOn dbToolSets['admin'].tasks['CreateSanntidUser']
        dependsOn dbToolSets['sanntid'].tasks['GrantSanntidUser']

        dependsOn dbToolSets['admin'].tasks['CreateReplicationUser']
        dependsOn dbToolSets['sanntid'].tasks['GrantReplicationUser']
    }

    taskSequence('dbTearDownSanntidUsers', group: 'Database', description: 'Sletter tablespace og bruker for sanntid data') {
        dependsOn dbToolSets['admin'].tasks['DropSanntidUser']
        dependsOn dbToolSets['admin'].tasks['DropSanntidTablespace']

        dependsOn dbToolSets['admin'].tasks['DropReplicationUser']
    }

    task('dbCreateSanntidSchema') {
        dependsOn dbToolSets['sanntid'].tasks['CreateSanntidSchema']
    }

    task('dbGrantUsers', description: 'Grants for brukere') {
        dependsOn dbToolSets['sanntid'].tasks['GrantUsers']
    }



    //global tasks...

    task('dbClean') {
        dependsOn 'dbTearDownSanntidUsers'
    }

    task('dbSetUpUsers') {
        dependsOn 'dbSetUpSanntidUsers'
    }

    taskSequence('dbInit') {
        dependsOn 'dbCreateSanntidSchema'
        dependsOn 'dbGrantUsers'
    }

}

//tasker for kodegenerering
task genHistorikkSchemaTempateFromSchema() {

    apply to: it, from: parent.file('genHistorikkSchemaTempateFromSchema.gradle')
    doFirst {
        println "Genererer skjema DDL for historikk basert på skjema hentet ifra gjeldende skjema for sanntid.."
    }

    doLast {
        genHistorikkSchemaTempateFromSchema(
                filename: 'src/main/sql/demo/sanntid/schema/CreateHistorikkSchema.sql',
                dbToolset: dbToolSets['admin'],
                sourceSchema: sanntid_db_schema,
                targetSchema: historikk_db_schema,
                excludeTables: {['SEQUENCE'].contains(it)},
                historikkColumnNames: [TVERSION: 'TVERSION', TBEGIN_INFO: 'TBEGIN_INFO', TEND_INFO: 'TEND_INFO', TBEGIN: 'TBEGIN', TEND: 'TEND'],
        )
    }
}