apply plugin: 'sktools-weblogic-wswar-plugin'

/**
 * Demonstrerer og tester at kompilering av koblet kildekode fungerer.
 * Dette er kildekode som ligger i samme {@link org.gradle.api.tasks.SourceSet}
 */

dependencies {
    weblogic libraries.weblogic
    weblogicCompile libraries.'tools.jar'
}

weblogicWsWar {
    sourceSet {
        java.srcDir 'src/weblogic/nonstandard'    //default is 'src/weblogic/java'
    }
}






task runDemo() {
    dependsOn 'testCompileWeblogicJava'
}

task testCompileWeblogicJava(dependsOn:'compileWeblogicJava') << {
    assert file("build/classes/weblogic/${project.name}.war/WEB-INF/classes/demo/PingHelper.class").exists()
}
