plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

gradlePlugin {
    plugins {
        filterResources {
            id = 'sktools.filter-resources'
            implementationClass = 'no.statkart.sktools.gradle.plugins.filterresources.FilterResourcesPlugin'
        }
    }
}

dependencies {
    testImplementation project(':build-utils:test-utils')
}

task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourceJar
        }
    }
}
