plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

gradlePlugin {
    plugins {
        dbtools {
            id = 'sktools.dbtools'
            implementationClass = 'no.statkart.sktools.gradle.plugins.dbtools.database.DbtoolsPlugin'
        }
    }
}

def pluginPropertiesDir = "$buildDir/plugin-properties"
sourceSets {
    main {
        output.dir(pluginPropertiesDir, builtBy: 'createPluginProperties')
    }
}

def pluginProperties = [
    sktools_dbtools : "no.statkart.sktools:db-tools:${version}" as String,
] as Properties

dependencies {
    implementation project(':build-utils:db-tools')
    implementation project(':build-utils:sql-parser') //pga SqlExecutor

    testImplementation project(':build-utils:test-utils')
    testImplementation libraries.hsqldb
}

pluginUnderTestMetadata.doFirst {
    pluginUnderTestMetadata.pluginClasspath.from project(':build-utils:db-tools').sourceSets.main.runtimeClasspath
}

task createPluginProperties() {
    outputs.dir pluginPropertiesDir
    inputs.properties pluginProperties
    doLast {
        def file = project.file("$pluginPropertiesDir/no/statkart/sktools/dbtools-gradle-plugin.properties")
        file.parentFile.mkdirs()
        org.gradle.util.GUtil.saveProperties(pluginProperties, file)
        logger.info "Created plugin info file: ${file.getAbsolutePath()}"
    }
}
tasks.processResources.dependsOn createPluginProperties


task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier "sources"
}

publishing {
    publications.all {
        if (it.name == 'pluginMaven') artifact sourceJar
    }
}


