plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

java {
    withSourcesJar()
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}


//gradlePlugin {
//    plugins {
//        dbtools {
//            id = 'sktools.dbtools'
//            implementationClass = 'no.statkart.sktools.gradle.plugins.dbtools.database.DbtoolsPlugin'
//        }
//    }
//}

def pluginPropertiesDir = "$buildDir/plugin-properties"
def pluginProperties = [
    sktools_dbtools : "no.statkart.sktools:db-tools:${version}" as String,
] as Properties

dependencies {
    implementation project(':build-utils:db-tools')
    implementation project(':build-utils:sql-parser') //pga SqlExecutor

    testImplementation project(':build-utils:test-utils')
    testImplementation libraries.hsqldb
}


// inject av verktøy i testkjøring
task testProperties {
    def outputDir = file("$buildDir/$name")

    inputs.files project(':build-utils:db-tools').sourceSets.main.runtimeClasspath
    outputs.dir outputDir

    doLast {
        def properties = [
            sktools_dbtools_classpath: project(':build-utils:db-tools').sourceSets.main.runtimeClasspath.asPath,
            libraries_hsqldb : libraries.hsqldb,
        ]
        outputDir.mkdirs()
        org.gradle.util.GUtil.saveProperties(properties as Properties, file("$outputDir/DbtoolsPluginTest.properties"))
    }
}
pluginUnderTestMetadata.pluginClasspath.from files(testProperties)
pluginUnderTestMetadata.pluginClasspath.from sourceSets.main.output
sourceSets.test.resources.srcDir testProperties

task createPluginProperties() {
    outputs.dir pluginPropertiesDir
    inputs.properties pluginProperties
    doLast {
        def file = project.file("$pluginPropertiesDir/no/statkart/sktools/dbtools-gradle-plugin.properties")
        file.parentFile.mkdirs()
        org.gradle.util.GUtil.saveProperties(pluginProperties, file)
        logger.info "Created plugin info file: ${file.getAbsolutePath()}"
    }
}
sourceSets.main.resources.srcDir createPluginProperties
