apply plugin: 'maven'
apply plugin: 'groovy'

project.version = '1.2'
group = 'no.statkart.sktools.gradle'



dependencies {
    compile project(':build-utils:db-tools')

    testCompile libraries.hsqldb

    //std groovy version defined in root project
    groovy libraries.groovy

    //gradle api til byggesystemm blir benyttet som std
    compile gradleApi()

    //test
    testCompile project(':build-utils:test-utils')

}

task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
    onlyIf { gradle.taskGraph.hasTask(install) || gradle.taskGraph.hasTask(uploadArchives) } //only when published..
}


artifacts {
    archives sourcesJar
}

