/******************************************************************************************************************** **
 * Demonstrasjon av gradle måten å strukturere opp kildekoden på
 ******************************************************************************************************************** */

apply plugin: 'java'




/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task demo(dependsOn:'clean') {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    doLast {

        println 'Printer sourceSets definisjon...'
        forkGradle(['printSourceSets'])

        println 'Tester IntelliJ integrasjon før build...'
        forkGradle(['cleanIdea'])
        forkGradle(['ideaModule', 'assertIdeaModule'])

        println 'Tester IntelliJ integrasjon etter build...'
        forkGradle(['cleanIdea', 'build'])
        forkGradle(['ideaModule', 'assertIdeaModule'])

    }
}



task assertIdeaModule() {
    doFirst {
        file("${project.name}.iml").text.with {
//        assert it.contains("build/resources/special")    //forventer at sti for egenproduserte ressurser ligger på classpath
//        assert it.contains("build/classes/special")    //forventer at sti for egenproduserte classes ligger på classpath
        }

    }
}


task printSourceSets() {
    doFirst {
        logger.info "SourceSets defined: "
        project.convention.plugins.java.sourceSets.each { s ->
            ['java', 'allJava', 'resources', 'filterResources', 'groovy', 'allGroovy', 'allSource'].each { id ->
                try {
                    def prefix = "${s.name}.${id}"
                    s."$id".srcDirs.each { println "$prefix <- ".padLeft(prefix.size() + 5, ' ') + project.relativePath(it); prefix = prefix.replaceAll(/./, ' ')  }
                    println()
                } catch (MissingPropertyException mpe) {
                    assert true //ok her
                }
            }
        }
    }
}


/******************************************************************************************************************** **
 * Helper method for forking gradle builds programmatically. Using gradle Tooling API
 * (Only relevant for testing)
 ******************************************************************************************************************** */
void forkGradle(List<String> tasks, Map props = [:]) {
    org.gradle.tooling.ProjectConnection connection = org.gradle.tooling.GradleConnector.newConnector().forProjectDirectory(project.projectDir).connect();
    try {
        org.gradle.tooling.BuildLauncher build = connection.newBuild()
                .forTasks(tasks.collect { "${project.path}:${it}".toString() } as String[])
                .withArguments(props.collect { "-P${it.key}=${it.value}" } << ['-DnoMavenBootstrap=true'] as String[])
                .run();
    } finally {
        connection.close();
    }
}


