apply plugin: 'sktools-dbtools-plugin'


description = """\

    Demo av hvordan en kan sette opp en database med forskjellige brukere.

    Eksempelet kan enkelt utvides til å omfatte flere databaser.
"""

configurations {
    drivers
}

dependencies {
    drivers 'org.hsqldb:hsqldb:2.2.8'
}


//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {

    useDrivers configurations.drivers


    useToolset('hsqldb', 'Sa', 'main/sql/system') {

        url = "jdbc:hsqldb:mem:testbase"

        credentials.username = 'SA'
        credentials.password = ''
    }

    useToolset('hsqldb', 'Bruker1', 'main/sql/bruker1') {

        url = "jdbc:hsqldb:mem:testbase"

        credentials.username = 'BRUKER1'
        credentials.password = 'BRUKER1'
    }

}


task dbInit {

    description = 'Setter opp demobase'
    def tasks = [
            tasks.SaCreateUsers,
            tasks.Bruker1CreateTable1
    ]

    tasks.each {
        dependsOn = it.dependsOn
    }

    doLast {
        tasks.each {
            println "${name} -> ${it.path}"
            it.execute()
        }
    }

}


