/******************************************************************************************************************** **
 *
 * Demonstrasjon på hvordan en kan sette opp en database med forskjellige brukere.
 *
 * Eksempelet kan enkelt utvides til å omfatte flere databaser.
 *
 ******************************************************************************************************************** */

apply plugin: 'sktools-dbtools-plugin'


//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {

    useDrivers 'org.hsqldb:hsqldb:2.3.3'

    toolset( name:'sa', type:'hsqldb', prefix:'sa') {
        url = "jdbc:hsqldb:mem:testbase"

        credentials.username = 'SA'
        credentials.password = ''

        sqlTask( 'CreateUsers', sqlFile:'src/main/sql/system/CreateUsers.sql')

        properties = [brukernavn:'BRUKER1']
        properties += [brukernavn:'BRUKER1']
    }

    toolset( name:'bruker1', type:'hsqldb', prefix:'bruker1') {
        url = "jdbc:hsqldb:mem:testbase"

        credentials.username = 'BRUKER1'
        credentials.password = 'BRUKER1'

        sqlTask( 'CreateTable1', sqlFile:'src/main/sql/bruker1/CreateTable1.sql')
    }

}

task('dbInit', description: 'Setter opp demobase') {
    dependsOn tasks.saCreateUsers
    dependsOn tasks.bruker1CreateTable1

    tasks.bruker1CreateTable1.mustRunAfter tasks.saCreateUsers
}

/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task runDemo() {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    Assert.that('dbInit').describedAs('credentialsSeparationAmongToolsets').leadsTo(project).withState {
        assertTable1AccessForSA()
        assertTable1AccessForBruker1()
    }

}


class Assert {
    def taskName
    List<String> taskNames
    Project project
    List<Closure> prep = []

    static def previousTask = null

    static Assert that(String... taskNames) {
        Assert instance = new Assert(); instance.taskNames = taskNames; return instance
    }

    Assert describedAs(String taskName) {
        this.taskName = taskName; this
    }

    Assert prep(Closure prepProjectBeforeAsserts) {
        prep << prepProjectBeforeAsserts; this
    }

    Assert leadsTo(Project project = project) {
        this.project = project; this
    }

    Assert withState(Closure check) {
        def task = project.task(taskName, type: GradleBuild) {
            dir = project.projectDir
            tasks = taskNames
            startParameter.projectProperties = [sktools_versjon: "${project.version}"]
            startParameter.projectProperties << project.gradle.startParameter.projectProperties
            prep.reverseEach { Closure beforeAsserts -> doFirst { beforeAsserts.setDelegate(this); beforeAsserts.run()}}
            doLast { check.setDelegate(this); check.run() }
            doFirst {
                toConsole('--------------------------------------------------------------------------------');
                toConsole("Testing use case: ${taskName} tasks=${taskNames}\n\n\n");
            }
            doLast {
                toConsole "\n  ...end of test case: ${taskName}"
                toConsole('--------------------------------------------------------------------------------\n\n');
            }
            outputs.upToDateWhen { false } //always run this...
        }
        project.tasks['runDemo'].dependsOn task

        if (previousTask) task.dependsOn previousTask //ordered execution of asserts...
        previousTask = task
        this
    }

    //convenience methods and asserts....

    void assertTable1AccessForSA() {
        def convention = project.convention.plugins['db'].dbToolSets['sa']
        def sql = groovy.sql.Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
        sql.eachRow("select count(*) from BRUKER1.TABLE1") {
            assert it[0] == 0
        }
    }

    void assertTable1AccessForBruker1() {
        def convention = project.convention.plugins['db'].dbToolSets['bruker1']
        def sql = groovy.sql.Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
        sql.eachRow("select count(*) from TABLE1") {
            assert it[0] == 0
        }
        sql.eachRow("select count(*) from BRUKER1.TABLE1") {
            assert it[0] == 0
        }
    }


    private void toConsole(def message) {
        project.logger.quiet(message)
    }


}


