plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

gradlePlugin {
    plugins {
        provided {
            id = 'sktools.provided'
            implementationClass = 'no.statkart.sktools.gradle.plugins.provided.ProvidedPlugin'
        }
    }
}

dependencies {
    testImplementation project(':build-utils:test-utils')
}

task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications.matching { it.name == 'pluginMaven' }.each {
        artifact sourceJar
    }
}
