plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

gradlePlugin {
    plugins {
        ideaextensions {
            id = 'sktools.ideaextensions'
            implementationClass = 'no.statkart.sktools.gradle.plugins.ideaextensions.IdeaExtensionsPlugin'
        }
    }
}

dependencies {
    testImplementation project(':build-utils:test-utils')
}

task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications.matching { it.name == 'pluginMaven' }.each {
        artifact sourceJar
    }
}
