apply plugin: 'sktools-dbtools-plugin'


configurations {
    drivers
}

dependencies {
    drivers "com.oracle:ojdbc6:11.2.0.2.0@jar"
}


ext.db_username = 'BRUKER1'
ext.db_password = 'BRUKER1'


//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {


    useDrivers configurations.drivers

    useToolset('oracle', '', 'main/sql') {

        //mandatory, required property
        project.ext.set 'oracle_db_host', 'localhost'
        project.ext.set 'oracle_db_port', '1521'
        project.ext.set 'oracle_db_sid', '<YOUR_SID>'


        url = "jdbc:oracle:thin:@${project.ext.oracle_db_host}:${project.ext.oracle_db_port}:${project.ext.oracle_db_sid}"
    }

}
