apply plugin: 'sktools-ideaextensions-plugin'
apply plugin: 'groovy'


sourceSets {
    //main sourceSet som blir brukt av Intellij
    main {
        java.srcDir 'src/main2/java'
        allJava.srcDir 'src/main2/allJava' // defineres ikke som allSource
    }

    //legger til nytt sourceSet
    hiddenSource {
        java.srcDir 'src/hidden/java2'
        groovy.srcDir 'src/hidden/groovy2'
        resources.srcDir 'src/hidden/resources2'

        allGroovy.srcDir 'src/hidden/allGroovy' // defineres ikke som allSource
        allJava.srcDir 'src/hidden/allJava' // defineres ikke som allSource
    }
}

task runDemo() {
    dependsOn 'testFolderGeneration'
    dependsOn 'testSourceFolderDefs'
}

tasks.clean.dependsOn tasks.cleanIdea
tasks.clean.doLast {
    logger.quiet("..deleting {}", project.file('src'))
    project.delete('src')
}

//tester at iml filen inneholder folders for main og test sourceSet  [SKIF-178]
task('testSourceFolderDefs', dependsOn: tasks.idea) << {
    file("${project.name}.iml").text.with { fileContents ->
        [
                'src/main/java',
                'src/main2/java',
                'src/main/groovy',
                'src/main/resources',

                'src/test/java',
                'src/test/groovy',
                'src/test/resources',
        ].each {
            assert fileContents.contains(it) //forventer at iml fil inneholder filstier
        }

    }
}

//tester at mapper blir generert opp ihht sourceSet  [SKIF-178]
task('testFolderGeneration', dependsOn: tasks.idea) << {
    [
            'src/main/java',
            'src/main2/java',
            'src/main2/allJava',
            'src/main/resources',

            'src/hiddenSource/java',
            'src/hidden/java2',
            'src/hidden/allJava',

            'src/hiddenSource/groovy',
            'src/hidden/groovy2',
            'src/hidden/allGroovy',

            'src/hiddenSource/resources',
            'src/hidden/resources2',
    ].each {
        file(it).with {
            if (!it.name.contains('all')) {
                assert it.exists() //forventer at mapper ihht til sourceSet er blitt opprettet
                assert it.isDirectory()
            } else {
                assert !it.exists() //forventer ikke at mapper for *allJava og *allGroovy blir opprettet
            }
        }
    }
}