plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

//deprecated - fjernes i 1.6
group = 'no.statkart.sktools.gradle'

dependencies {
    implementation project(':gradle-plugins:weblogic-plugin')

    testImplementation project(':build-utils:test-utils')
    testImplementation project(':gradle-plugins:weblogic-wswar-plugin')
}

pluginUnderTestMetadata.doFirst {
    if (org.gradle.util.GradleVersion.current() >= org.gradle.util.GradleVersion.version('4.10')) {
        pluginUnderTestMetadata.pluginClasspath.from project(':gradle-plugins:weblogic-wswar-plugin').sourceSets.main.output
    } else {
        pluginUnderTestMetadata.pluginClasspath += project(':gradle-plugins:weblogic-wswar-plugin').sourceSets.main.output
    }
}

task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications.all {
        artifact sourceJar
    }
}
