plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

//deprecated - fjernes i 1.6
group = 'no.statkart.sktools.gradle'

gradlePlugin {
    plugins {
        weblogicWsclient {
            id = 'sktools.weblogic-wsclient'
            implementationClass = 'no.statkart.sktools.gradle.plugins.weblogic.wsclient.WeblogicWsClientPlugin'
        }
    }
}

dependencies {
    compileOnly gradleApi()

    implementation project(':gradle-plugins:weblogic-plugin')

    testImplementation gradleTestKit()
    testImplementation project(':build-utils:test-utils')
    testImplementation project(':gradle-plugins:weblogic-wswar-plugin')
}

task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications.matching { it.name == 'pluginMaven' }.each {
        artifact sourceJar
    }
}
