/******************************************************************************************************************** **
 * Demonstrasjon av IntelliJ integrasjon i Gradle
 *
 *
 ******************************************************************************************************************** */

project.ext.set('MAVEN_REPO', project.properties.get('MAVEN_REPO', 'http://nexus.statkart.no:8090/nexus/content/groups/public/'))


apply from: rootProject.file('intellij/ideaProject.gradle')
apply from: rootProject.file('intellij/ideaWorkspace.gradle')

subprojects { p ->

    project.ext.set('isIdeaModule', project.subprojects.size() == 0)

    task('gen') { task ->
        description = "Genererer kildekode for alle sourceSets"
    }

    task('resources', dependsOn:'gen') { task ->
        description = "Genererer ressurser for alle sourceSets"
    }

    repositories {
        maven { name = 'public'; url = "${rootProject.MAVEN_REPO}" }
    }
}


evaluationDependsOnChildren()   //lar children legge til java plugin etter behov


subprojects { Project subProject ->

    apply from: rootProject.file('intellij/ideaModule.gradle'), to: p
    apply from: rootProject.file('intellij/ideaIntegration.gradle'), to: subProject

    def resourcesTask = subProject.tasks.resources
    subProject.convention.plugins.java?.sourceSets?.all {
        resourcesTask.dependsOn it.processResourcesTaskName
    }

}


task demo() {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'
}