/******************************************************************************************************************** **
 * Demonstrasjon av hvordan en kan plugge inn generert kode.
 *
 *  - ressurser blir generert til ./build/resources/<sourceSet> (std gradle path)
 *  - javakode blir generert til ./gen/special/java (custom path)
 *
 * Viser også hvordan man integrerer dette med IntelliJ.
 ******************************************************************************************************************** */

apply plugin: 'java'
apply plugin: 'idea'


sourceSets {
    main {
        //legger til ressurser som ikke blir generert via 'processResources'
        output.dir("${buildDir}/special/resources", builtBy: 'generateSpecialResources')

        //legger til class-filer som ikke blir generert via 'compileJava'
        output.dir("${buildDir}/classes/special", builtBy: 'compileSpecialJava')


        //markering av mappe her gjør at IntelliJ plukker opp denne og markerer denne som source
        // - konsekvensen av denne er at kildekoden blir kompilert av IntelliJ
        // - generelt så bør man unngå å legge inn dette slik at man unngår spesial-kompilering for intellij
        allSource.srcDir 'gen/special/java'
    }
}

//taks som genererer ressurser
task generateSpecialResources {
    doLast {
        def generated = project.file("${buildDir}/special/resources/myGeneratedResource.properties")
        generated.parentFile.mkdirs()
        generated.text = "message=Stay happy!"
    }
}


//taks som genererer classes
task compileSpecialJava(type:Compile) {
    source = "gen/special/java"
    destinationDir = project.file("${buildDir}/classes/special")
    classpath = files('na')
    dependsOn "generateSpecialSource"
}

task generateSpecialSource {
    doLast {
        def generated = project.file("gen/special/java/special.java")
        generated.parentFile.mkdirs()
        generated.text = '''class Special { public static String getMessage() throws Exception {
            java.util.Properties props = new java.util.Properties();
            props.load(Special.class.getResourceAsStream("myGeneratedResource.properties"));
            return props.get("message").toString();
        }}'''
    }

    project.tasks.clean.doLast {
        println "sletter generert kildekode ./gen"
        delete(file('gen'))
    }
}


/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task demo(dependsOn:'clean') {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    doLast {

        println 'Printer sourceSets definisjon...'
        forkGradle(['printSourceSets'])


        println 'Tester IntelliJ integrasjon...'
        forkGradle(['cleanIdea'])
        forkGradle(['ideaModule', 'assertIdeaModule'])

        println 'Tester egen-generering av ressurser...'
        forkGradle(['classes', 'assertResources'])

        println 'Tester egen-generering av classes...'
        forkGradle(['processResources', 'assertJavaSource'])

        println 'Tester classpath via kjøring av eksempelklient...'
        forkGradle(['build', 'assertClasspath'])

    }
}


task assertClasspath() << {
    def sourceSet = project.convention.plugins.java.sourceSets.main

    assert sourceSet.runtimeClasspath.contains(file("${buildDir}/special/resources"))
    assert sourceSet.runtimeClasspath.contains(file("${buildDir}/classes/special"))

    //tester ved å eksekvere generert javaklient
    project.javaexec {
        main = 'Messenger'
        classpath = sourceSet.runtimeClasspath
        standardOutput = System.out
        errorOutput = System.err

        println "Excecuting javaprogram with classpath \n  = ${classpath.files.join(';\n += ')};"
    }.rethrowFailure()
}

task assertIdeaModule() << {

    file("${project.name}.iml").text.with {
        assert it.contains("build/resources/special")    //forventer at sti for egenproduserte ressurser ligger på classpath
        assert it.contains("build/classes/special")    //forventer at sti for egenproduserte classes ligger på classpath
    }

}

task assertResources() << {
    def sourceSet = project.convention.plugins.java.sourceSets.main

    assert sourceSet.output.files.contains(file("${buildDir}/special/resources"))
    assert sourceSet.output.asFileTree.contains(file("${buildDir}/special/resources/myGeneratedResource.properties"))
}


task assertJavaSource() << {
    def sourceSet = project.convention.plugins.java.sourceSets.main

    assert sourceSet.allSource.srcDirs.contains(file('gen/special/java'))

    assert sourceSet.output.files.contains(file("${buildDir}/classes/special"))
    assert sourceSet.output.asFileTree.contains(file("${buildDir}/classes/special/Special.class"))
}


task printSourceSets() << {
    logger.info "SourceSets defined: "
    project.convention.plugins.java.sourceSets.each { s ->
        ['java', 'allJava', 'resources', 'filterResources', 'groovy', 'allGroovy', 'allSource'].each { id ->
            try {
                def prefix = "${s.name}.${id}"
                s."$id".srcDirs.each { println "$prefix <- ".padLeft(prefix.size() + 5, ' ') + project.relativePath(it); prefix = prefix.replaceAll(/./, ' ')  }
                println()
            } catch (MissingPropertyException mpe) {
                assert true //ok her
            }
        }
    }
}

/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(List tasks, Map props = [:]) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks
    sp.projectProperties = props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}

