assert project.gradle.gradleVersion >= '1.0-milestone-4'



buildscript {
    project.version = rootProject.getProperty('version')
    if (project.version == Project.DEFAULT_VERSION) project.version = '1.0-SNAPSHOT' //nb - dersom ikke default version er satt riktig så blir kjøring ifra demo-katalog feil..

    rootProject.setProperty('PUBLIC_REPO', 'http://skrivap92.statkart.no:8001/nexus/content/groups/public/')

    repositories {
        if (project.gradle.gradleVersion >= '1.0-milestone-7') {
            mavenRepo name: 'public', url: "${rootProject.PUBLIC_REPO}"
        } else {
            //for gradle versions previos to 1.0-milestone-7
            mavenRepo name: 'public', urls: "${rootProject.PUBLIC_REPO}"
        }
        mavenLocal()
    }
    dependencies {
        classpath "no.statkart.sktools.gradle:dbtools-plugin:${version}"
    }
}

allprojects {
    apply plugin: 'groovy'
    sourceCompatibility = '1.6'
    targetCompatibility = '1.6'

    repositories {
        mavenRepo name: 'public', url: "${rootProject.PUBLIC_REPO}"
        mavenLocal()
    }
}



//intellij
allprojects {
    apply plugin: 'idea'
}


project.idea.module {
    //legger til denne for innkobling av dokumentasjon i Intellij osv
    scopes.PROVIDED.plus += buildscript.configurations.classpath
}
