//settings per modul

apply plugin: 'idea'

idea.module {
  // Bruker ulik byggekatelog for Gradle og IDEA
  inheritOutputDirs = false
  outputDir = file('build/idea/main')
  testOutputDir = file('build/idea/test')

  downloadSources = false
  downloadJavadoc = false
}


//Legger til scopes for alle prosjekter som mangler dette (eks rene war moduler)
if (!project.plugins.hasPlugin('java')) {
    project.idea.module {
        scopes.get('PROVIDED', [plus: [], minus: []])
        scopes.get('COMPILE', [plus: [], minus: []])
        scopes.get('RUNTIME', [plus: [], minus: []])
    }
}


