group = 'no.statkart.sktools.gradle.plugins.dbtools-plugin.demos'

buildscript {
    if (rootProject.ext.has('sktools_versjon')) version = rootProject.ext.get('sktools_versjon')
    if (version == Project.DEFAULT_VERSION) { version = '1.5-SNAPSHOT'; logger.warn "No -Psktools_versjon= defined. Defaulting to \"${version}\""} //nb - dersom ikke default version er satt riktig så blir kjøring ifra demo-katalog feil..

    // Variables to grab from environment + defaults
    ['MAVEN_REPO'].each { val ->
        if (!rootProject.ext.has(val) && System.getenv(val) != null) {
            rootProject.ext.set(val, System.getenv(val))
        }
    }
    project.ext.set('MAVEN_REPO', project.ext.properties.get('MAVEN_REPO', 'https://nexus.statkart.no/repository/public/'))

    repositories {
        mavenLocal()
        maven { name = 'public'; url = MAVEN_REPO }
    }

    dependencies {
        classpath "no.statkart.sktools.gradle:dbtools-plugin:${version}"
    }
}


def clean = task('clean') {
    doFirst {
        logger.info "Cleaning project ${project.projectDir}"
    }
}

subprojects {
    task('clean') //noOp
}

allprojects {
    setVersion(rootProject.version)
    tasks.matching { 'runDemo' == it.name }.each {
        it.mustRunAfter clean
    }

    repositories {
        mavenLocal()
        maven { name = 'public'; url = "${rootProject.MAVEN_REPO}" }
    }

}

ext.port = gradle.startParameter.projectProperties.get('port') ?: randomHsqldbPort()
static int randomHsqldbPort() {
    int port = 9001 /*default port for hsqldb*/

    boolean onJenkins = System.getenv('EXECUTOR_NUMBER');
    if (onJenkins) {
        //velger en random port for parallel kjøring i jenkins
        //jenkins freestyle project og pipeline jobber setter env EXECUTOR_NUMBER
        def executorNumber = System.getenv('EXECUTOR_NUMBER') ?: 0 //unikhet muliggjør parallell testing
        port += executorNumber as int

        //for parallelkjøring i jenkins pipelineline settes ingen ytterligere variable, her improviseres det noe...
        int randomNum = new java.util.Random().nextInt(10)
        port += randomNum * 10
    }
    return port
}
