group = 'no.statkart.sktools.gradle.plugins.dbtools-plugin.demos'


assert GradleVersion.version('1.0').compareTo(GradleVersion.current()) <= 0 //lowest gradle version supported

buildscript {
    if (rootProject.ext.has('sktools_versjon')) version = rootProject.ext.get('sktools_versjon')
    if (version == Project.DEFAULT_VERSION) { version = '1.3-SNAPSHOT'; logger.warn "No -Psktools_versjon= defined. Defaulting to \"${version}\""} //nb - dersom ikke default version er satt riktig så blir kjøring ifra demo-katalog feil..

    // Variables to grab from environment + defaults
    ['MAVEN_REPO', 'JAVA_HOME'].each { val ->
        if (!rootProject.ext.has(val) && System.getenv(val) != null) {
            rootProject.ext.set(val, System.getenv(val))
        }
    }
    project.ext.set('MAVEN_REPO', project.ext.properties.get('MAVEN_REPO', 'http://nexus.statkart.no:8090/nexus/content/groups/public/'))

    repositories {
        //bruker kun lokale filer her da dette er et demo prosjekt...
        mavenLocal()
        maven { name = 'public'; url = MAVEN_REPO }
    }

    dependencies {
        classpath "no.statkart.sktools.gradle:dbtools-plugin:${version}"
    }
}

allprojects {
    setVersion(rootProject.version)

    repositories {
        mavenLocal()
        maven { name = 'public'; url = "${rootProject.MAVEN_REPO}" }
    }
}



//intellij
allprojects {
    apply plugin: 'java'    //trenger denne for at scopes.PROVIDED.plus skal fungere i idea plugin konfigurasjon
    apply plugin: 'idea'
}


project.idea.module {
    //legger til denne for innkobling av dokumentasjon i Intellij osv
    scopes.PROVIDED.plus += buildscript.configurations.classpath
}

tasks.clean.doFirst {
    logger.info "Cleaning project ${project.projectDir}"
}
