include ':simpledemo'
include ':multiple_toolsets'
include ':encoding'
include ':properties'
include ':patch'
include ':patch:multimodule'
include ':exhaustion'
include ':task_ordering'

rootProject.name = 'dbtools-plugin-demos'



//automatisk re-compile og install av siste versjon av plugin til lokal maven (spesifikt for demo-prosjekt)
gradle.projectsLoaded {
    final File projectDir = gradle.rootProject.file('../../..')

    gradle.allprojects { project ->
        tasks.withType(GradleBuild) { gradleBuild ->
            gradleBuild.startParameter.systemPropertiesArgs = [noMavenBootstrap: 'true']
            gradleBuild.startParameter.projectProperties = [sktools_versjon: "${project.version}"]
        }
    }

    //dersom ikke nested bygg..
    if (gradle.startParameter.systemPropertiesArgs['noMavenBootstrap']) {
        logger.info "Skipping maven install due to -DnoMavenBootstrap=${gradle.startParameter.systemPropertiesArgs['noMavenBootstrap']}"
    } else {
        logger.quiet 'Asserting project is up to date. Forking install on plugin-project. TIP: feature can be disabled with param -DnoMavenBootstrap=true'

        org.gradle.tooling.ProjectConnection connection = org.gradle.tooling.GradleConnector.newConnector().forProjectDirectory(projectDir).connect()
        try {
            connection.newBuild().forTasks('install').run()
        } finally {
            connection.close()
        }
    }
}
