/******************************************************************************************************************** **
 *
 * SKIF-209: Verifiserer oppdaterte lib filer for relaterte prosjekter
 *
 ******************************************************************************************************************** */

apply plugin: 'sktools-webstart-plugin'

signJars {

}

webstart {
    jnlp {
        jnlpFilename 'echo-client-signed.jnlp'
        jnlp {
            title 'Signed client'
            application.mainClass 'WebstartTester'
            resources {
                jars project(':echo-client')
                javaRuntime '1.6+', '64m', '64m'
            }
        }
    }
}

/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */
task runDemo(dependsOn:'clean') {
    description = 'Tester at lib filer blir oppdaterte'

    doLast {

        println "Tømmer cache katalog"
        project.rootProject.delete('.cache')

        cleanExtraResources.execute()

        println "Tester generering av client"
        forkGradle([
                'release',
                tasks['genWebstart'],
                tasks['assertEchoClientClasses'],
        ]) //'release' version without SNAPSHOT

        createExtraResources.execute()

        println "Tester generering av client"
        forkGradle([
                'release',
                tasks['genWebstart'],
                tasks['assertEchoClientClasses'],
                tasks['assertAddedEchoClientClasses'],
        ]) //'release' version without SNAPSHOT
    }
}

task createExtraResources() << {
    println "Oppretter genererte filer"
    File file = project.project(':echo-client').file('src/main/SKIF-209/addedResource.txt')
    file.parentFile.mkdirs()
    file.createNewFile()
}

task cleanExtraResources() << {
    println "Sletter genererte filer"
    project.project(':echo-client').delete('src/main/SKIF-209')
}



task assertEchoClientClasses() << {
    ["build/signed/lib"].each {
        def archive = project.files(it).asFileTree.filter({it.name.contains("echo-client")}).singleFile
        assert archive.exists() //forventer at jar fil er opprettet

        assert !project.zipTree(archive).matching {include '**/*.class'}.files.isEmpty()
    }
}

task assertAddedEchoClientClasses() << {
    ["build/signed/lib"].each {
        def archive = project.files(it).asFileTree.filter({it.name.contains("echo-client")}).singleFile
        assert archive.exists() //forventer at jar fil er opprettet

        assert project.zipTree(archive).matching {include 'addedResource.txt'}.files.size() == 1
    }
}


/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(List tasks, Map props = [:]) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks.collect { it instanceof Task ? it.path : it.toString() }
    sp.projectProperties << props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}
