group = 'no.statkart.sktools.gradle.plugins.ideaextensions-plugin.demos'


apply from:'simple-demo.gradle'


assert gradle.gradleVersion == '1.0' || gradle.gradleVersion >= '1.0-milestone-7'

//innkobling av plugin jar filer for gradle byggesystem
buildscript {
    rootProject.version = '1.1'

    // Variables to grab from environment + defaults
    ['WEBLOGIC_HOME', 'COMPUTERNAME', 'PUBLIC_REPO', 'JAVA_HOME'].each { val ->
        if (!rootProject.hasProperty(val) && System.getenv(val) != null) {
            if (gradle.gradleVersion >= '1.0-milestone-9') {
                rootProject.ext.set(val, System.getenv(val))
            } else {
                rootProject.setProperty(val, System.getenv(val))
            }
        }
    }
    if (gradle.gradleVersion >= '1.0-milestone-9') {
        project.ext.set('PUBLIC_REPO', project.properties.get('PUBLIC_REPO', 'http://skrivap92.statkart.no:8001/nexus/content/groups/public/'))
    } else {
        project.setProperty('PUBLIC_REPO', project.properties.get('PUBLIC_REPO', 'http://skrivap92.statkart.no:8001/nexus/content/groups/public/'))
    }

    repositories {
        //bruker kun lokale filer her da dette er et demo prosjekt...
        mavenLocal()

//        mavenRepo name: 'public', url: PUBLIC_REPO

    }

    dependencies {
        classpath "no.statkart.sktools.gradle:ideaextensions-plugin:${version}"
    }

}
