<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="http://statkart.no/sktools/wsapi/v1/service/store" xmlns:ns1="http://statkart.no/sktools/wsapi/v1/domain/basistyper" xmlns:tns="http://statkart.no/sktools/wsapi/v1/service/store" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:import namespace="http://statkart.no/sktools/wsapi/v1/domain/basistyper" schemaLocation="StoreServiceWS_schema3.xsd"/>

  <xs:element name="getObject" type="tns:getObject"/>

  <xs:element name="getObjectResponse" type="tns:getObjectResponse"/>

  <xs:element name="getObjects" type="tns:getObjects"/>

  <xs:element name="getObjectsIgnoreMissing" type="tns:getObjectsIgnoreMissing"/>

  <xs:element name="getObjectsIgnoreMissingResponse" type="tns:getObjectsIgnoreMissingResponse"/>

  <xs:element name="getObjectsResponse" type="tns:getObjectsResponse"/>

  <xs:element name="getVersions" type="tns:getVersions"/>

  <xs:element name="getVersionsForList" type="tns:getVersionsForList"/>

  <xs:element name="getVersionsForListResponse" type="tns:getVersionsForListResponse"/>

  <xs:element name="getVersionsResponse" type="tns:getVersionsResponse"/>

  <xs:complexType name="getObject">
    <xs:sequence>
      <xs:element name="id" type="ns1:SkToolsBubbleObjectId" minOccurs="0"/>
      <xs:element name="SkToolsContext" type="ns1:SkToolsContext" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getObjectResponse">
    <xs:sequence>
      <xs:element name="return" type="ns1:SkToolsBubbleObject" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getObjectsIgnoreMissing">
    <xs:sequence>
      <xs:element name="ids" type="ns1:SkToolsBubbleObjectIdList" minOccurs="0"/>
      <xs:element name="SkToolsContext" type="ns1:SkToolsContext" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getObjectsIgnoreMissingResponse">
    <xs:sequence>
      <xs:element name="return" type="ns1:SkToolsBubbleObjectList" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getVersionsForList">
    <xs:sequence>
      <xs:element name="ids" type="ns1:SkToolsBubbleObjectIdList" minOccurs="0"/>
      <xs:element name="start" type="ns1:Timestamp" minOccurs="0"/>
      <xs:element name="end" type="ns1:Timestamp" minOccurs="0"/>
      <xs:element name="SkToolsContext" type="ns1:SkToolsContext" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getVersionsForListResponse">
    <xs:sequence>
      <xs:element name="return" type="ns1:SkToolsBubbleObjectIdToSnapshotBubbleIdsMap" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getVersions">
    <xs:sequence>
      <xs:element name="id" type="ns1:SkToolsBubbleObjectId" minOccurs="0"/>
      <xs:element name="start" type="ns1:Timestamp" minOccurs="0"/>
      <xs:element name="end" type="ns1:Timestamp" minOccurs="0"/>
      <xs:element name="SkToolsContext" type="ns1:SkToolsContext" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getVersionsResponse">
    <xs:sequence>
      <xs:element name="return" type="ns1:SkToolsBubbleObjectIdList" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getObjects">
    <xs:sequence>
      <xs:element name="ids" type="ns1:SkToolsBubbleObjectIdList" minOccurs="0"/>
      <xs:element name="SkToolsContext" type="ns1:SkToolsContext" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getObjectsResponse">
    <xs:sequence>
      <xs:element name="return" type="ns1:SkToolsBubbleObjectList" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

