apply plugin: 'sktools-filter-resources-plugin'
apply plugin: 'java'



filterResources {
    properties(
            testValue: 'myValue',
            'otherProperty': 'value',
    )
}



task runDemo() {
    dependsOn 'testFilterResources'
}


task('testFilterResources', dependsOn: tasks.filterResources) {
    doFirst {
        assert file('build/filteredResources/main/someFile.txt').exists()
        assert file('build/filteredResources/main/someFile.txt').text.contains("version=@version@")
        assert file('build/filteredResources/main/someFile.txt').text.contains("testValue=myValue")
    }
}

