apply plugin: 'java'
apply plugin: 'sktools-weblogic-wswar-plugin'

description = "Web modul med webservice implementasjon"

dependencies {
    weblogicCompile project(path: project.path, configuration:'runtime')

    weblogicProvided libraries.weblogic
    weblogicProvided libraries['tools.jar']
}



//innkobling av plugin jar filer for gradle byggesystem
buildscript {

    repositories {
        //bruker kun lokale filer her da dette er et demo prosjekt...
        mavenLocal()
        maven { name = 'public'; url = MAVEN_REPO }
    }

    dependencies {
        classpath "no.statkart.sktools.gradle:weblogic-wswar-plugin:${version}"
    }
}
