/******************************************************************************************************************** **
 * Demonstrerer standard bruk av plugin
 *
 * Det demonstreres også eksempel implementasjon av 'gen' target
 ******************************************************************************************************************** */

apply plugin: 'java'
apply plugin: 'sktools-weblogic-wsclient-plugin'


dependencies {
    weblogicProvided libraries.weblogic
    weblogicProvided libraries.'tools.jar'  //tools jar må være med for weblogic 10.3.5 eller nyere?
}


weblogicWsClient {
    client1 {
        baseWar { project(path:':war1', configuration:'weblogic') }
    }
}


task('gen').description = "Genererte ressurser"


//integrasjon med plugin
afterEvaluate {
    if (project.plugins.hasPlugin('sktools-weblogic-wsclient-plugin')) {
        project.tasks.withType(no.statkart.sktools.gradle.plugins.weblogic.wsclient.WeblogicWsClientCompileTask.class) {
            project.tasks.gen.dependsOn it
        }
    }
}


/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task runDemo() << {

    //SKTOOLS-56: viser tempdir konfigurasjon
    println "Java tempdir for gradle prosjekt: ${System.getProperty('java.io.tmpdir')}"
    println "genWeblogicWsClient.temporaryDir: ${genWeblogicWsClient.temporaryDir}"

    println 'Tester kodegenerering...'
    forkGradle(['genWeblogicWsClient', 'assertGenWeblogicWsClient'])

    println 'Tester bygging av weblogic artifakt...'
    forkGradle(['clean', 'build', 'assertBuild'])

    println 'Tester bygging av main artifakt...'
    forkGradle(['clean', 'assemble', 'assertBuild'])

    println 'Tester generering via gen-integrasjon...'
    forkGradle(['clean', 'gen', 'assertGeneratedWeblogicResources', 'assertGeneratedWeblogicClasses'])

}


task assertGeneratedWeblogicResources() << {
    assert file('gen/main/wsclient/META-INF/wsdls/TestServiceWS_v1.wsdl').exists()
}

task assertGeneratedWeblogicClasses() << {
    assert file('gen/main/wsclient/no/statkart/test/service1/TestServiceWSV1.java').exists()
}


task assertGenWeblogicWsClient() {
    dependsOn assertGeneratedWeblogicResources
    dependsOn assertGeneratedWeblogicClasses
}


task assertBuild() {
    dependsOn assertGenWeblogicWsClient
    doLast {
        assert file("build/libs/${project.name}-${project.version}.jar").exists()
    }
}




/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(List tasks, Map props = [:]) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks.collect {"${project.path}:${it}".toString()}
    sp.projectProperties << props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}
