-- PATCH DATA DB.VERSION="0.2" PATCH.NO="1" "Create test table2"

CREATE TABLE TEST_TABLE2 (
   ID INTEGER NOT NULL,
   NAVN VARCHAR(32) NOT NULL,
   PRIMARY KEY (ID)
);


-- PATCH DATA DB.VERSION="0.2" PATCH.NO="3" "Inserting Chuck Norris2"
INSERT INTO TEST_TABLE2 (ID, NAVN) VALUES (1, 'CHUCK NORRIS');

-- PATCH INDEX DB.VERSION="0.2" PATCH.NO="4" "Indexing names and id2"
CREATE INDEX TEST_TABLE2_IDX_01 ON TEST_TABLE2(NAVN, ID);
