include ':projectA'
include ':projectB'

// release/SNAPSHOT versioning
gradle.projectsLoaded { Gradle g ->
    if (!startParameter.taskNames.contains('release')) {
        g.rootProject.allprojects {
            it.afterEvaluate {
                if (it.version != DEFAULT_VERSION) {
                    it.version.subversjon += "-SNAPSHOT"
                }
            }
        }
    } else {
        startParameter.taskNames.remove('release')
        println 'Configuring build for release!'

        //optional assert at version er anngitt
        assert !g.rootProject.getVersion().startsWith('1.dev')
    }
}
