/******************************************************************************************************************** **
 * Demonstrasjon av hvordan en kan plugge inn generert kode på via sourceSet.
 *
 *  - ressurser blir generert til ./build/resources/<sourceSet> (std gradle path)
 *  - javakode blir generert til ./gen/special/java (custom path)
 *
 * Viser også hvordan man integrerer dette med IntelliJ
 *
 * NB: Merk at generert kode kun havner på runtime classpath og kan således ikke refereres til ifra annen kompilert kode
 ******************************************************************************************************************** */

apply plugin: 'java'
apply plugin: 'idea'


sourceSets {

    special {

        java.srcDirs = []
//        resources.srcDirs = ["${buildDir}/resources/special"]   //std folder is build/resources/special

        //markering av mappe for generert kildekode her
        // - IntelliJ bryr seg kun om 'main' sourceSet
        allSource.srcDir 'gen/special/java'
    }

    main {
        //legger til ressurser som ikke blir generert via 'processResources'
        output.dir(special.output.resourcesDir, builtBy: special.processResourcesTaskName)

        //legger til class-filer som ikke blir generert via 'compileJava'
        output.dir(special.output.classesDir, builtBy: special.compileJavaTaskName)

    }
}

//taks som genererer ressurser
task generateSpecialResources { Task it ->
    doLast {
        def generated = project.file("${buildDir}/resources/special/myGeneratedResource.properties")
        generated.parentFile.mkdirs()
        generated.text = "message=Stay happy!"
    }

    project.tasks.processSpecialResources.dependsOn(it)
}


//taks som genererer kildekode
task generateSpecialSource { Task it ->
    doLast {
        def generated = project.file("gen/special/java/special.java")
        generated.parentFile.mkdirs()
        generated.text = '''class Special { public static String getMessage() throws Exception {
            java.util.Properties props = new java.util.Properties();
            props.load(Special.class.getResourceAsStream("myGeneratedResource.properties"));
            return props.get("message").toString();
        }}'''
    }

    project.tasks.clean.doLast {
        println "sletter generert kildekode ./gen"
        project.delete('gen')
    }

    project.tasks.compileSpecialJava.dependsOn(it).source 'gen/special/java'

}


/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task demo(dependsOn:'clean') {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    doLast {

        println 'Printer sourceSets definisjon...'
        forkGradle(['printSourceSets'])

        println 'Tester IntelliJ integrasjon...'
        forkGradle(['cleanIdea'])
        forkGradle(['ideaModule', 'assertIdeaModule'])

        println 'Tester egen-generering av ressurser...'
        forkGradle(['classes', 'assertResources'])

        println 'Tester egen-generering av classes...'
        forkGradle(['processResources', 'assertJavaSource'])

        println 'Tester classpath via kjøring av eksempelklient...'
        forkGradle(['build', 'assertClasspath'])

    }
}


task assertClasspath() << {
    def sourceSet = project.convention.plugins.java.sourceSets.main
    def specialSourceSet = project.convention.plugins.java.sourceSets.special

    assert sourceSet.runtimeClasspath.contains(specialSourceSet.output.resourcesDir)
    assert sourceSet.runtimeClasspath.contains(specialSourceSet.output.classesDir)


    //tester ved å eksekvere generert javaklient
    project.javaexec {
        main = 'Messenger'
        classpath = sourceSet.runtimeClasspath
        standardOutput = System.out
        errorOutput = System.err

        println "Excecuting javaprogram with classpath \n  = ${classpath.files.join(';\n += ')};"
    }.rethrowFailure()
}

task assertIdeaModule() << {
    def specialSourceSet = project.convention.plugins.java.sourceSets.special

    file("${project.name}.iml").text.with {
        def specialClassesClassPath = project.relativePath(specialSourceSet.output.classesDir).replaceAll('\\\\', '/')
        assert it.contains("/${specialClassesClassPath}")    //forventer at sti for egenproduserte ressurser ligger på classpath

        def specialResourcesClassPath = project.relativePath(specialSourceSet.output.resourcesDir).replaceAll('\\\\', '/')
        assert it.contains("/${specialResourcesClassPath}")    //forventer at sti for egenproduserte classes ligger på classpath

        assert !it.contains("gen/special/java") //forventer at generert source IKKE er markert som sourcekatalog

    }

}

task assertResources() << {
    def sourceSet = project.convention.plugins.java.sourceSets.special

    assert sourceSet.output.files.contains(file("${buildDir}/resources/special"))
    assert sourceSet.output.asFileTree.contains(file("${buildDir}/resources/special/myGeneratedResource.properties"))
}


task assertJavaSource() << {
    def sourceSet = project.convention.plugins.java.sourceSets.special

    assert sourceSet.allSource.srcDirs.contains(file('gen/special/java'))

    assert sourceSet.output.files.contains(file("${buildDir}/classes/special"))
    assert sourceSet.output.asFileTree.contains(file("${buildDir}/classes/special/Special.class"))
}


task printSourceSets() << {
    logger.info "SourceSets defined: "
    project.convention.plugins.java.sourceSets.each { s ->
        ['java', 'allJava', 'resources', 'filterResources', 'groovy', 'allGroovy', 'allSource'].each { id ->
            try {
                def prefix = "${s.name}.${id}"
                s."$id".srcDirs.each { println "$prefix <- ".padLeft(prefix.size() + 5, ' ') + project.relativePath(it); prefix = prefix.replaceAll(/./, ' ')  }
                println()
            } catch (MissingPropertyException mpe) {
                assert true //ok her
            }
        }
    }
}

/******************************************************************************************************************** **
 * Helper method for forking gradle builds programmatically. Using gradle Tooling API
 * (Only relevant for testing)
 ******************************************************************************************************************** */
void forkGradle(List<String> tasks, Map props = [:]) {
    org.gradle.tooling.ProjectConnection connection = org.gradle.tooling.GradleConnector.newConnector().forProjectDirectory(project.projectDir).connect();
    try {
        org.gradle.tooling.BuildLauncher build = connection.newBuild()
                .forTasks(tasks.collect { "${project.path}:${it}".toString() } as String[])
                .withArguments(props.collect { "-P${it.key}=${it.value}" } << ['-DnoMavenBootstrap=true'] as String[])
                .run();
    } finally {
        connection.close();
    }
}

