apply plugin: 'sktools-filterproperties-plugin'
apply plugin: 'java'





task runDemo {
    dependsOn 'testFilterResources'
    dependsOn 'testClean'
}


task testFilterResources(dependsOn:'filterResources') << {
    assert file('gen/main/resources/someFile.txt').exists()
    file('gen/main/resources/someFile.txt').text.contains("version=${project.version}")
    file('gen/main/resources/someFile.txt').text.contains("testValue=@testValue@")
}

task testClean(dependsOn:['testFilterResources', 'clean']) << {
    println 'todo'
//    assert !file('gen/src/main/resources').exists()
}
