apply plugin: 'sktools-dbtools-plugin'


 // Kort intro til HSQLDB - http://hsqldb.org
 /**
  * Hsqldb er en liten lettvekts database som kan kjøres in memory eller som stand alone.
  * En har mulighet til å persistere informasjon til disk.
  *
  * Dersom en kjører in memory kan en aksessere databasen innenfor samme javavm.
  *
  * Ved aksessering ifra flere prosesser bør en kjøre basen i "stand alone" mode. En har her fortsatt mulighet til
  * å kjøre denne som in memory. Databasen kjører da i en frittstående prosess.
  *
  * HSQLDB 2.4.x krever JRE 8
  */
configurations {
    hsqldb
}

dependencies {
    hsqldb 'org.hsqldb:hsqldb:2.3.3'
}


int executorNumber = System.getenv('EXECUTOR_NUMBER') ?: 0 //unikhet muliggjør parallell testing
ext.port = 9001 + executorNumber

//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {

    useDrivers project.configurations.hsqldb

    toolset( name:'sa', type:'hsqldb', prefix:'') {
        url = "jdbc:hsqldb:hsql://localhost:${port}/testPatching"
        credentials.username = 'SA'
        credentials.password = ''

        patch {
            name = 'Module1'
            patchTask('_1.9.1', sqlFile: 'src/sql/system_1.9.1/patch/patchModule1_1.9.1.sql')
            patchTask('_1.10', sqlFile: 'src/sql/system_1.10/patch/patchModule1_1.10.sql')
        }

        patch {
            name = 'Module2'
            patchTask('_1.9.1', sqlFile: 'src/sql/system_1.9.1/patch/patchModule2_1.9.1.sql')
            patchTask('_1.10', sqlFile: 'src/sql/system_1.10/patch/patchModule2_1.10.sql')
        }

        sqlTask('assertMinPatchVersion', sqlString: '-- verifies min patch version').doLast {
            patch['Module1'].assertMinVersion '1.9.1' //minste versjon støttet i dette bygget
            patch['Module2'].assertMinVersion '1.9.1' //minste versjon støttet i dette bygget
        }

        taskSequence('createViews', dependsOn: [tasks['assertMinPatchVersion']]) {
            dependsOn sqlTask('createTestTableView_1.9.1', sqlFile: 'src/sql/system_1.9.1/view/createTestTableView_1.9.1.sql') {
                onlyIf { patch['Module1'].currentVersion == '1.9.1' }
                onlyIf { patch['Module2'].currentVersion == '1.9.1' }
            }
            dependsOn sqlTask('createTestTableView_1.10', sqlFile: 'src/sql/system_1.10/view/createTestTableView_1.10.sql') {
                onlyIf { patch['Module1'].currentVersion == '1.10' }
                onlyIf { patch['Module2'].currentVersion == '1.10' }
            }
        }

        properties = [:]

    }

    taskSequence('dbPatch', description: 'Patcher databasen opp til siste versjon') {

        dependsOn dbToolSets['sa'].patch['Module1'].tasks['_1.9.1']
        dependsOn dbToolSets['sa'].patch['Module2'].tasks['_1.9.1']
        dependsOn dbToolSets['sa'].patch['Module1'].tasks['_1.10']
        dependsOn dbToolSets['sa'].patch['Module2'].tasks['_1.10']
    }

}





/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task runDemo() {


    Assert.that('clean').describedAs('startUpEmptyHsqlInstances').leadsTo(project).withState {
        tearDownDatabase()
        startUpDatabase()
        assertNoPatchTable()
    }

    //kjører inn en patch
    Assert.that('PatchModule1_1.9.1').describedAs('patchTil1_9_1').prep {
        assertNoTable('TEST_TABLE1')
        assertNoTable('TEST_TABLE2')

    }.leadsTo(project).withState {
        assertTableRowcountID1('TEST_TABLE1', 0)
        assertNoTable('TEST_TABLE2')
    }


    //kjører inn alle patcher til siste versjon (2.0)
    Assert.that('dbPatch').describedAs('patchAll').prep {
        assertTableRowcountID1('TEST_TABLE1', 0)
        assertNoTable('TEST_TABLE2')

    }.leadsTo(project).withState {
        assertTableRowcountID1('TEST_TABLE1', 1)
        assertTableRowcountID1('TEST_TABLE2', 1)
    }


    //kjører igjen inn alle patcher til siste versjon (2.0)
    Assert.that('dbPatch').describedAs('patchAllMultipleTimes').prep {
        assertTableRowcountID1('TEST_TABLE1', 1)
        assertTableRowcountID1('TEST_TABLE2', 1)

    }.leadsTo(project).withState {
        assertTableRowcountID1('TEST_TABLE1', 1)
        assertTableRowcountID1('TEST_TABLE2', 1)
    }



    Assert.that('clean').describedAs('teardown').leadsTo(project).withState {
        logger.quiet 'Shutting down running HSQLDB instance...'
        tearDownDatabase()
    }

    doLast {
        logger.quiet "done."
    }
}







class Assert {
    def taskName
    List<String> taskNames
    Project project
    List<Closure> prep = []

    static def previousTask = null

    static Assert that(String... taskNames) {
        Assert instance = new Assert(); instance.taskNames = taskNames; return instance
    }

    Assert describedAs(String taskName) {
        this.taskName = taskName; this
    }

    Assert prep(Closure prepProjectBeforeAsserts) {
        prep << prepProjectBeforeAsserts; this
    }

    Assert leadsTo(Project project = project) {
        this.project = project; this
    }

    Assert withState(Closure check) {
        def task = project.task(taskName, type: GradleBuild) {
            dir = project.projectDir
            tasks = taskNames
            startParameter.systemPropertiesArgs = [noMavenBootstrap: 'true']
            startParameter.projectProperties = [sktools_versjon:"${project.version}"]
            prep.reverseEach { Closure beforeAsserts -> doFirst { beforeAsserts.setDelegate(this); beforeAsserts.run()}}
            doLast { check.setDelegate(this); check.run() }
            doFirst {
                toConsole('--------------------------------------------------------------------------------');
                toConsole("Testing use case: ${taskName} tasks=${taskNames}\n\n\n");
            }
            doLast {
                toConsole "\n  ...end of test case: ${taskName}"
                toConsole('--------------------------------------------------------------------------------\n\n');
            }
            outputs.upToDateWhen { false } //always run this...
        }
        project.tasks['runDemo'].dependsOn task

        if (previousTask) task.dependsOn previousTask //ordered execution of asserts...
        previousTask = task
        this
    }

    //convenience methods and asserts....



    /**
     * Verifies that table with {@code tablename} does not exists
     */
    void assertNoTable(String tablename) {
        try {
            sqlSA().eachRow("select count(*) from " + tablename) { }
            assert false //forventer at tabell ikke finnes
        } catch (java.sql.SQLException e) {
            assert true
        }
    }

    /**
     * Verifies rowcount for table with {@code tablename} where {@code ID=1}
     */
    void assertTableRowcountID1(String tablename, int count) {
        sqlSA().eachRow("select count(*) from " + tablename + " where ID=1") {
            assert it[0] == count
        }
    }


    // common methods ->

    groovy.sql.Sql sqlSA() {
        def convention = project.convention.plugins['db'].dbToolSets['sa']
        groovy.sql.Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
    }

    /**
     * Verifies that {@code PATCHINFO} does not exists
     */
    void assertNoPatchTable() {
        try {
            sqlSA().eachRow("select count(*) from PATCHINFO") { }
            assert false //forventer at tabell ikke finnes
        } catch (java.sql.SQLException e) {
            assert true
        }
    }

    void listPatchInfoTableForComponent(def sql, def component = null) {
        try {
            def sqlString = "select * from PATCHINFO"
            if (component != null)  sqlString += " where component='${component}'"
            toConsole "Utskrift av PATCHINFO component=${component}:\n\n"

            if (sql.rows(sqlString).isEmpty()) {
                toConsole "\t<empty>"
            } else {
                sql.eachRow(sqlString) {
                    toConsole it
                }
            }

        } catch (java.sql.SQLException e) {
            assert false
        }
    }


    void tearDownDatabase() {
        toConsole "Tar ned database ${project.convention.plugins.db.dbToolSets['sa'].url}"
        try {
            sqlSA().execute('SHUTDOWN;')
        } catch (java.sql.SQLException e) {
            assert true //får noen ganger EOFException her..
        }
    }

    void startUpDatabase() { //Forker database i subprosess
        def alias = project.convention.plugins.db.dbToolSets['sa'].url.split('/')[3]
        //forking the groovy way until https://github.com/gradle/gradle/issues/1367
        def cmd = ['java', '-cp', project.configurations.hsqldb.asPath, 'org.hsqldb.Server',
                '-database.0', 'mem:test', '-port', project.port, '-dbname.0', alias //definisjon for database med navn "test"
        ]

        toConsole "Starter opp database via kommando: \n\t${cmd.join(' ')}"
        def process = cmd.execute()

        process.in.close()
        process.out.close()
        process.err.close()

//        System.console().readLine('pause for debug..')
    }

    private void toConsole(def message) {
        project.logger.quiet(message)
    }


}
