plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

java {
    withSourcesJar()
}

publishing {
    publications {
        pluginMaven(MavenPublication) {
            artifactId = 'xjc-plugin'
        }
    }
}

gradlePlugin {
    plugins {
        xjc {
            id = 'sktools.xjc'
            implementationClass = 'no.statkart.sktools.gradle.plugins.xjc.XjcPlugin'
        }
    }
}

def pluginPropertiesDir = "$buildDir/plugin-properties"
def pluginProperties = [
        default_xjc_implementation : 'org.glassfish.jaxb:jaxb-xjc:3.0.2',
        default_jaxb_ri_implementation : 'org.glassfish.jaxb:jaxb-runtime:3.0.2',
] as Properties

dependencies {
    testImplementation project(':build-utils:test-utils')
}

pluginUnderTestMetadata.pluginClasspath.from sourceSets.main.output


tasks.register('createPluginProperties') {
    outputs.dir pluginPropertiesDir
    inputs.properties pluginProperties
    doLast {
        def file = layout.projectDirectory.file("$pluginPropertiesDir/no/statkart/sktools/xjc-gradle-plugin.properties").asFile
        file.parentFile.mkdirs()
        file.withWriter {
            pluginProperties.store(it, (String) null)
        }
        logger.info "Created plugin info file: ${file.getAbsolutePath()}"
    }
}
sourceSets.main.resources.srcDir createPluginProperties
