apply plugin: 'maven'
apply plugin: 'groovy'

group = 'no.statkart.sktools.gradle'



dependencies {

    //gradle api til byggesystemm blir benyttet som std
    compile gradleApi()
    runtime 'commons-lang:commons-lang:2.6@jar'

    compile project(':build-utils:xjc-plugins')

    //test
    testCompile project(':build-utils:test-utils')
}

task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
    onlyIf { gradle.taskGraph.hasTask(install) || gradle.taskGraph.hasTask(uploadArchives) } //only when published..
}


artifacts {
    archives sourcesJar
}

