plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

gradlePlugin {
    plugins {
        xjc {
            id = 'sktools.xjc'
            implementationClass = 'no.statkart.sktools.gradle.plugins.xjc.XjcPlugin'
        }
    }
}

def pluginPropertiesDir = "$buildDir/plugin-properties"

sourceSets {
    main {
        output.dir(pluginPropertiesDir, builtBy: 'createPluginProperties')
    }
}

def pluginProperties = [
        sktools_xjc_extensions : "no.statkart.sktools:xjc-plugins:${version}" as String,
        default_xjc_implementation : libraries.jaxb_xjc as String,
        default_jaxb_ri_implementation : libraries.jaxb_rt as String,
] as Properties

dependencies {
    testImplementation project(':build-utils:test-utils')
}

pluginUnderTestMetadata.doFirst {
    if (org.gradle.util.GradleVersion.current() >= org.gradle.util.GradleVersion.version('4.10')) {
        pluginUnderTestMetadata.pluginClasspath.from project(':build-utils:xjc-plugins').sourceSets.main.runtimeClasspath
    } else {
        pluginUnderTestMetadata.pluginClasspath += project(':build-utils:xjc-plugins').sourceSets.main.runtimeClasspath
    }
}

task createPluginProperties() {
    outputs.dir pluginPropertiesDir
    inputs.properties pluginProperties
    doLast {
        def file = project.file("$pluginPropertiesDir/no/statkart/sktools/xjc-gradle-plugin.properties")
        file.parentFile.mkdirs()
        org.gradle.util.GUtil.saveProperties(pluginProperties, file)
        logger.info "Created plugin info file: ${file.getAbsolutePath()}"
    }
}
tasks.processResources.dependsOn createPluginProperties


task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications.all {
        if (it.name == 'pluginMaven') artifact sourceJar
    }
}
