/******************************************************************************************************************** **
 *
 * Demonstrasjon av setting av encoding for kildefiler.
 *
 ******************************************************************************************************************** */

apply plugin: 'sktools-dbtools-plugin'

String norskeTegn = "\u00c6\u00e6\u00d8\u00f8\u00c5\u00e5"// 'ÆæØøÅå' written with utf8 escaped values


configureDatabasePlugin {

    useDrivers 'org.hsqldb:hsqldb:2.3.3'

    toolset(name: 'UTF8', type: 'hsqldb', prefix: '') {

        sqlTask('insertData', sqlFile: 'sql/insertData.sql', encoding: 'UTF-8')
        sqlTask('createTable', sqlString: '''
            CREATE TABLE TABLE1 (
                ID INTEGER NOT NULL,
                TEXT VARCHAR(32) NOT NULL,
                PRIMARY KEY (ID)
            )
        ''')

        properties = [CUSTOM: norskeTegn]

        url = "jdbc:hsqldb:mem:testbase"

        credentials.username = 'SA'
        credentials.password = ''
    }

}

/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task runDemo() {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    Assert.that('createTable', 'insertData').describedAs('spesialtegnPersisteresRiktig').leadsTo(project).withState {

        logger.quiet('Verifiserer data med riktig tegnsett i databasen...')
        def convention = project.convention.plugins.db.dbToolSets['UTF8']
        def sql = groovy.sql.Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
        sql.eachRow("select ID, TEXT from TABLE1") {
            logger.quiet("..asserting row {}, text={}", it[0], it[1])
//            logger.quiet it[1].bytes.collect {"$it"}
            assert norskeTegn.equals(it[1])  // comparing strings
        }
    }

}


class Assert {
    def taskName
    List<String> taskNames
    Project project
    List<Closure> prep = []

    static def previousTask = null

    static Assert that(String... taskNames) {
        Assert instance = new Assert(); instance.taskNames = taskNames; return instance
    }

    Assert describedAs(String taskName) {
        this.taskName = taskName; this
    }

    Assert prep(Closure prepProjectBeforeAsserts) {
        prep << prepProjectBeforeAsserts; this
    }

    Assert leadsTo(Project project = project) {
        this.project = project; this
    }

    Assert withState(Closure check) {
        def task = project.task(taskName, type: GradleBuild) {
            dir = project.projectDir
            tasks = taskNames
            startParameter.projectProperties = [sktools_versjon: "${project.version}"]
            startParameter.projectProperties << project.gradle.startParameter.projectProperties
            prep.reverseEach { Closure beforeAsserts -> doFirst { beforeAsserts.setDelegate(this); beforeAsserts.run()}}
            doLast { check.setDelegate(this); check.run() }
            doFirst {
                toConsole('--------------------------------------------------------------------------------');
                toConsole("Testing use case: ${taskName} tasks=${taskNames}\n\n\n");
            }
            doLast {
                toConsole "\n  ...end of test case: ${taskName}"
                toConsole('--------------------------------------------------------------------------------\n\n');
            }
            outputs.upToDateWhen { false } //always run this...
        }
        project.tasks['runDemo'].dependsOn task

        if (previousTask) task.dependsOn previousTask //ordered execution of asserts...
        previousTask = task
        this
    }

    private void toConsole(def message) {
        project.logger.quiet(message)
    }

    //convenience methods and asserts....

}
