apply plugin: 'groovy'

description = "Intern modul for felles test-logikk."

sourceSets {
    sample // ressurser for sample.jar til bruk i tester
}

dependencies {
    implementation libraries.testng
    implementation libraries.assertj

    implementation gradleTestKit()
    implementation localGroovy()
}


tasks.register('createSampleJar', Jar) {
    archiveFileName = 'sample.jar.bin'
    from(project.sourceSets.sample.output)
    manifest.attributes([
        'Specification-Title'   : "Sample 1",
        'Implementation-Version': "0.1",
    ])
}
sourceSets.main.output.dir createSampleJar

tasks.register('createSample2Jar', Jar) {
    archiveFileName = 'sample2.jar.bin'
    from(project.sourceSets.sample.output)
    manifest.attributes([
        'Specification-Title': "Sample 2",
    ])
}
sourceSets.main.output.dir createSample2Jar
