/******************************************************************************************************************** **
 * Demonstrerer hvordan man kan implementere bruk av repositories.
 *
 * Generelt:
 * Under utvikling så ønsker man noen ganger å kunne utvikle på tvers av prosjekter. Dette uten påvirkning ifra av andre
 * samt at man ønsker å forhindre at man uforutsett påvirker andre.
 *
 * Implementasjon:
 * Vanligvis går man mot felles repo der felles versjoner av ressurser ligger.
 * Når man ønsker å gå mot spesielle versjoner så benyttes lokalt maven repo. Dette styres via env variabler.
 *
 * PS: Ved oppdateringer i gradle cachet, eller endringer i dependenices så må IntelliJ prosjekt-filer oppdateres.
 ******************************************************************************************************************** */





buildscript {
    Map env = System.getenv() + gradle.startParameter.systemPropertiesArgs

    ['MAVEN_REPO', 'COMPUTERNAME'].each { name ->
        if (env[name] != null) {
            project.ext.set(name, env[name])
        } else {
            throw new GradleException("Mandatory env variable ${name} not set!")
        }
    }

    project.ext.set('MAVEN_LOCAL_FOR_BUILDSYSTEM', (Boolean.parseBoolean(env['MAVEN_LOCAL']) || Boolean.parseBoolean(env['MAVEN_LOCAL_FOR_BUILDSYSTEM'])) ? true : null)
    project.ext.set('MAVEN_LOCAL_FOR_PROJECT', (Boolean.parseBoolean(env['MAVEN_LOCAL']) || Boolean.parseBoolean(env['MAVEN_LOCAL_FOR_PROJECT'])) ? true : null)

    repositories {
        if (MAVEN_LOCAL_FOR_BUILDSYSTEM) {
            mavenLocal()
            println '...initializing MAVEN_LOCAL_FOR_BUILDSYSTEM'
        }
        mavenRepo name: 'public', url: MAVEN_REPO

        if (!MAVEN_LOCAL_FOR_BUILDSYSTEM) {
            mavenLocal()
        }
    }

    dependencies {
        classpath "no.statkart.sktools.gradle:gradle-plugins:1.2-SNAPSHOT" //some gradle plugins
    }

}

allprojects {
    apply plugin: 'java'
    apply plugin: 'idea'

    repositories {
        if (MAVEN_LOCAL_FOR_PROJECT) {
            mavenLocal()
            println '...initializing MAVEN_LOCAL_FOR_PROJECT'
        }
        mavenRepo name: 'public', url: MAVEN_REPO

        if (!MAVEN_LOCAL_FOR_PROJECT) {
            mavenLocal()
        }
    }

    dependencies {
        compile "no.statkart.skif:skif-service-common:2.1-SNAPSHOT" //some project libs
    }

}




/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */


task demo(description: 'Kjører demo for å teste funksjonaliteten') {


    doLast {

        forkGradle(['assertMavenPublicForBuildsystem', 'assertMavenPublicForProject'], [MAVEN_REPO: project.MAVEN_REPO])

        forkGradle(['assertMavenLocalForBuildsystem', 'assertMavenPublicForProject'], [MAVEN_REPO: project.MAVEN_REPO, MAVEN_LOCAL_FOR_BUILDSYSTEM: 'true'])
        forkGradle(['assertMavenPublicForBuildsystem', 'assertMavenLocalForProject'], [MAVEN_REPO: project.MAVEN_REPO, MAVEN_LOCAL_FOR_PROJECT: 'true'])

        forkGradle(['assertMavenLocalForBuildsystem', 'assertMavenLocalForProject'], [MAVEN_REPO: project.MAVEN_REPO, MAVEN_LOCAL_FOR_BUILDSYSTEM: 'true', MAVEN_LOCAL_FOR_PROJECT: 'true'])
        forkGradle(['assertMavenLocalForBuildsystem', 'assertMavenLocalForProject'], [MAVEN_REPO: project.MAVEN_REPO, MAVEN_LOCAL: 'true'])

    }

}

task assertMavenPublicForBuildsystem() << {
    assert project.MAVEN_LOCAL_FOR_BUILDSYSTEM == null
}
task assertMavenPublicForProject() << {
    assert project.MAVEN_LOCAL_FOR_PROJECT == null
}

task assertMavenLocalForBuildsystem() << {
    assert project.MAVEN_LOCAL_FOR_BUILDSYSTEM != null
}
task assertMavenLocalForProject() << {
    assert project.MAVEN_LOCAL_FOR_PROJECT != null
}


/******************************************************************************************************************** **
 * Helper method for forking gradle builds programmatically. Using gradle Tooling API
 * (Only relevant for testing)
 ******************************************************************************************************************** */
void forkGradle(List<String> tasks, Map env = [:]) {
    org.gradle.tooling.ProjectConnection connection = org.gradle.tooling.GradleConnector.newConnector().forProjectDirectory(project.projectDir).connect();
    try {
        org.gradle.tooling.BuildLauncher build = connection.newBuild()
                .forTasks(tasks.collect { "${project.path}:${it}".toString() } as String[])
                .withArguments(env.collect {"-D${it.key}=${it.value}" } as String[])
                .run();
    } finally {
        connection.close();
    }
}




