/******************************************************************************************************************** **
 *
 * Demonstrasjon på hvordan en kan sette opp en database med forskjellige brukere.
 *
 * Eksempelet kan enkelt utvides til å omfatte flere databaser.
 *
 ******************************************************************************************************************** */

apply plugin: 'sktools-dbtools-plugin'


//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {

    useDrivers 'org.hsqldb:hsqldb:2.2.8'

    toolset( name:'sa', type:'hsqldb', prefix:'sa') {
        url = "jdbc:hsqldb:mem:testbase"

        credentials.username = 'SA'
        credentials.password = ''

        sqlTask( 'CreateUsers', sqlFile:'src/main/sql/system/CreateUsers.sql')

        properties = [brukernavn:'BRUKER1']
        properties += [brukernavn:'BRUKER1']
    }

    toolset( name:'bruker1', type:'hsqldb', prefix:'bruker1') {
        url = "jdbc:hsqldb:mem:testbase"

        credentials.username = 'BRUKER1'
        credentials.password = 'BRUKER1'

        sqlTask( 'CreateTable1', sqlFile:'src/main/sql/bruker1/CreateTable1.sql')
    }

}

task dbInit() {

    description = 'Setter opp demobase'
    def tasks = [
            tasks.saCreateUsers,
            tasks.bruker1CreateTable1
    ]

    tasks.each {
        dependsOn = it.dependsOn
    }

    doLast {
        tasks.each {
            println "${name} -> ${it.path}"
            it.execute()
        }
    }

}

/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task runDemo(dependsOn:clean) {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    doLast {

        println 'Tester dbInit...'
        forkGradle(['dbInit', 'assertTable1AccessForSA', 'assertTable1AccessForBruker1'])
    }
}


task assertTable1AccessForSA() << {
    def convention = project.convention.plugins['db'].dbToolSets['sa']
    def sql = groovy.sql.Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
    sql.eachRow("select count(*) from BRUKER1.TABLE1") {
      assert it[0] == 0
    }
}

task assertTable1AccessForBruker1() << {
    def convention = project.convention.plugins['db'].dbToolSets['bruker1']
    def sql = groovy.sql.Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
    sql.eachRow("select count(*) from TABLE1") {
      assert it[0] == 0
    }
    sql.eachRow("select count(*) from BRUKER1.TABLE1") {
      assert it[0] == 0
    }
}

/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(Map props = [:], List tasks) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks.collect {"${project.path}:${it}".toString()}
    sp.projectProperties = props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}

