/******************************************************************************************************************** **
 *
 * Demonstrasjon på hvordan en kan sette opp en database med forskjellige brukere.
 *
 * Eksempelet kan enkelt utvides til å omfatte flere databaser.
 *
 ******************************************************************************************************************** */

apply plugin: 'sktools-dbtools-plugin'


configurations {
    drivers
}

dependencies {
    drivers 'org.hsqldb:hsqldb:2.2.8'
}


//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {

    useDrivers configurations.drivers


    useToolset('hsqldb', 'Sa', 'main/sql/system') {

        url = "jdbc:hsqldb:mem:testbase"

        credentials.username = 'SA'
        credentials.password = ''
    }

    useToolset('hsqldb', 'Bruker1', 'main/sql/bruker1') {

        url = "jdbc:hsqldb:mem:testbase"

        credentials.username = 'BRUKER1'
        credentials.password = 'BRUKER1'
    }

}

task dbInit() {

    description = 'Setter opp demobase'
    def tasks = [
            tasks.SaCreateUsers,
            tasks.Bruker1CreateTable1
    ]

    tasks.each {
        dependsOn = it.dependsOn
    }

    doLast {
        tasks.each {
            println "${name} -> ${it.path}"
            it.execute()
        }
    }

}

/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task runDemo() {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    doLast {

        println 'Tester dbInit...'
        forkGradle(['dbInit', 'assertTable1AccessForSA', 'assertTable1AccessForBruker1'])
    }
}


task assertTable1AccessForSA() << {
    def convention = project.convention.plugins['db'].dbToolSets['Sa']
    def sql = groovy.sql.Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
    sql.eachRow("select count(*) from BRUKER1.TABLE1") {
      assert it[0] == 0
    }
}

task assertTable1AccessForBruker1() << {
    def convention = project.convention.plugins['db'].dbToolSets['Bruker1']
    def sql = groovy.sql.Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
    sql.eachRow("select count(*) from TABLE1") {
      assert it[0] == 0
    }
    sql.eachRow("select count(*) from BRUKER1.TABLE1") {
      assert it[0] == 0
    }
}

/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(List tasks, Map props = [:]) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks.collect {"${project.path}:${it}".toString()}
    sp.projectProperties = props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}

