
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Database
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
db_hostname=localhost
db_sid=DEV1
db_port=1521


! Systembruker/password som brukes ved database administrasjon, create.user, export/import etc.
db_system_username=SYSTEM
db_system_password=MATRIKKELADM

systemProp.db.oradata=D:\\oracle\\Oradata


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Database - historikk index1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

historikk_index1_db_system_username=${db_system_username}
historikk_index1_db_system_password=${db_system_password}

historikk_index1_db_username=HISTORIKKDEMO2_H
historikk_index1_db_password=${historikk_index1_db_username}
historikk_index1_db_sid=${db_sid}
historikk_index1_db_hostname=${db_hostname}
historikk_index1_db_port=${db_port}
historikk_index1_db_url=jdbc:oracle:thin:@${historikk_index1_db_hostname}:${historikk_index1_db_port}:${historikk_index1_db_sid}
historikk_index1_db_schema=${historikk_index1_db_username}

!forenklet oppsett for denne demoen: forventer at USERS tablespacet finnes
historikk_index1_db_tablespace=USERS
historikk_index1_db_tablespace_index=${historikk_index1_db_tablespace}


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Database - historikk index2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

historikk_index2_db_system_username=${db_system_username}
historikk_index2_db_system_password=${db_system_password}

historikk_index2_db_username=HISTORIKKDEMO3_H
historikk_index2_db_password=${historikk_index2_db_username}
historikk_index2_db_sid=${db_sid}
historikk_index2_db_hostname=${db_hostname}
historikk_index2_db_port=${db_port}
historikk_index2_db_url=jdbc:oracle:thin:@${historikk_index2_db_hostname}:${historikk_index2_db_port}:${historikk_index2_db_sid}
historikk_index2_db_schema=${historikk_index2_db_username}

!forenklet oppsett for denne demoen: forventer at USERS tablespacet finnes
historikk_index2_db_tablespace=USERS
historikk_index2_db_tablespace_index=${historikk_index2_db_tablespace}



