apply plugin: 'java'
apply plugin: 'sktools-wsdocgen-plugin'

sourceSets {
    main {
        wsdoc.group {
            targetPath 'build/main/docs/wsdoc' //default
            include '**/*WSBean.java'          //default
            lookupPath '../../domain/javadoc'  //valgfri funksjonalitet
        }
    }
}


task runDemo() {
    dependsOn 'testGenWsDoc'
    dependsOn 'testClean'

}

task testGenWsDoc(dependsOn:'genWsDoc') << {
    assert file('build/main/docs/wsdoc/TestService.html').exists()
}

task testClean(dependsOn:['testGenWsDoc', 'clean']) << {
    println 'todo'
}
