apply plugin: 'java'
apply plugin: 'sktools-wsdocgen-plugin'

sourceSets {
    main {
        wsdoc.group {
            targetPath 'build/main/docs/wsdoc' //default
            include '**/*WSBean.java'          //default
            lookupPath '../../domain/javadoc'  //valgfri funksjonalitet
        }
    }
}


task runDemo() {
    dependsOn 'testGenWsdoc'
    dependsOn 'testPackWsdoc'
    dependsOn 'testClean'

}

task('testPackWsdoc', dependsOn: tasks.packWsdoc) {
    doFirst {
        assert project.zipTree(packWsdoc.archivePath).matching { include '**/TestService.html' }.files.size() == 1
    }
}

task('testGenWsdoc', dependsOn: tasks.genWsdoc) {
    doFirst {
        assert file('build/main/docs/wsdoc/TestService.html').exists()
    }
}

task('testClean', dependsOn:[tasks.testGenWsdoc, tasks.clean]) {
    doFirst {
        logger.quiet 'todo'
    }
}
