/******************************************************************************************************************** **
 * Demonstrerer hvordan en kan integrere med JavaPlugin og andre konfigurasjoner
 *
 * Ved 'build' så blir da "runtime" artifaktet generert
 * Ved 'buildWeblogic' så blir da "weblogic" artifaktet generert
 * - PS: merk at dette artifaktet vil bli automatiskt generert der en trenger det i andre prosjekter (war, ear, testkode osv)
 ******************************************************************************************************************** */

apply plugin: 'java'
apply plugin: 'sktools-weblogic-wsclient-plugin'



dependencies {
    weblogic libraries.weblogic
    weblogic libraries.'tools.jar'  //tools jar må være med for weblogic 10.3.5 eller nyere?
}

weblogicWsClient {
    webService {
        name 'client1'
        baseWar { project(path:':war1', configuration:'weblogic') }
    }
}

// MAT-10082
// Dersom en ønsker at artifaktet blir generert ved build/assemble
afterEvaluate { Project project ->

    //må være sikker på at pluginen er registrert.. bruker sen evaluering som eksempel
    if (project.plugins.hasPlugin('sktools-weblogic-wsclient-plugin')) {
        project.tasks.assemble.dependsOn 'jarWeblogic'
    }
}


// Task for generering av all generert kode
task gen { genTask ->
    project.tasks.withType(no.statkart.sktools.gradle.plugins.weblogic.wsclient.WeblogicGenClientTask).all {
        genTask.dependsOn(it)
    }
}


/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */



task runDemo() << {

    println 'Tester clean...'
    forkGradle(['clean', 'assertClean'])

    println 'Tester bygging av weblogic artifakt...'
    forkGradle(['buildWeblogic', 'assertBuildWeblogic'])

    assert !file("build/libs/${project.name}.jar").exists() //skal ikke trigge generering av andre artifakter

    println 'Tester bygging av main artifakt...'
    forkGradle(['build', 'assertBuild'])

    println 'Tester bygging av alle artifakter...'   //assemble depends on 'jarWeblogic'
    forkGradle(['clean', 'build', 'assertBuild', 'assertBuildWeblogic'])

    println 'Tester generering via gen...'   //gen depends on 'jarWeblogic'
    forkGradle(['clean', 'gen', 'assertGeneratedWeblogicResources', 'assertGeneratedWeblogicClasses'])

}


task assertGeneratedWeblogicResources() << {
    assert file('gen/weblogic/wsclient/META-INF/wsdls/TestServiceWS_v1.wsdl').exists()
}

task assertGeneratedWeblogicClasses() << {
    assert file('gen/weblogic/wsclient/no/statkart/test/service1/TestServiceWSV1.java').exists()
}


task assertBuildWeblogic() {
    dependsOn assertGeneratedWeblogicResources
    dependsOn assertGeneratedWeblogicClasses
    doLast {
        assert file("build/libs/${project.name}-weblogic.jar").exists()
    }
}

task assertBuild() << {
    assert file("build/libs/${project.name}.jar").exists()
}

task assertClean() << {
    assert !file('gen/classes/weblogic').exists()
    assert !file("build/libs/${project.name}-weblogic.jar").exists()
    assert !file("build/libs/$project.{name}.jar").exists()
}


/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(List tasks, Map props = [:]) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks.collect {"${project.path}:${it}".toString()}
    sp.projectProperties = props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}
