apply plugin: 'sktools-dbtools-plugin'


def libraries = [
        drivers: ['com.oracle.jdbc:ojdbc6:11.2.0.4@jar']
]


/**
 * SKTOOLS-32
 * Demonstrerer angivelse av filtrerte properties for toolset
 */


configureDatabasePlugin {

    useDrivers libraries.drivers

    toolset( name:'main', type:'oracle', prefix:'') {

        //SKTOOLS-32
        assert properties['dynamic'] == null //ikke satt enda


        sqlTask('CustomTask', sqlString: 'select 1 from dual') {
//            doFirst {
                toolset.properties['dynamic'] = 'CustomTaskValue'
//            }
        }

        url = "jdbc:oracle:thin:@${project.ext.oracle_db_host}:${project.ext.oracle_db_port}:${project.ext.oracle_db_sid}"

        //SKTOOLS-32
        assert properties['dynamic'] == 'CustomTaskValue' //som satt over

        properties = [
                dynamic: 'initialValue',

                username: project.properties.get('username', 'BRUKER1'),
                password: project.properties.get('password', 'BRUKER1'),
        ]

        //SKTOOLS-32
        assert properties['dynamic'] == 'initialValue' //som satt over


        //SKTOOLS-32
        sqlTask('CustomTask2', sqlString: 'select 1 from dual') {
            toolset.properties['dynamic'] = 'CustomTask2Value'
        }
        assert properties['dynamic'] == 'CustomTask2Value' //som satt over



    }

}


