apply plugin: 'sktools-ideaextensions-plugin'
apply plugin: 'groovy'


/**
 * Tester at filer maskeres bort
 * Tester at Perforce kobles inn som vcs
 */
ideaExtensions {
    ignoreMasks += '*.tmp'
    ignorePaths += '.gradle'
    vcs 'Perforce'
    inspectionProfile = 'inspections.xml'
    codeStyle = 'codestyle.xml'
}

tasks.idea.doFirst {
    //generer noen filer
    project.file('config').mkdirs()
    project.file('config/myconfig.tmp').createNewFile()
    project.file('config/myconfig2.properties').createNewFile()
    project.file('gradle.log').createNewFile()
}

tasks.clean.dependsOn tasks.cleanIdea //cleans out generated idea files
tasks.clean.dependsOn tasks.cleanIdeaWorkspace //cleans out generated idea files

task runDemo() {
    dependsOn 'testMasks'
    dependsOn 'testVCS'
    dependsOn 'testInspections'
    dependsOn 'testCodeStyle'
}


task('testMasks', dependsOn: tasks.idea) {
    doFirst {
        assert file("${project.name}.iws").text.contains('mask="*.tmp"')
    }
}

task('testVCS', dependsOn: tasks.idea) {
    doFirst {
        assert file("${project.name}.ipr").text.contains('vcs="Perforce"')
    }
}

task('testInspections', dependsOn: tasks.idea) {
    doFirst {
        assert file("${project.name}.ipr").text.contains('"SKTools Default"')
    }
}

task('testCodeStyle', dependsOn: tasks.idea) {
    doFirst {
        assert file("${project.name}.ipr").text.contains('"XML_ATTRIBUTE_WRAP"')
    }
}