apply plugin: 'sktools-dbtools-plugin'


 // Kort intro til HSQLDB - http://hsqldb.org
 /**
  * Hsqldb er en liten lettvekts database som kan kjøres in memory eller som stand alone.
  * En har mulighet til å persistere informasjon til disk.
  *
  * Dersom en kjører in memory kan en aksessere databasen innenfor samme javavm.
  *
  * Ved aksessering ifra flere prosesser bør en kjøre basen i "stand alone" mode. En har her fortsatt mulighet til
  * å kjøre denne som in memory. Databasen kjører da i en frittstående prosess.
  */
configurations {
    hsqldb
}

dependencies {
    hsqldb 'org.hsqldb:hsqldb:2.2.9'
}


//see DbtoolsConvention#ConfigureDatabasePlugin
configureDatabasePlugin {

    useDrivers project.configurations.hsqldb

    toolset( name:'sa', type:'hsqldb', prefix:'') {
        //;shutdown=true
        url = "jdbc:hsqldb:hsql://localhost/testPatching${project.version}"
        credentials.username = 'SA'
        credentials.password = ''


        patch {
            patchTask('Latest', sqlFile:'src/sql/schema1/patch.sql', description: 'Databasepatcher for schema1')
        }

        patch {
            name = 'Component2'
            patchTask('Latest', sqlFile:'src/sql/schema2/patch.sql', description: 'Databasepatcher for schema2')
        }

        patch {
            // patch for tomt skjema. Demoen illustrerer funksjonalitet benyttet rundt import
            name = 'Empty'
            definePatchVersionTask('SetPatchversionFor2_2', dbVersion: '2.2', patchNumber: 34)
//            assertPatchVersionTaskName = 'AssertPatchVersionEmpty'
            assertPatchVersionTask('AssertPatchVersion', dbVersion: '2.2', patchNumber: 34)

        }

        sqlTask('ImportEmpty', sqlString:'PROMPT Pseudo task for import')

        properties = [:]

    }


    taskSequence('dbImportEmpty', description: "Import of 'Empty' schema.") {
        dependsOn dbToolSets['sa'].tasks['ImportEmpty']
        dependsOn dbToolSets['sa'].patch['Empty'].tasks['SetPatchversionFor2_2']  // "EmptySetPatchversionFor2_2"
    }

}




/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task runDemo() {


    Assert.that('clean').describedAs('startUpEmptyHsqlInstances').leadsTo(project).withState {
        tearDownDatabase()
        startUpDatabase()
        assertNoPatchTable()
    }

    // 'Tester patchComponent1...'
    Assert.that('patchLatest').describedAs('patchCopmonent1RunsComponent1Patches').prep {
        assertNoTestTable()

    }.leadsTo(project).withState {
        sqlSA().eachRow("select count(*) from PATCHINFO where dbVersion='1.0' and patchNo=4 AND component='null'") {
            assert it[0] == 1 // row# PATCHINFO
        }
        sqlSA().eachRow("select count(*) from TEST_TABLE where ID=1") {
            assert it[0] == 1 // row# TEST_TABLE
        }
    }


    Assert.that('patchComponent2Latest').describedAs('patchCopmonent2RunsComponent2Patches').prep {
        assertNoTestTable2()

    }.leadsTo(project).withState {

        //_assertComponent2Patchnummer4
        def sql = sqlSA()
        sql.eachRow("select count(*) from PATCHINFO where dbVersion='0.2' and patchNo=4 AND component='Component2'") {
            if (it[0] >= 1) {
                assert true
            } else {
                listPatchInfoTableForComponent(sql, 'Component2') //print debug info
                listPatchInfoTableForComponent(sql) //print debug info
                assert false //forventet a finne versjon for komponent
            }
        }

        //_assertPatchComponent2
        sqlSA().eachRow("select count(*) from TEST_TABLE2 where ID=1") {
            assert it[0] == 1
        }
    }

    /**
     * Illustrerer mekanikk for setting av patch# etter import (eksperimentell)
     * - PS: vanligvis så følger patchinfo data med importerte data
     */
    Assert.that('dbImportEmpty').describedAs('definePatchversionCreatesPatchinfo').leadsTo(project).withState {
        def sql = sqlSA()
        sql.eachRow("select count(*) from PATCHINFO where dbVersion='2.2' and patchNo=34 AND component='Empty'") {
            if (it[0] >= 1) {
                assert true
            } else {
                listPatchInfoTableForComponent(sql, 'Empty') //print debug info
                listPatchInfoTableForComponent(sql) //print debug info
                assert false //forventet a finne versjon for komponent
            }
        }
    }


    Assert.that(dbToolSets['sa'].patch['Empty'].tasks['AssertPatchVersion'].name).describedAs('assertPatchVersionForComponentEmpty').leadsTo(project).withState {
        //eksperimentell assert for byggesystem
    }


    Assert.that('clean').describedAs('teardown').leadsTo(project).withState {
        println 'Shutting down running HSQLDB instance...'
        tearDownDatabase()
    }

}



class Assert {
    def taskName
    String[] taskNames
    Project project
    List<Closure> prep = []

    static def previousTask = null

    static Assert that(String... taskNames) {
        Assert instance = new Assert(); instance.taskNames = taskNames; return instance
    }

    Assert describedAs(String taskName) {
        this.taskName = taskName; this
    }

    Assert prep(Closure prepProjectBeforeAsserts) {
        prep << [prepProjectBeforeAsserts]; this
    }

    Assert leadsTo(Project project = project) {
        this.project = project; this
    }

    Assert withState(Closure check) {
        def task = project.task(taskName, type: GradleBuild) {
            dir = project.projectDir
            tasks = taskNames
            startParameter.systemPropertiesArgs = [noMavenBootstrap: 'true']
            startParameter.projectProperties = [sktools_versjon:"${project.version}"]
            prep.reverseEach { Closure beforeAsserts -> doFirst { beforeAsserts.setDelegate(this); beforeAsserts.run()}}
            doLast { check.setDelegate(this); check.run() }
            doFirst {
                println('--------------------------------------------------------------------------------');
                println "Testing use case: ${taskName} tasks=${taskNames}\n\n\n"
            }
            doLast {
                println "\n  ...end of test case: ${taskName}"
                println('--------------------------------------------------------------------------------\n\n');
            }
            outputs.upToDateWhen { false } //always run this...
        }
        project.tasks['runDemo'].dependsOn task

        if (previousTask) task.dependsOn previousTask //ordered execution of asserts...
        previousTask = task
        this
    }

    //convenience methods and asserts....


    /**
     * Verifies that {@code TEST_TABLE2} does not exists
     */
    void assertNoTestTable2() {
        try {
            sqlSA().eachRow("select count(*) from TEST_TABLE2") { }
            assert false //forventer at tabell ikke finnes
        } catch (java.sql.SQLException e) {
            assert true
        }
    }


    /**
     * Verifies that {@code TEST_TABLE} does not exists
     */
    void assertNoTestTable() {
        try {
            sqlSA().eachRow("select count(*) from TEST_TABLE") { }
            assert false //forventer tabell ikke finnes
        } catch (java.sql.SQLException e) {
            assert true
        }
    }

    /**
     * Verifies that {@code PATCHINFO} does not exists
     */
    void assertNoPatchTable() {
        try {
            sqlSA().eachRow("select count(*) from PATCHINFO") { }
            assert false //forventer at tabell ikke finnes
        } catch (java.sql.SQLException e) {
            assert true
        }
    }


    groovy.sql.Sql sqlSA() {
        def convention = project.convention.plugins['db'].dbToolSets['sa']
        groovy.sql.Sql.newInstance(convention.url, convention.credentials.username, convention.credentials.password, convention.driver)
    }


    void listPatchInfoTableForComponent(def sql, def component = null) {
        try {
            def sqlString = "select * from PATCHINFO"
            if (component != null)  sqlString += " where component='${component}'"
            println "Utskrift av PATCHINFO component=${component}:\n\n"

            if (sql.rows(sqlString).isEmpty()) {
                println "\t<empty>"
            } else {
                sql.eachRow(sqlString) {
                    println it
                }
            }

        } catch (java.sql.SQLException e) {
            assert false
        }
    }


    void tearDownDatabase() {
        println "Tar ned database ${project.convention.plugins.db.dbToolSets['sa'].url}"
        try {
            sqlSA().execute('SHUTDOWN;')
        } catch (java.sql.SQLException e) {
            assert true //får noen ganger EOFException her..
        }
    }

    void startUpDatabase() { //Forker database i subprosess
        //forking the groovy way until GRADLE-1254
        def cmd = ['java', '-cp', project.configurations.hsqldb.asPath, 'org.hsqldb.Server',
                '-database.0', 'mem:test', '-dbname.0', "testPatching${project.version}" //definisjon for database med navn "test"
        ]

        println "Starter opp database via kommando: \n\t${cmd.join(' ')}"
        def process = cmd.execute()

        process.in.close()
        process.out.close()
        process.err.close()

//        System.console().readLine('pause for debug..')
    }

}


