/******************************************************************************************************************** **
 *
 * SKIF-209: Verifiserer oppdaterte lib filer for relaterte prosjekter
 *
 ******************************************************************************************************************** */

apply plugin: 'sktools-webstart-plugin'

configurations {
    webstartlibs
}

dependencies {
    webstartlibs project(':echo-client')
}

webstart {
    unsigned {
        libDir 'unsigned'
        mainJar 'echo-client'
        jarDependencies configurations.webstartlibs
        jnlp {
            jnlpFilename 'echo-client.jnlp'
            title 'Unsigned client'
            application.mainClass 'WebstartTester'
            resources {
                javaRuntime '1.6+', '64m', '64m'
            }
        }
    }
    signed {
        sign rootProject.file('kodesignering.jks'), 'statenskartverk', 'SagZ45_p1'
        libDir 'signed'
        mainJar 'echo-client'
        jarDependencies configurations.webstartlibs
        jnlp {
            jnlpFilename 'echo-client-signed.jnlp'
            title 'Signed client'
            application.mainClass 'WebstartTester'
            resources {
                javaRuntime '1.6+', '64m', '64m'
            }
        }
    }
}

/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */
task runDemo(dependsOn:'clean') {
    description = 'Tester at lib filer blir oppdaterte'

    doLast {

        Assert.that('release', 'war').describedAs('releaseAssemblesClient').prep {
            println "Tømmer cache katalog..."
            project.rootProject.delete('.cache')

            println "Sletter genererte filer"
            project.project(':echo-client').delete('src/main/SKIF-209')

        }.leadsTo(project).withState {

            //'release' version without SNAPSHOT
            assertEchoClientClasses()
        }


        Assert.that('release', 'war').describedAs('releaseAssemblesUpdatedClient').prep {
            println "Legger til genererte filer..."
            File file = project.project(':echo-client').file('src/main/SKIF-209/addedResource.txt')
            file.parentFile.mkdirs()
            file.createNewFile()

        }.leadsTo(project).withState {

            //'release' version without SNAPSHOT
            assertEchoClientClasses()
            assertAddedEchoClientClasses()
        }

    }
}





class Assert {
    def taskName
    String[] taskNames
    Project project
    List<Closure> prep = []

    static def previousTask = null

    static Assert that(String... taskNames) {
        Assert instance = new Assert(); instance.taskNames = taskNames; return instance
    }

    Assert describedAs(String taskName) {
        this.taskName = taskName; this
    }

    Assert prep(Closure prepProjectBeforeAsserts) {
        prep << [prepProjectBeforeAsserts]; this
    }

    Assert leadsTo(Project project = project) {
        this.project = project; this
    }

    Assert withState(Closure check) {
        def task = project.task(taskName, type: GradleBuild) {
            dir = project.projectDir
            tasks = taskNames
            startParameter.systemPropertiesArgs = [noMavenBootstrap: 'true']
            prep.reverseEach { Closure beforeAsserts -> doFirst { beforeAsserts.setDelegate(this); beforeAsserts.run()}}
            doLast { check.setDelegate(this); check.run() }
            doFirst {
                println('--------------------------------------------------------------------------------');
                println "Testing use case: ${taskName} tasks=${taskNames}\n\n\n"
            }
            doLast {
                println "\n  ...end of test case: ${taskName}"
                println('--------------------------------------------------------------------------------\n\n');
            }
            outputs.upToDateWhen { false } //always run this...
        }
        project.tasks['runDemo'].dependsOn task

        if (previousTask) task.dependsOn previousTask //ordered execution of asserts...
        previousTask = task
        this
    }

    //convenience methods and asserts....

    void assertEchoClientClasses() {
        FileTree warTree = project.zipTree(war.archivePath)

        ['signed/echo-client*.jar', 'unsigned/echo-client*.jar'].each { String pattern ->
            def archive = warTree.matching { include pattern }.singleFile
            assert archive.exists() //forventer at jar fil er opprettet

            assert !project.zipTree(archive).matching {include '**/*.class'}.files.isEmpty()
        }
    }

    void assertAddedEchoClientClasses() {
        FileTree warTree = project.zipTree(war.archivePath)

        ['signed/echo-client*.jar', 'unsigned/echo-client*.jar'].each { String pattern ->
            def archive = warTree.matching { include pattern }.singleFile
            assert archive.exists() //forventer at jar fil er opprettet

            assert project.zipTree(archive).matching {include 'addedResource.txt'}.files.size() == 1
        }
    }


}


