/******************************************************************************************************************** **
 *
 * SKIF-209: Verifiserer oppdaterte lib filer for relaterte prosjekter
 *
 ******************************************************************************************************************** */

apply plugin: 'sktools-webstart-plugin'

configurations {
    webstartlibs
}

dependencies {
    webstartlibs project(':echo-client')
}

webstart {
    unsigned {
        libDir 'unsigned'
        mainJar 'echo-client'
        jarDependencies configurations.webstartlibs
        jnlp {
            jnlpFilename 'echo-client.jnlp'
            title 'Unsigned client'
            application.mainClass 'WebstartTester'
            resources {
                javaRuntime '1.6+', '64m', '64m'
            }
        }
    }
    signed {
        sign rootProject.file('kodesignering.jks'), 'statenskartverk', 'SagZ45_p1'
        libDir 'signed'
        mainJar 'echo-client'
        jarDependencies configurations.webstartlibs
        jnlp {
            jnlpFilename 'echo-client-signed.jnlp'
            title 'Signed client'
            application.mainClass 'WebstartTester'
            resources {
                javaRuntime '1.6+', '64m', '64m'
            }
        }
    }
}

/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */
task runDemo(dependsOn: ['clean', ':echo-client:clean']) {
    description = 'Tester at lib filer blir oppdaterte'

    final File resourceFile = project.project(':echo-client').file('src/main/SKIF-209/addedResource.txt')

    Assert.that('war').describedAs('warAssemblesClient').prep {
        println "Tømmer cache katalog..."
        project.rootProject.delete('.cache')

        println "Sletter genererte filer"
        project.project(':echo-client').delete('src/main/SKIF-209')
//        project.project(':echo-client').delete('build/resources/main')

    }.leadsTo(project).withState {

        assertWarEchoClientClasses()
        assertSourceFileEchoClientResource(resourceFile, 0)
        assertWarEchoClientResources('addedResource.txt', 0)
    }


    Assert.that('war').describedAs('warAssemblesUpdatedClient').prep {
        println "Legger til genererte filer..."
        resourceFile.parentFile.mkdirs()
        resourceFile.createNewFile()

    }.leadsTo(project).withState {

        assertWarEchoClientClasses()
        assertSourceFileEchoClientResource(resourceFile, 1)
        assertWarEchoClientResources('addedResource.txt', 1)
    }

}





class Assert {
    def taskName
    String[] taskNames
    Project project
    List<Closure> prep = []

    static def previousTask = null

    static Assert that(String... taskNames) {
        Assert instance = new Assert(); instance.taskNames = taskNames; return instance
    }

    Assert describedAs(String taskName) {
        this.taskName = taskName; this
    }

    Assert prep(Closure prepProjectBeforeAsserts) {
        prep << [prepProjectBeforeAsserts]; this
    }

    Assert leadsTo(Project project = project) {
        this.project = project; this
    }

    Assert withState(Closure check) {
        def task = project.task(taskName, type: GradleBuild) {
            dir = project.projectDir
            tasks = taskNames
            startParameter.systemPropertiesArgs = [noMavenBootstrap: 'true']
            startParameter.projectProperties = [sktools_versjon:"${project.version}"]
            prep.reverseEach { Closure beforeAsserts -> doFirst { beforeAsserts.setDelegate(this); beforeAsserts.run()}}
            doLast { check.setDelegate(this); check.run() }
            doFirst {
                println('--------------------------------------------------------------------------------');
                println "Testing use case: ${taskName} tasks=${taskNames}\n\n\n"
            }
            doLast {
                println "\n  ...end of test case: ${taskName}"
                println('--------------------------------------------------------------------------------\n\n');
            }
            outputs.upToDateWhen { false } //always run this...
        }
        project.tasks['runDemo'].dependsOn task

        if (previousTask) task.dependsOn previousTask //ordered execution of asserts...
        previousTask = task
        this
    }

    //convenience methods and asserts....

    void assertWarEchoClientClasses() {
        FileTree warTree = project.zipTree(project.tasks.war.archivePath)

        ['signed/echo-client*.jar', 'unsigned/echo-client*.jar'].each { String pattern ->
            def archive = warTree.matching { include pattern }.singleFile
            assert archive.exists() //forventer at jar fil er opprettet

            assert !project.zipTree(archive).matching {include '**/*.class'}.files.isEmpty()
        }
    }

    void assertWarEchoClientResources(String filePattern, int expectedCount) {
        FileTree warTree = project.zipTree(project.tasks.war.archivePath)

        ['signed/echo-client*.jar', 'unsigned/echo-client*.jar'].each { String pattern ->
            def archive = warTree.matching { include pattern }.singleFile
            assert archive.exists() //forventer at jar fil er opprettet

            assert project.zipTree(archive).matching { include filePattern }.files.size() == expectedCount
        }
    }

    static void assertSourceFileEchoClientResource(File sourceFile, int expectedCount) {
        println "asserting ${sourceFile} exists. Expected: ${expectedCount.asBoolean()}, actual: ${sourceFile.exists()}"
        assert !sourceFile.exists() == !expectedCount //xnor expression
    }

}


