apply plugin: 'groovy'
apply plugin: 'maven-publish'

group = 'no.statkart.sktools.gradle'



dependencies {
    compileOnly gradleApi()

    implementation project(':gradle-plugins:weblogic-plugin')

    testImplementation gradleTestKit()
    testImplementation project(':build-utils:test-utils')
}

task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourceJar
        }
    }
}
