-- Patcher for Module1 til versjon 1.10

-- PATCH DB.MIN.VERSION="1.9.1"

-- PATCH DATA DB.VERSION="1.10" PATCH.NO="1" "Inserting Chuck Norris"
INSERT INTO TEST_TABLE1 (ID, NAVN) VALUES (1, 'CHUCK NORRIS');

-- PATCH INDEX DB.VERSION="1.10" PATCH.NO="2" "Indexing names and id"
CREATE INDEX TEST_TABLE1_IDX_01 ON TEST_TABLE1(NAVN, ID);
