-- Patcher for Module2 til versjon 1.10

-- PATCH DB.MIN.VERSION="1.9.1"

-- PATCH DATA DB.VERSION="1.10" PATCH.NO="1" "FK constraints to Module1"
ALTER TABLE TEST_TABLE2
   ADD CONSTRAINT FK_TEST_TABLE2 FOREIGN KEY (ID)
   REFERENCES TEST_TABLE1(ID);

-- PATCH DATA DB.VERSION="1.10" PATCH.NO="2" "Inserting Chuck Norris2"
INSERT INTO TEST_TABLE2 (ID, NAVN) VALUES (1, 'CHUCK NORRIS ALT');

