apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'maven-publish'

dependencies {
    //xjc
    compile 'com.sun.xml.bind:jaxb-xjc:2.2.11'
    compile 'org.glassfish.jaxb:jaxb-xjc:2.2.11', {
        exclude group: 'org.apache.ant', module: 'ant' //ant from gradle api - this resolves version conflicts on classpath for testing..
    }

    //jaxb impl og runtime
    compile 'com.sun.xml.bind:jaxb-impl:2.2.11'
    compile 'org.glassfish.jaxb:jaxb-runtime:2.2.11', {
        exclude group: 'org.apache.ant', module: 'ant' //ant from gradle api - this resolves version conflicts on classpath for testing..
    }

    //testing...
    testCompile project(':build-utils:test-utils')
    testCompile gradleApi()

}


task sourceJar(type: Jar) {
    from sourceSets.main.allJava
    classifier "sources"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourceJar
        }
    }
}

