apply plugin: 'sktools-filterproperties-plugin'
apply plugin: 'java'



filterProperties {
    properties testValue: 'myValue',
            'otherProperty': 'value'


}




task runDemo() {
    dependsOn 'testFilterResources'
}


task testFilterResources(dependsOn:'filterResources') << {
    assert file('gen/main/resources/someFile.txt').exists()
    assert file('gen/main/resources/someFile.txt').text.contains("version=@version@")
    assert file('gen/main/resources/someFile.txt').text.contains("testValue=myValue")
}

