apply plugin: 'sktools-xjc-plugin'


xjc {
    schema {
        path 'src/main/xsd'
    }
}





task runDemo {
    dependsOn 'testXjcGenerate'
    dependsOn 'testClean'
}

task testXjcGenerate(dependsOn:'processResources') << {
    assert file('gen/main/java/no/statkart/sktools/test/SimpleType.java').exists()
}

task testClean(dependsOn:['testXjcGenerate', 'clean']) << {
    println 'todo'
//    assert !file('gen/main/java/no/statkart/sktools/test/SimpleType.java').exists()
}