//apply plugin: 'java'
apply plugin: 'sktools-weblogic-wsclient-plugin'

dependencies {
    weblogic libraries.weblogic
}

weblogicWsClient {
    webService {
        name 'client1'
        baseWar { project(path:':war1', configuration:'weblogic') }
    }
}


task runDemo {
    dependsOn 'testGenWeblogicWsClient'
    dependsOn 'testClean'
}


task testGenWeblogicWsClient(dependsOn:'genWeblogicWsClient') << {
    assert file('gen/weblogic/wsclient/META-INF/wsdls/TestServiceWS_v1.wsdl').exists()
    assert file('gen/weblogic/wsclient/no/statkart/test/service1/TestServiceWSV1.java').exists()
}

task testClean(dependsOn:['testGenWeblogicWsClient', 'clean']) << {
    println 'todo'
    assert !file('gen/classes/weblogic').exists()
}
