apply plugin: 'java'
apply plugin: 'sktools-weblogic-wswar-plugin'


dependencies {
    weblogic libraries.weblogic
    weblogicCompile libraries.'tools.jar'
    weblogicCompile project(path: project.path, configuration:'runtime')
}




project.task('listSourceFiles') {
    doLast {
        println 'task.source() : ' + project.tasks.compileWeblogicJava.getSource()
        project.tasks.compileWeblogicJava.getSource().files.each {
            println "source += ${it}"
        }
    }
}

task runDemo() {
    dependsOn 'testCompileWeblogicJava'
    dependsOn 'testClean'
}

task testCompileWeblogicJava(dependsOn:'compileWeblogicJava') << {
    assert file('build/classes/weblogic/simple-demo.war/WEB-INF/classes/exceptiondemo01/ExceptionService1WSBean.class').exists()
    assert file('build/classes/weblogic/simple-demo.war/WEB-INF/ExceptionService2WS.wsdl').exists()
}

task testClean(dependsOn:['testCompileWeblogicJava', 'clean']) << {
    println 'todo'
//    assert !file('build/classes/weblogic').exists()
}

