/******************************************************************************************************************** **
 *
 * Demonstrasjon på bruk av plugin.
 *
 * Dette eksempelet illustrerer hvordan en kan lagdele web service implementasjon ved å legge resten i main SourceSet.
 *
 * En viser også eksempel implementasjon av 'gen' target.
 *
 ******************************************************************************************************************** */

apply plugin: 'java'
apply plugin: 'sktools-weblogic-wswar-plugin'


dependencies {
    weblogicCompile project(path: project.path)
//    weblogicCompile project(path: project.path, configuration:'default')  //samme som project

    weblogicProvided libraries.weblogic
}


warWeblogic {
    from 'src/weblogic/webapp'  //kobler inn ressurser som skal i war arkiv
}


task('gen').description = "Genererte ressurser for alle sourceSets"

//integrasjon med plugin
afterEvaluate {
    if (project.plugins.hasPlugin('sktools-weblogic-wswar-plugin')) {
        project.tasks.withType(no.statkart.sktools.gradle.plugins.weblogic.wswar.WeblogicWsCompileTask.class) {
            project.tasks.gen.dependsOn it
        }
    }
}

/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task('listSourceFiles') {
    doFirst {
        logger.quiet "task.source() : ${project.tasks.compileWeblogicJava.source}"
        project.tasks.compileWeblogicJava.source.files.each {
            logger.quiet "source += ${it}"
        }
    }
}

task runDemo() {
    description = 'Kjører en enkel demo for å verifisere funksjonalitet'

    Assert.that('clean', 'compileJava').describedAs('compileJavaGeneratesCompiledCode').prep { clean() }.leadsTo(project).withState {
        assertCompileJava()
    }

    Assert.that('genWeblogic').describedAs('genWeblogicGeneratesCompiledCode').prep { clean() }.leadsTo(project).withState {
        assertGenWeblogic()
        assertCompileWeblogicJava()
    }


    Assert.that('gen').describedAs('genGeneratesWeblogicCode').prep { clean() }.leadsTo(project).withState {
        assertGenWeblogic()
        assertCompileWeblogicJava()
    }

    Assert.that('warWeblogic').describedAs('archiveContainsGeneratedCode').prep { clean() }.leadsTo(project).withState {
        assertWarWeblogic()
        assertGenWeblogic()
        assertNoWebXmlInSourceSetOutputs()
    }

}

class Assert {
    def taskName
    String[] taskNames
    Project project
    List<Closure> prep = []

    static def previousTask = null

    static Assert that(String... taskNames) {
        Assert instance = new Assert(); instance.taskNames = taskNames; return instance
    }

    Assert describedAs(String taskName) {
        this.taskName = taskName; this
    }

    Assert prep(Closure prepProjectBeforeAsserts) {
        prep << prepProjectBeforeAsserts; this
    }

    Assert leadsTo(Project project = project) {
        this.project = project; this
    }

    Assert withState(Closure check) {
        def task = project.task(taskName, type: GradleBuild) {
            dir = project.projectDir
            tasks = taskNames
            startParameter.systemPropertiesArgs = [noMavenBootstrap: 'true']
            startParameter.projectProperties = [sktools_versjon:"${project.version}"]
            prep.reverseEach { Closure beforeAsserts -> doFirst { beforeAsserts.setDelegate(this); beforeAsserts.run()}}
            doLast { check.setDelegate(this); check.run() }
            doFirst {
                toConsole('--------------------------------------------------------------------------------');
                toConsole("Testing use case: ${taskName} tasks=${taskNames}\n\n\n");
            }
            doLast {
                toConsole "\n  ...end of test case: ${taskName}"
                toConsole('--------------------------------------------------------------------------------\n\n');
            }
            outputs.upToDateWhen { false } //always run this...
        }
        project.tasks['runDemo'].dependsOn task

        if (previousTask) task.dependsOn previousTask //ordered execution of asserts...
        previousTask = task
        this
    }

    private void toConsole(def message) {
        project.logger.quiet(message)
    }


    //convenience methods and asserts....

    void clean() {
        project.delete('build/classes', 'build/weblogic') //har problemer med clean av lib katalogen...
    }

    void assertWarWeblogic() {
        def war = project.file("build/libs/${project.name}-weblogic-${project.version}.war")
        assert war.exists() //forventer at war fil er opprettet

        assert !project.zipTree(war).matching { include 'WEB-INF/classes/WebConfig.class' }.files.isEmpty()
        assert project.zipTree(war).matching { exclude 'WEB-INF/'; include '**/WebConfig.*' }.files.isEmpty()

        assert !project.zipTree(war).matching { include 'WEB-INF/classes/exceptiondemo01/ExceptionService1WSBean.class' }.files.isEmpty()
        assert project.zipTree(war).matching { exclude 'WEB-INF/'; include '**/ExceptionService1WSBean.*' }.files.isEmpty()

        assert project.zipTree(war).matching { include '**/ServiceFaultInfo.*' }.files.isEmpty() //forventer ikke noen filer ifra main sourceset
        assert project.zipTree(war).matching { include '**/ServiceFaultInfo.*' }.files.isEmpty() //forventer ikke noen filer ifra main sourceset

        assert !project.zipTree(war).matching { include 'WEB-INF/web.xml' }.files.isEmpty() //forventer at web.xml kommer med i arkiv

        def webXml = project.zipTree(war).matching { include 'WEB-INF/web.xml' }.singleFile
        assert webXml.text.contains('<display-name>dummy</display-name>') //forventer denne versjonen av web.xml (ikke generert fil)

    }


    void assertNoWebXmlInSourceSetOutputs() {
        assert project.sourceSets.main.output.asFileTree.matching { include '**/web.xml' }.files.isEmpty()
        assert project.sourceSets.weblogic.output.asFileTree.matching { include '**/web.xml' }.files.isEmpty()
    }

    void assertGenWeblogic() {
        assert !project.sourceSets.weblogic.output.asFileTree.matching { include 'exceptiondemo01/ExceptionService1WSBean.class' }.files.isEmpty()
        assert !project.sourceSets.weblogic.output.asFileTree.matching { include 'exceptiondemo01/ExceptionService2WSBean.class' }.files.isEmpty()
    }

    void assertCompileWeblogicJava() {
        assert !project.sourceSets.weblogic.output.asFileTree.matching { include 'WebConfig.class' }.files.isEmpty()
    }

    void assertCompileJava() {
        assert project.sourceSets.main.output.asFileTree.find { it.name == 'ServiceException.class' }
        assert project.sourceSets.main.output.asFileTree.find { it.name == 'ServiceFaultInfo.class' }
    }

}





