
task runDemos(description: 'Eksekverer alle demoer i underprosjekter via forket gradle bygg', type: GradleBuild) {

    dir = "$buildDir/demos"
    tasks = ['demo']

    startParameter.projectProperties = [
            MAVEN_REPO: MAVEN_REPO,
            WEBLOGIC_HOME: WEBLOGIC_HOME,
            WEBLOGIC_VERSION: WEBLOGIC_VERSION,
    ]

    startParameter.showStacktrace = ShowStacktrace.ALWAYS


    doFirst {
        project.delete dir

//        def configuration = configurations.detachedConfiguration dependencies.create("no.statkart.sktools.gradle:gradle-plugins-demo:${version}")
        def configuration = configurations.detachedConfiguration dependencies.create("no.statkart.sktools.gradle:gradle-plugins:${version}:demos@zip")
        def zipFile = files(configuration).singleFile //har du husket på publisering til maven repo?

        logger.lifecycle "...extracting ${zipFile}"

        project.copy {
            into dir
            from zipTree(zipFile)
        }
    }
}


