/******************************************************************************************************************** **
 * Demonstrasjon av bruk av ekstra ressurser ala jasper rapportmaler
 *
 * Merk: Vanligvis så vil man deklarere en configuration for dependencies brukt for rapporter.
 ******************************************************************************************************************** */

apply plugin: 'java'

sourceSets {

    jasper {
        //har implementert noe understøttende jasper spesifik kode, ligger her i std java source dir
        java.srcDirs

        //registrerer disse outputene på main slik at disse blir med i evt jar fil for jasper sourceSet.. merk at builtBy er optional og gjør at tasken blir kalt ved 'idea', 'jar' ol
        output.dir('gen/jasper/reports', builtBy: 'genJasper')
    }

    main {
    }

}


configurations {
    myNiftyLibs {
        description = "Konfigurasjon som inneholder noen kjekke bibliotek vi bruker"
    }

    jasperCompile {
        extendsFrom myNiftyLibs //legger til noen libs som runtime dependency
    }
}



dependencies {
    myNiftyLibs 'net.sf.jasperreports:jasperreports:3.7.0'
    jasperRuntime 'commons-lang:commons-lang:2.6@jar'

    runtime configurations.jasperRuntime //legger til dependency - får da riktig classpath for main
}

project.tasks.build.dependsOn project.tasks.compileJasperJava

project.task('genJasper') {
    doLast {
        //evt tilleggslogikk her..
        project.mkdir('gen/jasper/reports')
    }

    project.tasks.compileJasperJava.dependsOn(it)
}

/**
 * Erstatter resources task for jasper sourceset
 *
 * En kan evt benytte configuration til å legge til dependencies for evt bibliotek. Benytt da compileClasspath for sourceset.
 */
project.task(sourceSets.jasper.processResourcesTaskName, overwrite:true, type:Copy) {
    from sourceSets.jasper.resources.srcDirs
    into sourceSets.jasper.output.resourcesDir

    //eksemplifiserer ved å genererer noen kopi-filer med annet navn
    rename { "${it}-generatedCopy" }


    doLast {
        println "Example implementation executed!"
    }

    project.tasks.gen.dependsOn(it)
}




/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task demo(dependsOn:'clean') {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    doLast {

        println 'Printer sourceSets definisjon...'
        forkGradle(['printSourceSets'])

        println 'Tester IntelliJ integrasjon før build...'
        forkGradle(['cleanIdea'])
        forkGradle(['ideaModule', 'assertIdeaModule'])

        println 'Tester IntelliJ integrasjon etter build...'
        forkGradle(['cleanIdea', 'build'])
        forkGradle(['ideaModule', 'assertIdeaModule'])

    }
}



task assertIdeaModule() << {

    file("${project.name}.iml").text.with {

        assert it.contains('<sourceFolder url="file://$MODULE_DIR$/src/main/java')
        assert it.contains('<sourceFolder url="file://$MODULE_DIR$/src/jasper/java')
        assert it.contains('<sourceFolder url="file://$MODULE_DIR$/src/test/java')

        assert it.contains('<root url="file://$MODULE_DIR$/build/resources/main')

        assert it.contains('<root url="file://$MODULE_DIR$/gen/jasper/reports')
        assert it.contains('<root url="file://$MODULE_DIR$/build/resources/jasper')

        assert it.contains('<root url="file://$MODULE_DIR$/src/jasper/resources') //forventer at denne hektes inn som source for lib

        assert it.contains('commons-lang-2.6.jar!')  //forventer at denne ligger som runtime avhengighet
        assert it.contains('jasperreports-3.7.0.jar!') //forventer denne som compile time avhengighet
    }

}


task printSourceSets() << {
    logger.info "SourceSets defined: "
    project.convention.plugins.java.sourceSets.each { s ->
        ['java', 'allJava', 'resources', 'filterResources', 'groovy', 'allGroovy', 'allSource'].each { id ->
            try {
                def prefix = "${s.name}.${id}"
                s."$id".srcDirs.each { println "$prefix <- ".padLeft(prefix.size() + 5, ' ') + project.relativePath(it); prefix = prefix.replaceAll(/./, ' ')  }
                println()
            } catch (MissingPropertyException mpe) {
                assert true //ok her
            }
        }
    }
}


/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(List tasks, Map props = [:]) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks.collect {"${project.path}:${it}".toString()}
    sp.projectProperties = props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}


