apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'maven-publish'

dependencies {

    compileOnly 'com.sun.xml.ws:jaxws-rt:2.3.2'
    implementation 'jakarta.xml.ws:jakarta.xml.ws-api:2.3.2'

    //Saxon for xslt 2.0
    //Saxon HE is the open source version
    runtimeOnly libraries.saxon

    //testing...
    testImplementation gradleTestKit()
    testImplementation project(':build-utils:test-utils')

}


// Write the plugin's classpath to a file to share with the tests
task processorClasspathManifest {
    def outputDir = file("$buildDir/$name")

    inputs.files(sourceSets.main.runtimeClasspath)
        .withPropertyName("runtimeClasspath")
    outputs.dir(outputDir)
        .withPropertyName("outputDir")

    doLast {
        outputDir.mkdirs()
        file("$outputDir/processor-classpath.txt").text = sourceSets.main.runtimeClasspath.asPath
    }
}

// Add the classpath file to the test runtime classpath
dependencies {
    testRuntimeOnly files(processorClasspathManifest)
}


task sourceJar(type: Jar) {
    from sourceSets.main.allJava
    classifier "sources"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourceJar
        }
    }
}

