apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'maven-publish'

dependencies {

    implementation libraries.jaxb_api
    implementation libraries.jaxws_annotations

    //Saxon for xslt 2.0
    //Saxon HE is the open source version
    runtime libraries.saxon

    //testing...
    testCompile gradleApi()
    testCompile project(':build-utils:test-utils')

}

task sourceJar(type: Jar) {
    from sourceSets.main.allJava
    classifier "sources"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourceJar
        }
    }
}

