apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'maven-publish'

java {
    withSourcesJar()
}

dependencies {

    compileOnly 'com.sun.xml.ws:jaxws-rt:3.0.2'
    implementation 'jakarta.xml.ws:jakarta.xml.ws-api:3.0.1'

    //Saxon for xslt 2.0
    //Saxon HE is the open source version
    runtimeOnly 'net.sf.saxon:Saxon-HE:12.3'

    //testing...
    testImplementation gradleTestKit()
    testImplementation project(':build-utils:test-utils')

}


// Write the plugin's classpath to a file to share with the tests
tasks.register('processorClasspathManifest') {
    def outputDir = file("$buildDir/$name")

    inputs.files(sourceSets.main.runtimeClasspath)
        .withPropertyName("runtimeClasspath")
    outputs.dir(outputDir)
        .withPropertyName("outputDir")

    doLast {
        outputDir.mkdirs()
        file("$outputDir/processor-classpath.txt").text = sourceSets.main.runtimeClasspath.asPath
    }
}

// Add the classpath file to the test runtime classpath
dependencies {
    testRuntimeOnly files(processorClasspathManifest)
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

