/******************************************************************************************************************** **
 *
 * Demonstrasjon på bruk av plugin.
 *
 * Dette eksempelet illustrerer hvordan en kan lagdele web service implementasjon ved å legge resten i main SourceSet.
 *
 * En viser også eksempel implementasjon av 'gen' target.
 *
 ******************************************************************************************************************** */

apply plugin: 'java'
apply plugin: 'sktools-weblogic-wswar-plugin'


dependencies {
    weblogic libraries.weblogic
    weblogicCompile libraries.'tools.jar'
    weblogicCompile project(path: project.path)
//    weblogicCompile project(path: project.path, configuration:'default')  //samme som project
}


warWeblogic {
    from 'src/weblogic/webapp'  //kobler inn ressurser som skal i war arkiv
}


task('gen').description = "Genererte ressurser for alle sourceSets"


//integrasjon med plugin
afterEvaluate {
    if (project.plugins.hasPlugin('sktools-weblogic-wswar-plugin')) {
        project.tasks.withType(no.statkart.sktools.gradle.plugins.weblogic.wswar.WeblogicWsCompileTask.class) {
            project.tasks.gen.dependsOn it
        }
    }
}


/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

project.task('listSourceFiles') {
    doLast {
        println 'task.source() : ' + project.tasks.compileWeblogicJava.getSource()
        project.tasks.compileWeblogicJava.getSource().files.each {
            println "source += ${it}"
        }
    }
}

task runDemo(dependsOn:'clean') {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    doLast {
        println "Tester generering av main"
        forkGradle(['clean', 'compileJava', 'assertCompileJava'])

        println "Tester genWeblogic genererer"
        forkGradle(['clean', 'genWeblogic', 'assertGenWeblogic', 'assertCompileWeblogicJava'])

        println "Tester 'gen'-task integrasjon"
        clean()
        forkGradle(['gen', 'assertGenWeblogic', 'assertCompileWeblogicJava'])

        println "Tester arkiv"
        clean()
        forkGradle(['warWeblogic', 'assertWarWeblogic', 'assertGenWeblogic', 'assertCompileWeblogicJava', 'assertNoWebXmlInSourceSetOutputs'])

    }
}

void clean() {
    project.delete('build/classes', 'build/weblogic') //har problemer med clean av lib katalogen...
}

task assertWarWeblogic() << {
    def war = project.file("build/libs/${project.name}-weblogic.war")
    assert war.exists() //forventer at war fil er opprettet

    assert !project.zipTree(war).matching {include 'WEB-INF/classes/WebConfig.class'}.files.isEmpty()
    assert project.zipTree(war).matching {exclude 'WEB-INF/'; include '**/WebConfig.*'}.files.isEmpty()

    assert !project.zipTree(war).matching {include 'WEB-INF/classes/exceptiondemo01/ExceptionService1WSBean.class'}.files.isEmpty()
    assert project.zipTree(war).matching {exclude 'WEB-INF/'; include '**/ExceptionService1WSBean.*'}.files.isEmpty()

    assert project.zipTree(war).matching {include '**/ServiceFaultInfo.*'}.files.isEmpty() //forventer ikke noen filer ifra main sourceset
    assert project.zipTree(war).matching {include '**/ServiceFaultInfo.*'}.files.isEmpty() //forventer ikke noen filer ifra main sourceset

    assert !project.zipTree(war).matching {include 'WEB-INF/web.xml'}.files.isEmpty() //forventer at web.xml kommer med i arkiv

    def webXml = project.zipTree(war).matching {include 'WEB-INF/web.xml'}.singleFile
    assert webXml.text.contains('<display-name>dummy</display-name>') //forventer denne versjonen av web.xml (ikke generert fil)

}


task assertNoWebXmlInSourceSetOutputs() << {
    assert project.sourceSets.main.output.asFileTree.matching { include '**/web.xml' }.files.isEmpty()
    assert project.sourceSets.weblogic.output.asFileTree.matching { include '**/web.xml' }.files.isEmpty()
}

task assertGenWeblogic() << {
    assert !project.sourceSets.weblogic.output.asFileTree.matching { include 'exceptiondemo01/ExceptionService1WSBean.class' }.files.isEmpty()
    assert !project.sourceSets.weblogic.output.asFileTree.matching { include 'exceptiondemo01/ExceptionService2WSBean.class' }.files.isEmpty()
}

task assertCompileWeblogicJava() << {
    assert !project.sourceSets.weblogic.output.asFileTree.matching { include 'WebConfig.class' }.files.isEmpty()
}

task assertCompileJava() << {
    assert project.sourceSets.main.output.asFileTree.find {it.name == 'ServiceException.class'}
    assert project.sourceSets.main.output.asFileTree.find {it.name == 'ServiceFaultInfo.class'}
}


/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(List tasks, Map props = [:]) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks.collect {"${project.path}:${it}".toString()}
    sp.projectProperties = props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}
