apply plugin: 'sktools-dbtools-plugin'

//hjelpefunksjon for eksekveringsrekkefølge dersom task blir kjørt
def dependsOnIfExecuted = rootProject.getDependsOnIfExecuted()

def HISTORIKK_COLUM_NAMES = [TVERSION: 'TVERSION', TBEGIN_INFO: 'TBEGIN_INFO', TEND_INFO: 'TEND_INFO', TBEGIN: 'TBEGIN', TEND: 'TEND']


configureDatabasePlugin {
    useDrivers libraries.ojdbc

    project.ext.tns = "${historikk_db_sid}_${historikk_db_hostname}"


    /**
     * Toolset for DBA med script for:
     *
     *  - Vedlikehold av grants for brukere på systemnivå
     *  - Opprettelse/sletting av tablespace
     *  - Opprettelse/sletting av brukere
     */
    toolset(name: 'system', type: 'oracle', prefix: 'system') {

        sqlTask('CreateHistorikkTablespace', sqlFile: 'src/main/sql/demo/system/tablespace/CreateHistorikkTablespace.sql') {
            dependsOnIfExecuted it, sqlTask('DropHistorikkTablespace', sqlFile: 'src/main/sql/demo/system/tablespace/DropHistorikkTablespace.sql')
        }

        task('CreateUsers') {
            dependsOn sqlTask('CreateHistorikkUser', sqlFile: 'src/main/sql/demo/system/user/CreateHistorikkUser.sql') {
                dependsOnIfExecuted it, tasks['CreateHistorikkTablespace']
                dependsOnIfExecuted it, sqlTask('DropHistorikkUser', sqlFile: 'src/main/sql/demo/system/user/DropHistorikkUser.sql', failOnError: false)
            }
        }

        task('GrantUsers') {
            dependsOn sqlTask('GrantHistorikkUser', sqlFile: 'src/main/sql/demo/system/grant/GrantHistorikkUser.sql') {
                dependsOnIfExecuted it, tasks['CreateHistorikkUser']
            }
        }


        properties += [
                historikk_db_username: historikk_db_username,
                historikk_db_password: historikk_db_password,
                historikk_db_sid: historikk_db_sid,
                historikk_db_tablespace: historikk_db_tablespace,
                historikk_db_tablespace_index: historikk_db_tablespace_index,
        ]

        if (System.properties.containsKey('db.oradata')) { properties.put('db_oradata', System.getProperty('db.oradata')) }

        credentials.username = historikk_db_system_username
        credentials.password = historikk_db_system_password
        url = "jdbc:oracle:thin:@${historikk_db_hostname}:${historikk_db_port}:${historikk_db_sid}"
        driver = 'oracle.jdbc.OracleDriver'
    }


    /**
     * Toolset for SA-bruker med script for:
     *
     *  - Vedlikehold av grants for brukere på skjema-nivå
     *  - Opprettelse og vedlikehold av skjema (inkludert patching)
     *
     *  - Mekanikk for migrering til og fra historikk skjema
     */
    toolset(name: 'historikk', type: 'oracle', prefix: 'historikk') {

        task('UpdatePackages') {
            dependsOn sqlTask('UpdatePackageHistorikkSession', sqlFile: file('src/main/sql/demo/historikk/UpdatePackageHistorikkSession.sql')) {
                dependsOn sqlTask('UpdatePackageHistorikkTransaction', sqlFile: file('src/main/sql/demo/historikk/UpdatePackageHistorikkTransaction.sql')) {
                    dependsOn sqlTask('CreateTemporaryTables', sqlFile: file('src/main/sql/demo/historikk/CreateTemporaryTables.sql'), failOnError: false) //feiler ikke dersom tabell allerede finnes fra før
                }
            }
        }

        sqlTask('CreateHistorikkSchema', sqlFile: 'src/main/sql/demo/historikk/schema/CreatehistorikkSchema.sql') {
            dependsOn taskSequence('PurgeHistorikkSchema') {
                dependsOn sqlTask('PurgeHistorikkViews', sqlFile: 'src/main/sql/demo/historikk/schema/PurgeHistorikkViews.sql')
                dependsOn sqlTask('PurgeHistorikkTables', sqlFile: 'src/main/sql/demo/historikk/schema/PurgeHistorikkTables.sql')
                dependsOn sqlTask('PurgeHistorikkPackages', sqlFile: 'src/main/sql/demo/historikk/schema/PurgeHistorikkPackages.sql')
            }
        }


        task('GrantUsers') {
            dependsOn sqlTask('GrantSanntidUser', sqlFile: 'src/main/sql/demo/sanntid/grant/GrantSanntidUser.sql')
            dependsOn sqlTask('GrantReplicationUser', sqlFile: 'src/main/sql/demo/replication/grant/GrantReplicationUser.sql')
        }

        task('RevokeUsers') {
            dependsOn sqlTask('RevokeSanntidUser', sqlFile: 'src/main/sql/demo/sanntid/grant/RevokeSanntidUser.sql')
            dependsOn sqlTask('RevokeReplicationUser', sqlFile: 'src/main/sql/demo/replication/grant/RevokeReplicationUser.sql')
        }

        task('HistorikkForUsers') {
            dependsOn task('ProceduresForUsers') {
                dependsOn sqlTask('ProceduresForReplicationUser', sqlFile: 'src/main/sql/demo/replication/procedure/ProceduresForReplicationUser.sql')
            }
            dependsOn task('SynonymsForUsers') {
                dependsOn sqlTask('SynonymsForSanntidUser', sqlFile: 'src/main/sql/demo/sanntid/synonym/SynonymsForSanntidUser.sql')
            }
        }

        sqlTask('CreateViewsAndTriggers', sqlString:'') {
            dependsOn dbToolSets['historikk'].tasks['UpdatePackages']

            apply to: it, from: parent.file('genHistorikkViewsAndTriggers.gradle')
            doFirst {
                println "Genererer DDL for historikk views og legger dette til schema i databasen..."
            }

            doFirst {
                sqlString = genHistorikkViewsAndTriggers(
                        dbToolset: toolset,
                        historikkSourceSchema: historikk_db_schema,
                        historikkSchemaName: '@historikk_db_schema@',
                        historikkViewSchemaName: '@historikk_db_schema@',
                        includeTables: { it.endsWith('_H') },
                        historikkColumnNames: HISTORIKK_COLUM_NAMES,
                )
            }
            doLast {
                if (!logger.isEnabled(LogLevel.INFO)) {
                    logger.quiet "Legger inn view og triggere: \n\n ${sqlString}"
                }
            }
        }

        sqlTask('CreateSanntidTriggers', sqlString:'') {
            apply to: it, from: parent.file('genSanntidTriggers.gradle')
            doFirst {
                println "Genererer DDL for sanntids historikk triggere og legger dette til schema i databasen..."
            }

            doFirst {
                sqlString = genSanntidTriggers(
                        dbToolset: toolset,
                        sanntidSourceSchema: sanntid_db_schema,
                        sanntidSchemaName: "@sanntid_db_schema@",
                        historikkSchemaName: "@historikk_db_schema@",
                        excludeTables: {[
                                'SEQUENCE',
                        ].contains(it)},
                        historikkColumnNames: HISTORIKK_COLUM_NAMES,
                )
            }
            doLast {
                if (!logger.isEnabled(LogLevel.INFO)) {
                    logger.quiet "Legger inn view og triggere: \n\n ${sqlString}"
                }
            }
        }
        sqlTask('DropSanntidTriggers', sqlFile:'src/main/sql/demo/sanntid/trigger/DropSanntidTriggers.sql')


        properties += [
                historikk_db_username: historikk_db_username,
                historikk_db_schema: historikk_db_schema,
                historikk_db_tablespace: historikk_db_tablespace,
                historikk_db_tablespace_index: historikk_db_tablespace_index,
        ]

        //sanntid
        properties += [
                sanntid_db_username: sanntid_db_username,
                sanntid_db_schema: sanntid_db_schema,
        ]


        //replication
        properties += [
                replication_db_username: replication_db_username,
                replication_db_schema: replication_db_schema,
        ]


        credentials.username = historikk_db_system_username
        credentials.password = historikk_db_system_password
        url = "jdbc:oracle:thin:@${historikk_db_hostname}:${historikk_db_port}:${historikk_db_sid}"
        driver = 'oracle.jdbc.OracleDriver'
    }

    task('dbSetUpHistorikkUser', group: 'Database', description: 'Oppretter tablespace og bruker for Historikk data') {
        dependsOn dbToolSets['system'].tasks['CreateHistorikkTablespace']
        dependsOn dbToolSets['system'].tasks['CreateUsers']
        dependsOn dbToolSets['system'].tasks['GrantUsers']
    }

    taskSequence('dbTearDownHistorikkUser', group: 'Database', description: 'Sletter tablespace og bruker for Historikk data') {
        dependsOn dbToolSets['system'].tasks['DropHistorikkUser']
        dependsOn dbToolSets['system'].tasks['DropHistorikkTablespace']
    }

    taskSequence('dbCreateHistorikkSchema') {
        dependsOn dbToolSets['historikk'].tasks['CreateHistorikkSchema']
        dependsOn dbToolSets['historikk'].tasks['UpdatePackages']
        dependsOn dbToolSets['historikk'].tasks['CreateViewsAndTriggers']
    }

    task('dbGrantUsers', description: 'Grants for brukere') {
        dependsOn dbToolSets['system'].tasks['GrantUsers']
        dependsOn dbToolSets['historikk'].tasks['GrantUsers']
    }



    //global tasks...

    task('dbClean') {
        dependsOn 'dbTearDownHistorikkUser'
    }

    task('dbSetUpUsers') {
        dependsOn 'dbSetUpHistorikkUser'
    }

    taskSequence('dbInit') {
        dependsOn 'dbCreateHistorikkSchema'
        dependsOn 'dbGrantUsers'
        dependsOn dbToolSets['historikk'].tasks['HistorikkForUsers']
    }

    taskSequence('dbEngageHistorikk') {
        dependsOn dbToolSets['historikk'].tasks['CreateSanntidTriggers']
        dependsOn dbToolSets['historikk'].tasks['HistorikkForUsers']
        dependsOn 'dbGrantUsers'
    }

    taskSequence('dbDisengageHistorikk') {
        dependsOn dbToolSets['historikk'].tasks['RevokeSanntidUser']
        dependsOn dbToolSets['historikk'].tasks['DropSanntidTriggers']
    }

}



//task for kodegenerering av skjema for historikk
task genHistorikkSchemaTempateFromSchema() {

    apply to: it, from: parent.file('genHistorikkSchemaTempateFromSchema.gradle')
    doFirst {
        println "Genererer skjema DDL for historikk basert på skjema hentet ifra gjeldende skjema for sanntid.."
    }

    doLast {
        genHistorikkSchemaTempateFromSchema(
                filename: 'src/main/sql/demo/historikk/schema/CreateHistorikkSchema_generated.sql',
                dbToolset: dbToolSets['system'],
                sanntidSourceSchema: sanntid_db_schema,
                historikkSchemaName: "@historikk_db_schema@",
                excludeTables: {['SEQUENCE'].contains(it)},
                historikkColumnNames: HISTORIKK_COLUM_NAMES,
        )
    }
}

