apply plugin: 'sktools-filter-resources-plugin'
apply plugin: 'java'





task runDemo() {
    dependsOn 'testFilterResources'
}


task('testFilterResources', dependsOn: tasks.filterResources) {
    doFirst {
        assert file('build/filteredResources/main/someFile.txt').exists()
        file('build/filteredResources/main/someFile.txt').text.contains("version=${project.version}")
        file('build/filteredResources/main/someFile.txt').text.contains("testValue=@testValue@")
    }
}

