apply plugin: 'sktools-filter-resources-plugin'
apply plugin: 'java'





task runDemo() {
    dependsOn 'testFilterResources'
}


task('testFilterResources', dependsOn: tasks.filterResources) << {
    assert file('gen/main/resources/someFile.txt').exists()
    file('gen/main/resources/someFile.txt').text.contains("version=${project.version}")
    file('gen/main/resources/someFile.txt').text.contains("testValue=@testValue@")
}

