/******************************************************************************************************************** **
 *
 * Demonstrasjon på enkel bruk av plugin.
 *
 * En viser også eksempel implementasjon av 'gen' target.
 *
 ******************************************************************************************************************** */

apply plugin: 'sktools-xjc-plugin'
apply plugin: 'java'


sourceSets {
    main.xjc {
        schema {
            srcDir 'src/main/xsd'
            srcDir 'build/dynamic/xsd'
        }
    }
}

task('gen').description = "Genererte ressurser for alle sourceSets"

task zipSchemas(type: Zip) {
    classifier = 'schemas'
    from sourceSets.main.xjc.schemas.collect {it.source}
}

//integrasjon med xjc plugin
afterEvaluate {
    if (project.plugins.hasPlugin('sktools-xjc-plugin')) {
        project.tasks.withType(no.statkart.sktools.gradle.plugins.xjc.XjcCompile.class) {
            project.tasks.gen.dependsOn it
        }
    }
}

/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task runDemo() {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    Assert.that('clean', 'zipSchemas').describedAs("schemaArchive").leadsTo(project).withState {
        zipTree(tasks.zipSchemas.archivePath).asPath.contains 'simple.xsd'
    }

    Assert.that('clean', sourceSets.main.xjc[0].config.genTaskName).describedAs("schemaGeneratesSourceCode").leadsTo(project).withState {
        assertXjcGeneratedSources()
    }

    Assert.that('clean', 'assemble').describedAs("assembleTriggersSchemaGeneration").leadsTo(project).withState {
        assertXjcGeneratedSources()
        assertXjcClasses()
    }


    Assert.that('assemble').describedAs("modifiedGeneratedSourceFilesAssembles").prep {
        //'Tester at "dirty resources" ikke forekommer...'
        createDirtySchema('build/dynamic/xsd')

    }.leadsTo(project).withState {
        assertDirtySources()
        assertDirtyClasses()
    }

    Assert.that('assemble').describedAs("removingGeneratedSourceFilesRemovesAssembledOnes").prep {
        project.delete('build/dynamic/xsd')

    }.leadsTo(project).withState LogLevel.INFO, {
        assertNoDirtySources()
        assertNoDirtyClasses()
    }


    Assert.that('clean', 'gen').describedAs("genTaskCanTriggersXjc").leadsTo(project).withState {
        assertXjcGeneratedSources()
        assertXjcClasses()

        assertNoDirtySources()
        assertNoDirtyClasses()
    }

    //keep it tidy!
    Assert.that('clean').describedAs("housekeeping").leadsTo(project).withState {
        project.delete('gen')
    }

}




void createDirtySchema(def path) {
    project.file("${path}/other.xsd").with { File file ->
        project.logger.quiet "Creating file ${project.relativePath(file)}"
        file.parentFile.mkdirs()
        file.createNewFile()
        file.withPrintWriter { writer ->
//    file.withPrintWriter('UTF-8') { writer ->
            writer.print '''<?xml version="1.0" encoding="UTF-8"?>
            <xs:schema
                    version="1.0"
                    elementFormDefault="qualified"
                    targetNamespace="http://dirty"
                    xmlns="http://dirty"
                    xmlns:xs="http://www.w3.org/2001/XMLSchema"
                    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
                    jaxb:version="2.1">

                <xs:complexType name="Dirty">
                    <xs:sequence>
                        <xs:element name="var1" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>

            </xs:schema>
            '''
        }
    }
}


class Assert {
    def taskName
    String[] taskNames
    Project project
    List<Closure> prep = []

    static def previousTask = null

    static Assert that(String... taskNames) {
        Assert instance = new Assert(); instance.taskNames = taskNames; return instance
    }

    Assert describedAs(String taskName) {
        this.taskName = taskName; this
    }

    Assert prep(Closure prepProjectBeforeAsserts) {
        prep << [prepProjectBeforeAsserts]; this
    }

    Assert leadsTo(Project project = project) {
        this.project = project; this
    }

    Assert withState(LogLevel logLevel = null, Closure check) {
        def task = project.task(taskName, type: GradleBuild) {
            dir = project.projectDir
            tasks = taskNames
            startParameter.systemPropertiesArgs = [noMavenBootstrap: 'true']
            startParameter.projectProperties = [sktools_versjon:"${project.version}"]
            if (logLevel) startParameter.logLevel = logLevel
            prep.reverseEach { Closure beforeAsserts -> doFirst { beforeAsserts.setDelegate(this); beforeAsserts.run()}}
            doLast { check.setDelegate(this); check.run() }
            doFirst {
                println('--------------------------------------------------------------------------------');
                println "Testing use case: ${taskName} tasks=${taskNames}\n\n\n"
            }
            doLast {
                println "\n  ...end of test case: ${taskName}"
                println('--------------------------------------------------------------------------------\n\n');
            }
            outputs.upToDateWhen { false } //always run this...
        }
        project.tasks['runDemo'].dependsOn task

        if (previousTask) task.dependsOn previousTask //ordered execution of asserts...
        previousTask = task
        this
    }

    private void println(def message) {
        project.logger.quiet(message)
    }


    //convenience methods and asserts....


    void assertXjcGeneratedSources() {
        assert project.files(project.sourceSets.main.xjc[0].config.genOutputPath).asFileTree.files.find { it.name == 'SimpleType.java' }
    }

    void assertXjcClasses() {
        assert project.files(project.sourceSets.main.output).asFileTree.files.find { it.name == 'SimpleType.class' }
    }

    void assertDirtySources() {
        assert project.files(project.sourceSets.main.xjc[0].config.genOutputPath).asFileTree.files.find { it.name == 'Dirty.java' }
    }

    void assertDirtyClasses() {
        assert project.files(project.sourceSets.main.output).asFileTree.files.find { it.name == 'Dirty.class' }
    }

    void assertNoDirtySources() {
        assert !project.files(project.sourceSets.main.xjc[0].config.genOutputPath).asFileTree.files.find { it.name == 'Dirty.java' } //forventer ikke å finne Dirty.java blandt source
    }

    void assertNoDirtyClasses() {
        assert !project.files(project.sourceSets.main.output).asFileTree.files.find { it.name == 'Dirty.class' } //forventer ikke å finne Dirty.class blandt class filer
    }

}
