/******************************************************************************************************************** **
 * Demonstrasjon av bruk av multiple konfigurasjoner
 *
 * Verifiserer her at dependencies for 'other' konfigurasjon kommer med i IntelliJ prosjektet
 ******************************************************************************************************************** */

apply plugin: 'java'

sourceSets {
    other {
        compileClasspath += project.files("${System.getenv('JAVA_HOME')}/lib/tools.jar").stopExecutionIfEmpty() //legger til tools jar som compile dependency
    }

}


configurations {
    myNiftyLibs {
        description = "Konfigurasjon som inneholder alle kjekke bibliotek vi bruker"
    }

    other {
        extendsFrom myNiftyLibs //legger til noen libs som runtime dependency
    }

}



dependencies {
    myNiftyLibs 'commons-lang:commons-lang:2.6@jar'

    otherRuntime configurations.other

}






/******************************************************************************************************************** **
 * Diverse tasker som tester og demonstrerer implementasjonen
 ******************************************************************************************************************** */

task demo(dependsOn:'clean') {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'

    doLast {

        println 'Printer sourceSets definisjon...'
        forkGradle(['printSourceSets'])

        println 'Tester IntelliJ integrasjon før build...'
        forkGradle(['cleanIdea'])
        forkGradle(['ideaModule', 'assertIdeaModule'])

        println 'Tester IntelliJ integrasjon etter build...'
        forkGradle(['cleanIdea', 'build'])
        forkGradle(['ideaModule', 'assertIdeaModule'])

    }
}



task assertIdeaModule() << {

    file("${project.name}.iml").text.with {

        assert it.contains('<sourceFolder url="file://$MODULE_DIR$/src/main/java')
        assert it.contains('<sourceFolder url="file://$MODULE_DIR$/src/other/java')
        assert it.contains('<sourceFolder url="file://$MODULE_DIR$/src/test/java')

        assert it.contains('<root url="file://$MODULE_DIR$/build/resources/main')

        assert it.contains('commons-lang-2.6.jar!')  //forventer at denne ligger som runtime avhengighet
        assert it.contains('/lib/tools.jar!') //forventet compiletime avhengighet

    }

}


task printSourceSets() << {
    logger.info "SourceSets defined: "
    project.convention.plugins.java.sourceSets.each { s ->
        ['java', 'allJava', 'resources', 'filterResources', 'groovy', 'allGroovy', 'allSource'].each { id ->
            try {
                def prefix = "${s.name}.${id}"
                s."$id".srcDirs.each { println "$prefix <- ".padLeft(prefix.size() + 5, ' ') + project.relativePath(it); prefix = prefix.replaceAll(/./, ' ')  }
                println()
            } catch (MissingPropertyException mpe) {
                assert true //ok her
            }
        }
    }
}


/******************************************************************************************************************** **
 * Hjelpemetode for forking av gradle eksekveringer
 * Kun relevant for testing...
 ******************************************************************************************************************** */
void forkGradle(List tasks, Map props = [:]) {
    StartParameter sp = gradle.startParameter.newInstance()
    sp.taskNames = tasks
    sp.projectProperties = props
    GradleLauncher.newInstance(sp).run().rethrowFailure();
}


