/******************************************************************************************************************** **
 * Demonstrasjon av ulike måter en kan strukturere opp kildekoden på.
 *
 * Gradle grupperer kildekode via {@link org.gradle.api.tasks.SourceSet} i logiske enheter. Dette definerer hvor
 * kildekoden ligger deriblant ressursfiler samt plassering av det kompilerte resultatet. Merk at flere sourceSet
 * kan dele filer, og at filer kan ligge i flere forskjellige kataloger.
 *
 * Disse er løskoblet i forhold til {@link org.gradle.api.artifacts.Configuration}, noe som da i prinsipet faktisk
 * muliggjør deling av sourceSet på tvers av konfigurasjoner.
 *
 *
 * Demoene illustrerer vanlig, konvensjonell struktur, samt konfigurasjon av stuktur som ligner på hvordan
 * ant byggesystemet til matrikkelen var.
 ******************************************************************************************************************** */


allprojects {
    apply plugin: 'idea'
}


task demo() {
    description = 'Kjører en enkel demo for å teste funksjonaliteten'
}