apply plugin: 'java'
apply plugin: 'maven'

group = 'no.statkart.sktools.gradle'



dependencies {
    //'samlepom' av samtlige plugins [SKTOOLS-13]
    runtime project.childProjects.values()
}


def demosExecuted = 0

//task som eksekverer alle demo-prosjekter som evt måtte finnes
final def testAllDemos = task('testDemos', description: 'Eksekverer demoer for hvert plugin') {
    mustRunAfter project.tasks.test
    doLast {
        logger.lifecycle "\n...${demosExecuted} demos executed!"
    }
}

Closure setUpDemoTestingFor = { final Project pluginProject, final File demoDir ->
        //gradle 2.8 liker dårlig to GradleBuild invokasjoner i samme dir.
        Task runDemoTask = pluginProject.task('runDemo', type: GradleBuild) {
            dir = demoDir
            tasks = ['clean', 'runDemo']
            pluginProject.test.dependsOn it //part of test

            doFirst {
                logger.quiet '################################################################################'
                logger.quiet "## executing demo in ${rootProject.relativePath(dir)}"
                demosExecuted++
            }
            doLast {
                logger.quiet "\n  ...end of demo ${name}"
                logger.quiet '################################################################################\n\n'
            }
        }

        [runDemoTask].each { Task task ->
            task.startParameter.projectProperties = [sktools_versjon: "${pluginProject.version}", MAVEN_REPO: MAVEN_REPO, WEBLOGIC_HOME: WEBLOGIC_HOME]
            task.startParameter.systemPropertiesArgs = [noMavenBootstrap: 'true'];
            task.startParameter.offline = false;
            task.outputs.upToDateWhen { false } //always run this...
            task.shouldRunAfter pluginProject.tasks.test //kjøring av (optional) test før kjøring av demos
        }

        return runDemoTask
}

evaluationDependsOnChildren()
subprojects { Project childProject ->
    File demoDir = childProject.file("demos")
    if (demoDir.exists()) {
        logger.quiet "..demo found for ${childProject.getPath()}"

        childProject.task('testDemos') {
            dependsOn setUpDemoTestingFor(childProject, demoDir)
            testAllDemos.mustRunAfter it
        }
    } else {
        logger.warn "..no demo found for ${childProject.getPath()}"
    }
}


