plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'
}

group = 'no.statkart.sktools.gradle'

java {
    withSourcesJar()
}

gradlePlugin {
    plugins {
        properties {
            id = 'sktools.properties'
            implementationClass = 'no.statkart.sktools.gradle.plugins.properties.PropertiesPlugin'
        }
    }
}

dependencies {
    testImplementation project(':build-utils:test-utils')
}
