apply plugin: 'groovy'
apply plugin: 'maven-publish'

group = 'no.statkart.sktools.gradle'



dependencies {

    //gradle api til byggesystemm blir benyttet som std
    compile gradleApi()

    //test
    testCompile project(':build-utils:test-utils')
}


task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourceJar
        }
    }
}


