apply plugin: 'sktools-ideaextensions-plugin'
apply plugin: 'groovy'

sourceCompatibility = '1.6'
targetCompatibility = '1.6'

ideaExtensions {
    masks += '*.tmp'
    vcs 'Perforce'
}


tasks.idea.dependsOn task('genSpamfiler') {
    project.file('config').mkdirs()
    project.file('config/myconfig.tmp').createNewFile()
    project.file('config/myconfig2.properties').createNewFile()
    project.file('gradle.log').createNewFile()

}



//innkobling av plugin jar filer for gradle byggesystem
buildscript {
    rootProject.setProperty('PUBLIC_REPO', 'http://skrivap92.statkart.no:8001/nexus/content/groups/public/')

    repositories {
        if (project.gradle.gradleVersion >= '1.0-milestone-7') {
            mavenRepo name: 'public', url: "${rootProject.PUBLIC_REPO}"
        } else {
            //for gradle versions previos to 1.0-milestone-7
            mavenRepo name: 'public', urls: "${rootProject.PUBLIC_REPO}"
        }
        mavenLocal()
    }
    dependencies {
        classpath 'no.statkart.sktools.gradle:ideaextensions-plugin:1.0'
    }
}
