description = "Eksekverer installerte demoer for plugins. Dette forutsetter at disse er tilgjengeliggort i maven repo"

defaultTasks 'demo'

task demo(description: "Eksekverer alle demoer i underprosjekter via forket gradle") {
    /*
     * Bruker kommandolinje her for forking av gradle bygg.
     * Alle egenskaper som skal propagieres til demobygget må spesifiseres her.
     *
     * PS: Bruk av GradleExec gir problemer ved kjøring av idea/idea-extensions demo. Bruker derfor kommandolinje her.
     */

    doLast {
        project.projectDir.listFiles().each { demoDir ->
            if (demoDir.isDirectory() && !demoDir.name.startsWith('.') /* excluding folder ".gradle" */) {

                logger.quiet "Starting demo ${demoDir.name} in ${demoDir.absolutePath} ..."

                project.exec {
                    //windows
                    commandLine = "${gradle.gradleHomeDir}\\bin\\gradle.bat"
                    args "-b", "${project.relativePath(demoDir)}/build.gradle"
                    args "runDemo"
                    args "-PMAVEN_REPO=${MAVEN_REPO}"
                    args "-PWEBLOGIC_HOME=${WEBLOGIC_HOME}"
                    args "-PWEBLOGIC_VERSION=${WEBLOGIC_VERSION}"
                    args "-PMAVEN_REPO=${MAVEN_REPO}"
                    args "-Psktools_versjon=${version}" //fra vedlagt gradle.properties
                    args "--no-daemon"
                    args "--console=plain"
                    args "--full-stacktrace"

                    logger.quiet "Running ${commandLine}"
                }
            }
        }
    }
}

ext.MAVEN_REPO = rootProject.properties.get('MAVEN_REPO', System.getenv('MAVEN_REPO'))
if (ext.MAVEN_REPO == null) {
    ext.MAVEN_REPO = 'https://repo.maven.apache.org/maven2/'
    logger.warn "warning: MAVEN_REPO not defined. Defaulting to ${MAVEN_REPO}"
}

repositories {
    mavenLocal()
    maven { name = 'public'; url = MAVEN_REPO }
}


logger.quiet """
------------------------------------------------------------------------------------------------------------------------
SKTOOLS_VERSION=${version}
WEBLOGIC_VERSION=${project.properties.get('WEBLOGIC_VERSION', 'ikke satt')}
WEBLOGIC_HOME=${project.properties.get('WEBLOGIC_HOME', 'ikke satt')}
JAVA = ${System.getProperty('java.version')}
GRADLE = ${gradle.gradleVersion}
MAVEN_REPO = ${MAVEN_REPO}
------------------------------------------------------------------------------------------------------------------------"""

