apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'maven-publish'

java {
    withSourcesJar()
}

dependencies {
    implementation project(':build-utils:sql-parser')
    compileOnly gradleApi()
    implementation libraries.slf4j_api
    runtimeOnly libraries.slf4j_simple

    testImplementation project(':build-utils:test-utils')
    testImplementation localGroovy()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
