apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'maven-publish'

dependencies {
    implementation project(':build-utils:sql-parser')

    compileOnly gradleApi()
    implementation libraries.slf4j_api
    runtimeOnly libraries.slf4j_simple

    testImplementation project(':build-utils:test-utils')
    testImplementation localGroovy()
}


task sourceJar(type: Jar) {
    from sourceSets.main.allJava
    classifier 'sources'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourceJar
        }
    }
}
