group = 'no.statkart.sktools.gradle.plugins.wsclient-plugin.demos'

assert GradleVersion.current() >= GradleVersion.version('2.4') //lowest gradle version supported

//innkobling av plugin jar filer for gradle byggesystem
buildscript {
    if (rootProject.ext.has('sktools_versjon')) version = rootProject.ext.get('sktools_versjon')
    if (version == Project.DEFAULT_VERSION) { version = '1.4-SNAPSHOT'; logger.warn "No -Psktools_versjon= defined. Defaulting to \"${version}\""} //nb - dersom ikke default version er satt riktig så blir kjøring ifra demo-katalog feil..

    // Variables to grab from environment + defaults
    ['MAVEN_REPO'].each { val ->
        if (!rootProject.ext.has(val) && System.getenv(val) != null) {
            rootProject.ext.set(val, System.getenv(val))
        }
    }

    project.ext.set('MAVEN_REPO', project.properties.get('MAVEN_REPO', 'http://nexus.statkart.no:8090/nexus/content/groups/public/'))

    repositories {
        mavenLocal()
        maven { name = 'public'; url = MAVEN_REPO }
    }
    dependencies {
        classpath "no.statkart.sktools.gradle:wsimport-plugin:${version}"
    }
}

def clean = task('clean') {
    doFirst {
        logger.info "Cleaning project ${project.projectDir}"
    }
}

allprojects {
    setVersion(rootProject.version)
    tasks.matching { 'runDemo' == it.name }.each {
        it.mustRunAfter clean
    }

    repositories {
        mavenLocal()
        maven { name = 'public'; url = MAVEN_REPO }
    }
}
