apply plugin: 'sktools-filter-resources-plugin'
apply plugin: 'sktools-ideaextensions-plugin'
apply plugin: 'java'





task runDemo() {
    dependsOn 'testFilterResourcesAsSourceFolders'
}

tasks.clean.dependsOn tasks.cleanIdea
tasks.clean.doLast {
    project.delete 'gen', 'src'
}

task('testFilterResourcesAsSourceFolders', dependsOn: tasks.ideaModule) << {
    file("${project.name}.iml").text.with { fileContents ->
        [
                '$MODULE_DIR$/gen/main/resources',
                '$MODULE_DIR$/gen/test/resources',
        ].each {
            assert fileContents.contains(it) //forventer at iml fil inneholder filstier
        }

    }

}

