apply plugin: 'sktools-webstart-plugin'

description = 'Demonstrates how to make a simple webstart war module.'

configurations {
    client1Main {
        transitive = false
    }
    client1 {
        extendsFrom client1Main
    }
    client
}

dependencies {
    client1 'dom4j:dom4j:1.4@jar'
    client1Main project(path: ':echo-client')
    client1 'commons-lang:commons-lang:2.6@jar'
    client1 (['weblogic:wlfullclient_java5:10.3.5', 'weblogic:wlcipher:10.3.5', 'weblogic:cryptojfips:10.3.5'])
    client project(path: ':echo-client')
}

webstart {
    client1 {
        mainDependency configurations.client1Main
        jarDependencies configurations.client1
        sign rootProject.file('kodesignering.jks'), 'statenskartverk', 'SagZ45_p1'
        jnlp {
            jnlpFilename 'client1-signed.jnlp'
            title 'Client1 - signed'
            description 'Demonstrates signing of jars'
            application.mainClass 'WebstartTester'
            resources {
                javaRuntime '1.6+', '64m', '64m'    //means any rt with version 1.6 or greater
            }
        }
    }
    client2 {
        jarDependencies configurations.client
        jnlp {
            jnlpFilename 'client1-unsigned.jnlp'
            title 'Client1 - unsigned'
            description 'Demonstrates signing of jars'
            application.mainClass 'WebstartTester'
            resources {
                javaRuntime '1.6+', '64m', '64m'    //means any rt with version 1.6 or greater
            }
        }
    }
    client3 {
        jarDependencies configurations.client
        sign rootProject.file('kodesignering.jks'), 'statenskartverk', 'SagZ45_p1'
        jnlp {
            jnlpFilename 'runtimes-demo.jnlp'
            title 'Demo - multiple runtimes'
            description 'Demonstrates declaration of several runtimes'
            application.mainClass 'WebstartTester'
            resources {
                javaRuntime '1.5.0_14', '128m', '256m'
                javaRuntime '1.5.0_15 1.6.0_20', '128m', '256m'   //means the newest rt found among one in this list
                javaRuntime '1.6+', '64m', '64m'    //means any rt with version 1.6 or greater

            }
        }
    }
    client4 {
        jarDependencies configurations.client
        sign rootProject.file('kodesignering.jks'), 'statenskartverk', 'SagZ45_p1'
        jnlp {
            jnlpFilename 'properties.jnlp'
            title 'Demo - passing properties'
            description 'Demonstrates how to pass on properties to the application'
            resources {
                javaRuntime {   //means any rt with version 1.6 or greater
                    version '1.6+'
                    xms '128m'
                    xmx '256m'
                    vmArgs '-verbose -enableassertions'
                }

                systemProperties myProp1: 'test', myProp2: 'test2'
                systemProperties myProp3: 'test3'
            }
            resources {
                systemProperties myProp4: 'test4'
                systemProperties myProp5: 'test5'
            }
            application.mainClass 'WebstartTester'

        }
    }
}



task runDemo() {
    dependsOn 'testGenWebstart'
    dependsOn 'testClean'
}

task testGenWebstart(dependsOn: 'war') << {
    FileTree warTree = project.zipTree(war.archivePath)

    assert warTree.matching { include '*.jnlp' }.files.collect {it.name} as Set == ['client1-signed.jnlp', 'client1-unsigned.jnlp', 'runtimes-demo.jnlp', 'properties.jnlp'] as Set
    assert (warTree.matching { include 'lib/echo-client*.jar' }.files.collect {it.name} as Set).size() == 2 //forventer en signert (ganger 3 riktignok) og en usingert jar
}

task testClean(dependsOn: ['testGenWebstart', 'clean']) << {
    println 'todo'
}

repositories {
    mavenRepo name: 'public', url: rootProject.MAVEN_REPO
}
